hardkoded/puppeteer-sharp

- lib/PuppeteerSharp.Tests/Puppeteer/DownloaderTests.cs
- lib/PuppeteerSharp.Tests/Puppeteer/PuppeteerLaunch.cs
- lib/PuppeteerSharp.Tests/Puppeteer/PuppeteerLaunchTests.cs
- lib/PuppeteerSharp/Downloader.cs
- lib/PuppeteerSharp/Launcher.cs
- lib/PuppeteerSharp/NetworkManager.cs
- lib/PuppeteerSharp/Puppeteer.cs
- lib/PuppeteerSharp/PuppeteerOptions.cs
- lib/PuppeteerSharp/RevisionInfo.cs
> Download browser

- lib/PuppeteerSharp/Launcher.cs
- lib/PuppeteerSharp/Puppeteer.cs
We need to allow multiples chromium processors running at the same time
> Launcher should not be static

- lib/PuppeteerSharp.Tests/Page/PdfTests.cs
- lib/PuppeteerSharp.Tests/Page/ScreenshotTests.cs
- lib/PuppeteerSharp.Tests/TestConstants.cs
- lib/PuppeteerSharp/Page.cs
- lib/PuppeteerSharp/PdfOptions.cs
> Split PdfAsync and PdfStreamAsync functionalities

- .gitignore
> add testCert.cer to gitignore

- .gitignore
- demos/PuppeteerSharpDemos.sln
- demos/PuppeteerSharpPdfDemo/Program.cs
- demos/PuppeteerSharpPdfDemo/PuppeteerSharpPdfDemo.csproj
> Demo solution

- lib/PuppeteerSharp.Tests/Page/PdfTests.cs
- lib/PuppeteerSharp.Tests/Page/ScreenshotTests.cs
- lib/PuppeteerSharp.Tests/Puppeteer/PuppeteerLaunchTests.cs
- lib/PuppeteerSharp.Tests/PuppeteerLoaderCollection.cs
- lib/PuppeteerSharp.Tests/PuppeteerLoaderFixture.cs
This class will help us download chromium and set up a WebServer on a CI server.
Wanna take a look @Meir017 ?
> Implement PuppeteerLoaderFixture

- lib/PuppeteerSharp.TestServer/Startup.cs
- lib/PuppeteerSharp.Tests/Puppeteer/PuppeteerLaunchTests.cs
- lib/PuppeteerSharp/Launcher.cs
- lib/PuppeteerSharp/NetworkManager.cs
- lib/PuppeteerSharp/Page.cs
- lib/PuppeteerSharp/Puppeteer.cs
- lib/PuppeteerSharp/Response.cs
- lib/PuppeteerSharp/SecurityDetails.cs
solves #3 
This pull request is me just working out loud
I'll remove the `[WIP]` prefix when I'm done with it
> Implemented Puppeteer.launch tests

- lib/PuppeteerSharp.Tests/Puppeteer/PuppeteerLaunchTests.cs
- lib/PuppeteerSharp.Tests/TestConstants.cs
- lib/PuppeteerSharp/Connection.cs
- lib/PuppeteerSharp/LaunchOptions.cs
- lib/PuppeteerSharp/Launcher.cs
Processes are not being killed when the browser is closed
> Fix process leaks

- lib/PuppeteerSharp.Tests/Page/PdfTests.cs
- lib/PuppeteerSharp.Tests/Page/ScreenshotTests.cs
- lib/PuppeteerSharp.Tests/Puppeteer/PuppeteerLaunchTests.cs
- lib/PuppeteerSharp/Browser.cs
- lib/PuppeteerSharp/Connection.cs
- lib/PuppeteerSharp/Page.cs
> Implement IDisposable on Browser and Page

- lib/PuppeteerSharp.Tests/Page/UrlTests.cs
- lib/PuppeteerSharp.Tests/TestConstants.cs
> Page.Url tests

- demos/PuppeteerSharpPdfDemo/Program.cs
- demos/PuppeteerSharpPdfDemo/PuppeteerSharpPdfDemo.csproj
> Update demo to v0.3

- lib/PuppeteerSharp.Tests/PuppeteerLoaderFixture.cs
- lib/PuppeteerSharp.Tests/PuppeteerSharp.Tests.csproj
- lib/PuppeteerSharp/Connection.cs
- lib/PuppeteerSharp/Helpers/ProcessExtensions.cs
- lib/PuppeteerSharp/Launcher.cs
- lib/PuppeteerSharp/PuppeteerSharp.csproj
- lib/PuppeteerSharp/Session.cs
> Multi-platform support

- README.md
based on http://www.hardkoded.com/blogs/puppeteer-sharp-monthly-april-2018#progress
> updated README tests progress

- lib/PuppeteerSharp.Tests/Page/CookiesTests.cs
- lib/PuppeteerSharp.Tests/TestConstants.cs
- lib/PuppeteerSharp/BufferException.cs
- lib/PuppeteerSharp/ChromeProcessException.cs
- lib/PuppeteerSharp/CookieParam.cs
- lib/PuppeteerSharp/EvaluationFailedException.cs
- lib/PuppeteerSharp/InvalidTargetException.cs
- lib/PuppeteerSharp/MessageException.cs
- lib/PuppeteerSharp/NavigationException.cs
- lib/PuppeteerSharp/Page.cs
- lib/PuppeteerSharp/PuppeteerException.cs
- lib/PuppeteerSharp/Session.cs
- lib/PuppeteerSharp/TargetClosedException.cs
- lib/PuppeteerSharp/TargetCrashedException.cs
> implemented Page.cookies tests

- lib/PuppeteerSharp.Tests/Page/AuthenticateTests.cs
- lib/PuppeteerSharp.Tests/Page/EvaluateTests.cs
- lib/PuppeteerSharp.Tests/Page/PdfTests.cs
- lib/PuppeteerSharp.Tests/Page/SetContentTests.cs
- lib/PuppeteerSharp.Tests/Page/SetExtraHttpHeadersTests.cs
- lib/PuppeteerSharp.Tests/Page/SetJavaScriptEnabledTests.cs
- lib/PuppeteerSharp.Tests/Page/TitleTests.cs
- lib/PuppeteerSharp.Tests/PuppeteerBaseTest.cs
- lib/PuppeteerSharp.Tests/PuppeteerPageBaseTest.cs
resolves #111 page base test class
> Implement page base test class

- lib/PuppeteerSharp.Tests/Page/CookiesTests.cs
> use PuppeteerPageBaseTest in CookiesTests

- lib/PuppeteerSharp.Tests/FrameUtils.cs
- lib/PuppeteerSharp.Tests/Issues/Issue0100.cs
- lib/PuppeteerSharp.Tests/Page/EventsRequestTests.cs
- lib/PuppeteerSharp.Tests/Page/UrlTests.cs
- lib/PuppeteerSharp/NetworkManager.cs
- lib/PuppeteerSharp/Page.cs
- lib/PuppeteerSharp/Request.cs
> Implement Page.Events.Request tests

- lib/PuppeteerSharp.Tests/Page/EventsErrorTests.cs
- lib/PuppeteerSharp.Tests/Page/EventsRequestTests.cs
- lib/PuppeteerSharp.Tests/PuppeteerPageBaseTest.cs
- lib/PuppeteerSharp/ErrorEventArgs.cs
- lib/PuppeteerSharp/Page.cs
> Implement Page.Events.Error

- lib/PuppeteerSharp.Tests/Puppeteer/PuppeteerLaunchTests.cs
- lib/PuppeteerSharp/NavigationOptions.cs
Add at least one test that uses the options!
> Make navigation options all public!

- lib/PuppeteerSharp.Tests/Page/EmulateMediaTests.cs
- lib/PuppeteerSharp/MediaType.cs
- lib/PuppeteerSharp/Page.cs
> implemented Page.emulateMedia tests

- lib/PuppeteerSharp.Tests/PuppeteerSharp.Tests.csproj
- lib/PuppeteerSharp.Tests/test.runsettings
> Tests timeout

- README.md
- lib/PuppeteerSharp.Tests/Page/WaitForTests.cs
- lib/PuppeteerSharp.Tests/Puppeteer/PuppeteerLaunchTests.cs
- lib/PuppeteerSharp/Frame.cs
- lib/PuppeteerSharp/Page.cs
- lib/PuppeteerSharp/WaitForFunctionOptions.cs
- lib/PuppeteerSharp/WaitForFunctionPollingOption.cs
- lib/PuppeteerSharp/WaitForSelectorOptions.cs
- lib/PuppeteerSharp/WaitTask.cs
> Implemented Page.waitFor tests

- lib/PuppeteerSharp.Tests/Page/SetUserAgentTests.cs
closes #35 
the missing test `should emulate device user-agent`
> Implemented missing test in SetUserAgentTests

- lib/PuppeteerSharp.Tests/Frame/EvaluateTests.cs
- lib/PuppeteerSharp.Tests/FrameUtils.cs
> Implemented Frame.evaluate tests

- lib/PuppeteerSharp.Tests/Issues/Issue0100.cs
> Restore issue 100

- lib/PuppeteerSharp.Tests/Frame/EvaluateTests.cs
- lib/PuppeteerSharp.Tests/Frame/WaitForSelectorTests.cs
- lib/PuppeteerSharp.Tests/FrameUtils.cs
- lib/PuppeteerSharp/Frame.cs
- lib/PuppeteerSharp/Helper.cs
- lib/PuppeteerSharp/Page.cs
- lib/PuppeteerSharp/WaitTask.cs
> Implemented Frame.waitForSelector tests

- lib/PuppeteerSharp.Tests/Frame/EvaluateTests.cs
- lib/PuppeteerSharp.Tests/Frame/FrameManagementTests.cs
- lib/PuppeteerSharp.Tests/FrameUtils.cs
- lib/PuppeteerSharp.Tests/Page/Events/RequestTests.cs
- lib/PuppeteerSharp.Tests/Page/WaitForTests.cs
- lib/PuppeteerSharp.Tests/Puppeteer/PuppeteerConnectTests.cs
- lib/PuppeteerSharp.Tests/TestConstants.cs
- lib/PuppeteerSharp/Frame.cs
- lib/PuppeteerSharp/FrameManager.cs
- lib/PuppeteerSharp/Page.cs
> Implement Frame Management

- lib/PuppeteerSharp/NetworkManager.cs
- lib/PuppeteerSharp/Request.cs
- lib/PuppeteerSharp/ResourceType.cs
> Request.ResourceType enum

- lib/PuppeteerSharp.Tests/Connection/ConnectionTests.cs
> Implement Connection tests

- README.md
Based on https://ci.appveyor.com/project/kblok/puppeteer-sharp/branch/master
> Updated tests count

- lib/PuppeteerSharp.Tests/Page/EvaluateHandleTests.cs
> Implemented Page.evaluateHandle tests

- lib/PuppeteerSharp.Tests/Assets/injectedfile.js
- lib/PuppeteerSharp.Tests/Page/AddScriptTagTests.cs
- lib/PuppeteerSharp.Tests/PuppeteerSharp.Tests.csproj
- lib/PuppeteerSharp/AddScriptTagOptions.cs
- lib/PuppeteerSharp/Frame.cs
- lib/PuppeteerSharp/Page.cs
> Implemented Page.addScriptTag tests

- lib/PuppeteerSharp.Tests/Page/EvaluateOnNewDocumentTests.cs
- lib/PuppeteerSharp/Page.cs
> Implemented Page.evaluateOnNewDocument tests

- lib/PuppeteerSharp.Tests/Page/ExposeFunctionTests.cs
- lib/PuppeteerSharp/Page.cs
> Implemented exposeFunction tests

- lib/PuppeteerSharp.Tests/Page/GetElementsTests.cs
- lib/PuppeteerSharp.Tests/Page/QuerySelectorAllTests.cs
- lib/PuppeteerSharp/ElementHandle.cs
- lib/PuppeteerSharp/Frame.cs
- lib/PuppeteerSharp/JSHandle.cs
- lib/PuppeteerSharp/Page.cs
> Implemented Page.$$ tests

- lib/PuppeteerSharp.Tests/Frame/WaitForFunctionTests.cs
- lib/PuppeteerSharp.Tests/Input/InputTests.cs
- lib/PuppeteerSharp.Tests/Page/EmulateTests.cs
- lib/PuppeteerSharp.Tests/Page/EvalTests.cs
- lib/PuppeteerSharp.Tests/Page/GetElementTests.cs
- lib/PuppeteerSharp.Tests/Page/QuerySelectorTests.cs
- lib/PuppeteerSharp.Tests/Target/TargetTests.cs
- lib/PuppeteerSharp/ElementHandle.cs
- lib/PuppeteerSharp/Frame.cs
- lib/PuppeteerSharp/Page.cs
> Implemented Page.$ tests

- lib/PuppeteerSharp.Tests/Page/SelectTests.cs
- lib/PuppeteerSharp.Tests/PuppeteerSharp.Tests.csproj
- lib/PuppeteerSharp/Frame.cs
- lib/PuppeteerSharp/Page.cs
> Implement Page.SelectAsync

- lib/PuppeteerSharp.Tests/Page/EvalManyTests.cs
- lib/PuppeteerSharp/Extensions.cs
- lib/PuppeteerSharp/Page.cs
> Implemented Page.$$eval tests

- lib/PuppeteerSharp.Tests/Page/XPathTests.cs
- lib/PuppeteerSharp/ElementHandle.cs
- lib/PuppeteerSharp/Frame.cs
- lib/PuppeteerSharp/Page.cs
> Implemented Page.$x tests

- lib/PuppeteerSharp.Tests/Page/EvaluateTests.cs
> Implemented Page.evaluate tests using element and object handles

- lib/PuppeteerSharp.Tests/ElementHandleTests/HoverTests.cs
> Implement ElementHandle.HoverAsync

- lib/PuppeteerSharp.Tests/ElementHandleTests/ScreenshotTests.cs
- lib/PuppeteerSharp.Tests/Input/Dimensions.cs
- lib/PuppeteerSharp.Tests/Input/InputTests.cs
- lib/PuppeteerSharp.Tests/Page/ScreenshotTests.cs
- lib/PuppeteerSharp.Tests/Page/ViewPortTests.cs
- lib/PuppeteerSharp.Tests/Page/WaitForTests.cs
- lib/PuppeteerSharp.Tests/PuppeteerSharp.Tests.csproj
- lib/PuppeteerSharp.Tests/ScreenshotHelper.cs
- lib/PuppeteerSharp/Clip.cs
- lib/PuppeteerSharp/ElementHandle.cs
- lib/PuppeteerSharp/Page.cs
- lib/PuppeteerSharp/ScreenshotOptions.cs
- lib/PuppeteerSharp/Session.cs
- lib/PuppeteerSharp/ViewPortOptions.cs
> Implement ElementHandle.ScreenshotStreamAsync

- lib/PuppeteerSharp.Tests/ElementHandleTests/QuerySelectorTests.cs
- lib/PuppeteerSharp/ElementHandle.cs
> Implemented ElementHandle.$ tests

- lib/PuppeteerSharp.Tests/ElementHandleTests/QuerySelectorAllTests.cs
- lib/PuppeteerSharp.Tests/PuppeteerSharp.Tests.csproj
- lib/PuppeteerSharp/ElementHandle.cs
> Implemented ElementHandle.$$ tests

- lib/PuppeteerSharp.Tests/ExecutionContextTests/QueryObjectsTests.cs
- lib/PuppeteerSharp/ExecutionContext.cs
> Implemented ExecutionContext.queryObjects tests

- lib/PuppeteerSharp.Tests/BrowserTests/Events/DisconnectedTests.cs
- lib/PuppeteerSharp.Tests/BrowserTests/ProcessTests.cs
- lib/PuppeteerSharp.Tests/BrowserTests/UserAgentTests.cs
- lib/PuppeteerSharp.Tests/BrowserTests/VersionTests.cs
- lib/PuppeteerSharp.Tests/Issues/Issue0100.cs
- lib/PuppeteerSharp.Tests/PageTests/CloseTests.cs
- lib/PuppeteerSharp.Tests/PageTests/ScreenshotTests.cs
- lib/PuppeteerSharp.Tests/PuppeteerBaseTest.cs
- lib/PuppeteerSharp.Tests/PuppeteerBrowserBaseTest.cs
- lib/PuppeteerSharp.Tests/PuppeteerPageBaseTest.cs
- lib/PuppeteerSharp.Tests/PuppeteerTests/PuppeteerConnectTests.cs
- lib/PuppeteerSharp.Tests/PuppeteerTests/PuppeteerLaunchTests.cs
- lib/PuppeteerSharp/Browser.cs
- lib/PuppeteerSharp/Connection.cs
- lib/PuppeteerSharp/Launcher.cs
- lib/PuppeteerSharp/Session.cs
> Implement missing Launch Tests

- lib/PuppeteerSharp.Tests/PageTests/GoBackTests.cs
- lib/PuppeteerSharp/Messaging/PageGetNavigationHistoryResponse.cs
- lib/PuppeteerSharp/Page.cs
> Implement Page.GoBackAsync and Page.GoForwardAsync

- lib/PuppeteerSharp.Tests/PageTests/PdfTests.cs
- lib/PuppeteerSharp/Media/MarginOptions.cs
- lib/PuppeteerSharp/Media/PaperFormat.cs
- lib/PuppeteerSharp/Page.cs
- lib/PuppeteerSharp/PdfOptions.cs
> Use enum as format for Pdf generation

- lib/PuppeteerSharp.TestServer/SimpleServer.cs
- lib/PuppeteerSharp.Tests/PageTests/SetRequestInterceptionTests.cs
- lib/PuppeteerSharp/NetworkManager.cs
- lib/PuppeteerSharp/Page.cs
- lib/PuppeteerSharp/Payload.cs
- lib/PuppeteerSharp/Request.cs
> Implemented Page.setRequestInterception

- lib/PuppeteerSharp.TestServer/wwwroot/jscoverage/involved.html
- lib/PuppeteerSharp.TestServer/wwwroot/jscoverage/multiple.html
- lib/PuppeteerSharp.TestServer/wwwroot/jscoverage/ranges.html
- lib/PuppeteerSharp.TestServer/wwwroot/jscoverage/script1.js
- lib/PuppeteerSharp.TestServer/wwwroot/jscoverage/script2.js
- lib/PuppeteerSharp.TestServer/wwwroot/jscoverage/simple.html
- lib/PuppeteerSharp.TestServer/wwwroot/jscoverage/sourceurl.html
- lib/PuppeteerSharp.TestServer/wwwroot/jscoverage/unused.html
- lib/PuppeteerSharp.Tests/JSCoverageTests/JSCoverageTests.cs
- lib/PuppeteerSharp.Tests/JSCoverageTests/JSResetOnNavigationTests.cs
- lib/PuppeteerSharp.Tests/TestUtils.cs
- lib/PuppeteerSharp/Coverage.cs
- lib/PuppeteerSharp/CoverageEntry.cs
- lib/PuppeteerSharp/CoverageEntryPoint.cs
- lib/PuppeteerSharp/CoverageEntryRange.cs
- lib/PuppeteerSharp/JSCoverage.cs
- lib/PuppeteerSharp/Messaging/ProfilerTakePreciseCoverageResponse.cs
- lib/PuppeteerSharp/Session.cs
> Implement JSCoverage

- lib/PuppeteerSharp/AddTagOptions.cs
- lib/PuppeteerSharp/Browser.cs
- lib/PuppeteerSharp/ElementHandle.cs
- lib/PuppeteerSharp/Input/Keyboard.cs
- lib/PuppeteerSharp/Media/MediaType.cs
- lib/PuppeteerSharp/Mobile/DeviceDescriptor.cs
- lib/PuppeteerSharp/Page.cs
- lib/PuppeteerSharp/PageErrorEventArgs.cs
- lib/PuppeteerSharp/PuppeteerSharp.csproj
* Start generating the XML document so we get warnings.
* Fix broken XML comments
* Add missing comments
related to #236
> Page docs improvements

- lib/PuppeteerSharp.Tests/ElementHandleTests/ScreenshotTests.cs
- lib/PuppeteerSharp.Tests/Issues/Issue0100.cs
- lib/PuppeteerSharp.Tests/PageTests/PdfTests.cs
- lib/PuppeteerSharp.Tests/PageTests/ScreenshotTests.cs
- lib/PuppeteerSharp.Tests/ScreenshotHelper.cs
- lib/PuppeteerSharp/ElementHandle.cs
- lib/PuppeteerSharp/Page.cs
- lib/PuppeteerSharp/PdfOptions.cs
- lib/PuppeteerSharp/ScreenshotOptions.cs
> New ScreenshotDataAsync and PdfDataAsync methods

- README.md
- appveyor-demo.yml
- demos/PuppeteerSharpDemos-Local.sln
- demos/PuppeteerSharpPdfDemo/Program.cs
- demos/PuppeteerSharpPdfDemo/PuppeteerSharpPdfDemo-Local.csproj
- demos/PuppeteerSharpPdfDemo/PuppeteerSharpPdfDemo.csproj
This is more a public proof that the demo project works.
This guy won't build in every PR, only in master.
> Demo project test

- lib/PuppeteerSharp/Browser.cs
> added browser docs

- lib/PuppeteerSharp/Connection.cs
> Connection docs

- lib/PuppeteerSharp/Frame.cs
- lib/PuppeteerSharp/FrameManager.cs
- lib/PuppeteerSharp/Page.cs
> Frame docs

- lib/PuppeteerSharp/ExecutionContext.cs
> ExecutionContext docs

- lib/PuppeteerSharp.Tests/PuppeteerSharp.Tests.csproj
- lib/PuppeteerSharp/ElementHandle.cs
- lib/PuppeteerSharp/JSHandle.cs
- lib/PuppeteerSharp/Page.cs
- lib/PuppeteerSharp/Session.cs
- lib/PuppeteerSharp/TargetInfo.cs
> JSHandle docs

- lib/PuppeteerSharp/ElementHandle.cs
> ElementHandle docs

- lib/PuppeteerSharp.TestServer/wwwroot/serviceworkers/empty/sw.html
- lib/PuppeteerSharp.TestServer/wwwroot/serviceworkers/fetch/style.css
- lib/PuppeteerSharp.TestServer/wwwroot/serviceworkers/fetch/sw.html
- lib/PuppeteerSharp.TestServer/wwwroot/serviceworkers/fetch/sw.js
- lib/PuppeteerSharp.Tests/TargetTests/TargetTests.cs
- lib/PuppeteerSharp/Target.cs
> updated target tests

- lib/PuppeteerSharp.Tests/PageTests/ViewPortTests.cs
- lib/PuppeteerSharp/EmulationManager.cs
- lib/PuppeteerSharp/Page.cs
> updated page viewport tests

- appveyor.yml
> Add cache for nuget packages In appveyor CI

- lib/PuppeteerSharp.Tests/InputTests/InputTests.cs
- lib/PuppeteerSharp.Tests/PageTests/SetRequestInterceptionTests.cs
- lib/PuppeteerSharp/Downloader.cs
It's just a roll to Chromium 533271.
This is the source of truth for input changes https://github.com/GoogleChrome/puppeteer/pull/1938/files.
closes #277
> Add new SetRequestInterception Test

- lib/PuppeteerSharp.Tests/NetworkTests/NetworkEventTests.cs
- lib/PuppeteerSharp/Downloader.cs
- lib/PuppeteerSharp/Messaging/ResponseData.cs
- lib/PuppeteerSharp/NetworkManager.cs
- lib/PuppeteerSharp/Response.cs
> Update NetworkEventTests => Response.FromServiceWorker

- lib/PuppeteerSharp.Tests/FrameTests/ContextTests.cs
- lib/PuppeteerSharp/ExecutionContext.cs
- lib/PuppeteerSharp/FrameManager.cs
New Property `ExecutionContext.Frame`
closes #278
> Update Frame.Context tests

- lib/PuppeteerSharp.Tests/PageTests/Events/DOMContentLoadedTests.cs
- lib/PuppeteerSharp/Page.cs
> Implemented Page.Events.DOMContentLoaded

- lib/PuppeteerSharp.Tests/FrameTests/EvaluateHandleTests.cs
- lib/PuppeteerSharp/Frame.cs
> Implement Frame.EvaluateExpressionHandleAsync

- lib/PuppeteerSharp.Tests/PuppeteerTests/PuppeteerLaunchTests.cs
- lib/PuppeteerSharp/Helpers/StringExtensions.cs
- lib/PuppeteerSharp/Launcher.cs
> Closes issue #333 by handling paths with spaces in them.

- lib/PuppeteerSharp.Tests/FrameTests/WaitForSelectorTests.cs
- lib/PuppeteerSharp.Tests/FrameTests/WaitForXPathTests.cs
- lib/PuppeteerSharp.Tests/PageTests/WaitForTests.cs
- lib/PuppeteerSharp/Frame.cs
- lib/PuppeteerSharp/Page.cs
closes #274 
closes #273
closes #272
> Updated Page.waitFor & Frame.waitFor tests

- lib/PuppeteerSharp/Connection.cs
- lib/PuppeteerSharp/PuppeteerSharp.csproj
> Implement Connection.Delay

- lib/PuppeteerSharp/Launcher.cs
- lib/PuppeteerSharp/PuppeteerSharp.csproj
> Fix dispose deadlock

- lib/PuppeteerSharp.Tests/PuppeteerTests/AppModeTests.cs
- lib/PuppeteerSharp/LaunchOptions.cs
> Implement AppMode tests

- lib/PuppeteerSharp.Tests/Issues/Issue0343.cs
- lib/PuppeteerSharp/CookieParam.cs
> Increase CookieParam.Expires size

- lib/PuppeteerSharp.Tests/PageTests/EvaluateTests.cs
- lib/PuppeteerSharp/ExecutionContext.cs
> Throw error when page reloads during page.evaluate

- lib/PuppeteerSharp.Tests/PageTests/CloseTests.cs
- lib/PuppeteerSharp/Browser.cs
- lib/PuppeteerSharp/Page.cs
- lib/PuppeteerSharp/Target.cs
> Wait for the page to close in the browser in page.close

- lib/PuppeteerSharp.Tests/TargetTests/TargetTests.cs
- lib/PuppeteerSharp/Browser.cs
- lib/PuppeteerSharp/Helpers/FlexibleStringEnumConverter.cs
- lib/PuppeteerSharp/Target.cs
- lib/PuppeteerSharp/TargetInfo.cs
- lib/PuppeteerSharp/TargetType.cs
> Target refactor

- lib/PuppeteerSharp.TestServer/wwwroot/serviceworkers/fetch/sw.html
- lib/PuppeteerSharp.TestServer/wwwroot/serviceworkers/fetch/sw.js
- lib/PuppeteerSharp.Tests/NetworkTests/NetworkEventTests.cs
> Fix sw test

- lib/PuppeteerSharp.Tests/PageTests/GotoTests.cs
- lib/PuppeteerSharp/Response.cs
> response.ok should be true for file:// urls

- lib/PuppeteerSharp.Tests/FrameTests/WaitForSelectorTests.cs
- lib/PuppeteerSharp.Tests/FrameTests/WaitForXPathTests.cs
> Eliminate Racy Pattern

- lib/PuppeteerSharp.Tests/NetworkTests/NetworkEventTests.cs
- lib/PuppeteerSharp.Tests/PageTests/SetRequestInterceptionTests.cs
- lib/PuppeteerSharp/NetworkManager.cs
- lib/PuppeteerSharp/Request.cs
> Implement Request.RedirectChain API

- lib/PuppeteerSharp.Tests/PageTests/GotoTests.cs
- lib/PuppeteerSharp/NavigationException.cs
- lib/PuppeteerSharp/Page.cs
> Introduce url at error message at page.goto

- lib/PuppeteerSharp.TestServer/wwwroot/es6/.eslintrc
- lib/PuppeteerSharp.TestServer/wwwroot/es6/es6import.js
- lib/PuppeteerSharp.TestServer/wwwroot/es6/es6module.js
- lib/PuppeteerSharp.TestServer/wwwroot/es6/es6pathimport.js
- lib/PuppeteerSharp.Tests/Assets/es6/es6import.js
- lib/PuppeteerSharp.Tests/Assets/es6/es6module.js
- lib/PuppeteerSharp.Tests/Assets/es6/es6pathimport.js
- lib/PuppeteerSharp.Tests/PageTests/AddScriptTagTests.cs
- lib/PuppeteerSharp/AddTagOptions.cs
- lib/PuppeteerSharp/Frame.cs
> add type=module to addScriptTag

- lib/PuppeteerSharp.Tests/PageTests/Events/CloseTests.cs
- lib/PuppeteerSharp.Tests/PuppeteerTests/PuppeteerLaunchTests.cs
- lib/PuppeteerSharp/Browser.cs
- lib/PuppeteerSharp/NavigatorWatcher.cs
- lib/PuppeteerSharp/Page.cs
> Page Close event

- lib/PuppeteerSharp.Tests/FrameTests/FrameManagementTests.cs
- lib/PuppeteerSharp.Tests/PageTests/GoBackTests.cs
- lib/PuppeteerSharp.Tests/PageTests/WaitForNavigationTests.cs
- lib/PuppeteerSharp/Frame.cs
- lib/PuppeteerSharp/FrameManager.cs
- lib/PuppeteerSharp/Messaging/FrameDetachedResponse.cs
- lib/PuppeteerSharp/Messaging/NavigatedWithinDocumentResponse.cs
- lib/PuppeteerSharp/NavigatorWatcher.cs
- lib/PuppeteerSharp/Page.cs
> Support anchor navigation

- lib/PuppeteerSharp.TestServer/wwwroot/resetcss.html
- lib/PuppeteerSharp.Tests/ElementHandleTests/BoxModelTests.cs
- lib/PuppeteerSharp/BoxModel.cs
- lib/PuppeteerSharp/BoxModelPoint.cs
- lib/PuppeteerSharp/ElementHandle.cs
- lib/PuppeteerSharp/Messaging/BoxModelResponse.cs
> add ElementHandle.BoxModelAsync method

- lib/PuppeteerSharp.Tests/FrameTests/WaitForFunctionTests.cs
- lib/PuppeteerSharp/WaitForFunctionOptions.cs
- lib/PuppeteerSharp/WaitForSelectorOptions.cs
- lib/PuppeteerSharp/WaitTask.cs
> Add an option to disable timeout for WaitForFunctionAsync

- lib/PuppeteerSharp.Tests/PuppeteerTests/PuppeteerLaunchTests.cs
- lib/PuppeteerSharp/LaunchOptions.cs
- lib/PuppeteerSharp/Launcher.cs
- lib/PuppeteerSharp/Page.cs
- lib/PuppeteerSharp/Target.cs
Notice that we're ignoring everything related to pipe support
closes #395
> Options refactor

- lib/PuppeteerSharp.Tests/BrowserTests/Events/DisconnectedTests.cs
- lib/PuppeteerSharp.Tests/PuppeteerBaseTest.cs
- lib/PuppeteerSharp/Launcher.cs
> Consume protocol errors when initiating browser.close()

- lib/PuppeteerSharp.Tests/PageTests/EvaluateTests.cs
- lib/PuppeteerSharp/ExecutionContext.cs
> Fix Page.evaluate with Symbols in arrays

- lib/PuppeteerSharp.Tests/NetworkTests/NetworkEventTests.cs
- lib/PuppeteerSharp/NetworkManager.cs
- lib/PuppeteerSharp/PuppeteerSharp.csproj
- lib/PuppeteerSharp/Request.cs
- lib/PuppeteerSharp/Response.cs
> Explicitly throw on content request for redirect response

- lib/PuppeteerSharp/Launcher.cs
> launch chrome with --disable-dev-shm-usage by default

- lib/PuppeteerSharp.Tests/PageTests/Events/PageErrorTests.cs
- lib/PuppeteerSharp.Tests/PuppeteerBaseTest.cs
- lib/PuppeteerSharp.Tests/TargetTests/CreateCDPSessionTests.cs
- lib/PuppeteerSharp.Tests/TargetTests/TargetTests.cs
> Refactor WaitForEvents

- lib/PuppeteerSharp.TestServer/wwwroot/frames/one-frame.html
- lib/PuppeteerSharp.Tests/PageTests/WaitForNavigationTests.cs
- lib/PuppeteerSharp/Frame.cs
- lib/PuppeteerSharp/FrameManager.cs
- lib/PuppeteerSharp/Messaging/BasicFrameResponse.cs
> Page.waitForNavigation should correctly handle mixed content

- lib/PuppeteerSharp.Tests/FrameTests/WaitForFunctionTests.cs
- lib/PuppeteerSharp.Tests/FrameTests/WaitForSelectorTests.cs
- lib/PuppeteerSharp.Tests/FrameTests/WaitForXPathTests.cs
- lib/PuppeteerSharp/Frame.cs
- lib/PuppeteerSharp/Page.cs
- lib/PuppeteerSharp/WaitForFunctionOptions.cs
- lib/PuppeteerSharp/WaitForSelectorOptions.cs
- lib/PuppeteerSharp/WaitTask.cs
- lib/PuppeteerSharp/WaitTaskTimeoutException.cs
> Improve errors from frame.waitFor* methods

- lib/PuppeteerSharp.TestServer/PuppeteerSharp.TestServer.csproj
- lib/PuppeteerSharp.TestServer/SimpleServer.cs
- lib/PuppeteerSharp.TestServer/wwwroot/csp.html
- lib/PuppeteerSharp.Tests/FrameTests/WaitForFunctionTests.cs
- lib/PuppeteerSharp.Tests/PageTests/AddScriptTagTests.cs
- lib/PuppeteerSharp.Tests/PageTests/AddStyleTagTests.cs
- lib/PuppeteerSharp.Tests/PageTests/EvaluateOnNewDocumentTests.cs
- lib/PuppeteerSharp.Tests/PageTests/SetBypassCSPTests.cs
- lib/PuppeteerSharp/Frame.cs
- lib/PuppeteerSharp/Page.cs
> CSP support & Page.setBypassCSP

- lib/PuppeteerSharp/ViewPortOptions.cs
> Change property accessibility in ViewPortOptions

- lib/PuppeteerSharp.Tests/PageTests/ScreenshotTests.cs
- lib/PuppeteerSharp/ElementHandle.cs
- lib/PuppeteerSharp/Page.cs
- lib/PuppeteerSharp/ScreenshotOptions.cs
- lib/PuppeteerSharp/ScreenshotType.cs
closes #378 
closes #379  
We're introducing a breaking change here.
> Screenshot improvements

- lib/PuppeteerSharp/BrowserFetcher.cs
> Rolled Chromium to r555668

- lib/PuppeteerSharp.Tests/PageTests/BrowserTests.cs
- lib/PuppeteerSharp/Page.cs
- lib/PuppeteerSharp/Target.cs
> Add Page.Browser property

- lib/PuppeteerSharp/Page.cs
> add explanation to page.waitForNavigation

- lib/PuppeteerSharp/Mobile/DeviceDescriptorName.cs
- lib/PuppeteerSharp/Mobile/DeviceDescriptors.cs
> feat(DeviceDescriptors): add pixel2/pixel2 xl

- lib/PuppeteerSharp.Tests/PuppeteerTests/BrowserFetcherTests.cs
- lib/PuppeteerSharp/BrowserFetcher.cs
> DownloadAsync should return revision info even if the revision was already downloaded

- lib/PuppeteerSharp.Tests/Assets/one-style.css
- lib/PuppeteerSharp.Tests/Assets/one-style.html
- lib/PuppeteerSharp.Tests/PageTests/SetRequestInterceptionTests.cs
> Verify file url interception works as expected

- lib/PuppeteerSharp.TestServer/wwwroot/historyapi.html
- lib/PuppeteerSharp.Tests/PageTests/GotoTests.cs
- lib/PuppeteerSharp/Frame.cs
- lib/PuppeteerSharp/Page.cs
> test: Page.goto with 204

- lib/PuppeteerSharp/Launcher.cs
> feat(launcher): disable crash reporting by default

- lib/PuppeteerSharp.TestServer/wwwroot/popup/popup.html
- lib/PuppeteerSharp.TestServer/wwwroot/popup/window-open.html
- lib/PuppeteerSharp.Tests/TargetTests/TargetTests.cs
- lib/PuppeteerSharp/Browser.cs
- lib/PuppeteerSharp/Target.cs
- lib/PuppeteerSharp/TargetInfo.cs
> feat(targets): add target.opener()

- lib/PuppeteerSharp.Tests/PuppeteerTests/PuppeteerLaunchTests.cs
- lib/PuppeteerSharp/Launcher.cs
> implemented: launch browser with 'about:blank' by default

- lib/PuppeteerSharp.Tests/FrameTests/WaitForFunctionTests.cs
- lib/PuppeteerSharp/WaitTask.cs
> respect timeout 0 in page.waitForFunction

- lib/PuppeteerSharp.Tests/ElementHandleTests/EvaluateFunctionTests.cs
> added a missing test for elementHandle

- lib/PuppeteerSharp.Tests/PageTests/CloseTests.cs
- lib/PuppeteerSharp/Page.cs
> added page.IsClosed property

- lib/PuppeteerSharp.Tests/PuppeteerTests/PuppeteerLaunchTests.cs
- lib/PuppeteerSharp/Launcher.cs
> fix(browser): ensure first page is created when browser is launched

- lib/PuppeteerSharp.TestServer/wwwroot/frames/nested-frames.html
- lib/PuppeteerSharp.TestServer/wwwroot/grid.html
- lib/PuppeteerSharp.Tests/ElementHandleTests/ScreenshotTests.cs
> normalized scrollbars in headful tests

- lib/PuppeteerSharp.Tests/PuppeteerTests/PuppeteerLaunchTests.cs
- lib/PuppeteerSharp/Launcher.cs
> fixed: disable OOPIF by default

- lib/PuppeteerSharp/Browser.cs
- lib/PuppeteerSharp/Launcher.cs
- lib/PuppeteerSharp/Target.cs
> does not pass user options to browser constructor

- lib/PuppeteerSharp.Tests/PuppeteerTests/PuppeteerConnectTests.cs
> test: verify ignoreHTTPSErrors works with puppeteer.connect

- lib/PuppeteerSharp/ConsoleType.cs
> added verbose to ConsoleType

- lib/PuppeteerSharp.Tests/ElementHandleTests/EvaluateFunctionTests.cs
- lib/PuppeteerSharp/ElementHandle.cs
- lib/PuppeteerSharp/Extensions.cs
> added elementHandle.$$eval method

- lib/PuppeteerSharp/Helpers/AsyncFileHelper.cs
- lib/PuppeteerSharp/Payload.cs
- lib/PuppeteerSharp/Request.cs
As the Request class is never treated as a Payload we are removing that dependency.
closes #537
> Change accessibiilty on Payload.

- lib/PuppeteerSharp.Tests/BrowserContextTests/BrowserContextTests.cs
- lib/PuppeteerSharp/Browser.cs
- lib/PuppeteerSharp/BrowserContext.cs
- lib/PuppeteerSharp/Connection.cs
- lib/PuppeteerSharp/Launcher.cs
- lib/PuppeteerSharp/Messaging/CreateBrowserContextResponse.cs
- lib/PuppeteerSharp/Messaging/GetBrowserContextsResponse.cs
- lib/PuppeteerSharp/Target.cs
- lib/PuppeteerSharp/TargetInfo.cs
> feat(BrowserContext): introduce Browser Contexts

- lib/PuppeteerSharp.Tests/PageTests/ScreenshotTests.cs
- lib/PuppeteerSharp/ScreenshotOptions.cs
> Change ScreenshotOptions.Quality type

- lib/PuppeteerSharp.Tests/PageTests/ScreenshotTests.cs
- lib/PuppeteerSharp/ElementHandle.cs
- lib/PuppeteerSharp/Helpers/TaskQueue.cs
- lib/PuppeteerSharp/Page.cs
> Allow screenshot to return a base64 string

- README.md
We were taking the factor from another repo 😂
> Fix CodeFactor URL

- lib/PuppeteerSharp.Tests/PageTests/GotoTests.cs
- lib/PuppeteerSharp.Tests/PageTests/WaitForRequestTests.cs
- lib/PuppeteerSharp.Tests/PageTests/WaitForResponseTests.cs
- lib/PuppeteerSharp.Tests/TestConstants.cs
- lib/PuppeteerSharp/Helpers/TaskHelper.cs
- lib/PuppeteerSharp/Launcher.cs
- lib/PuppeteerSharp/NavigatorWatcher.cs
- lib/PuppeteerSharp/Page.cs
- lib/PuppeteerSharp/ResponseCreatedEventArgs.cs
- lib/PuppeteerSharp/WaitForOptions.cs
> Page.WaitForRequestAsync and Page.WaitForResponseAsync

- lib/PuppeteerSharp.TestServer/wwwroot/offscreenbuttons.html
- lib/PuppeteerSharp.Tests/ElementHandleTests/IsIntersectingViewportTests.cs
- lib/PuppeteerSharp.Tests/InputTests/InputTests.cs
- lib/PuppeteerSharp/ElementHandle.cs
> ElementHandle.IsIntersectingViewportAsync and Offsetclicks

- lib/PuppeteerSharp.TestServer/wwwroot/wrappedlink.html
- lib/PuppeteerSharp.Tests/InputTests/InputTests.cs
- lib/PuppeteerSharp/ElementHandle.cs
- lib/PuppeteerSharp/Messaging/GetContentQuadsResponse.cs
> Click wrapped links support

- lib/PuppeteerSharp.Tests/BrowserContextTests/BrowserContextTests.cs
- lib/PuppeteerSharp.Tests/PageTests/Events/ConsoleTests.cs
> Fix random tests flakiness

- lib/PuppeteerSharp/RequestAbortErrorCode.cs
> Add new error reasons for request.abort()

- lib/PuppeteerSharp.Tests/WorkerTests/WorkerTests.cs
- lib/PuppeteerSharp/Page.cs
- lib/PuppeteerSharp/Worker.cs
> Implement pageerror event from a worker

- lib/PuppeteerSharp.Tests/PageTests/WaitForNavigationTests.cs
- lib/PuppeteerSharp/Page.cs
> Clarify docs about waitForNavigation

- lib/PuppeteerSharp/Frame.cs
- lib/PuppeteerSharp/FrameManager.cs
> Don't pass a reference to the page into frames

- lib/PuppeteerSharp/Messaging/BindingCalledResponse.cs
- lib/PuppeteerSharp/Page.cs
> Migrate exposeFunction from console.debug to Runtime.installBinding

- lib/PuppeteerSharp.Tests/PageTests/CloseTests.cs
- lib/PuppeteerSharp.Tests/PageTests/CookiesTests.cs
- lib/PuppeteerSharp.Tests/PageTests/EvaluateTests.cs
- lib/PuppeteerSharp.Tests/PuppeteerTests/PuppeteerLaunchTests.cs
- lib/PuppeteerSharp/CDPSession.cs
- lib/PuppeteerSharp/Connection.cs
- lib/PuppeteerSharp/EvaluationFailedException.cs
- lib/PuppeteerSharp/ExecutionContext.cs
- lib/PuppeteerSharp/MessageException.cs
- lib/PuppeteerSharp/PuppeteerException.cs
Breaking Change: Now EvaluateFunctionHandleAsync and EvaluateExpressionHandleAsync will throw an EvaluationException.
closes #481
> Nicer protocol error messages

- lib/PuppeteerSharp.Tests/FrameTests/WaitForFunctionTests.cs
- lib/PuppeteerSharp/WaitTask.cs
> Fix race condition in WaitTask

- lib/PuppeteerSharp.Tests/PuppeteerTests/HeadfulTests.cs
- lib/PuppeteerSharp.Tests/PuppeteerTests/PuppeteerLaunchTests.cs
- lib/PuppeteerSharp.Tests/TargetTests/TargetTests.cs
Reference: https://github.com/GoogleChrome/puppeteer/commit/07b91f61a9cc2352e8175bd22abdbd253659fb46#diff-24ad699ffd13b0c06bf487e8ecf238ab
> Split headful tests

- lib/PuppeteerSharp.Tests/Issues/Issue0616.cs
- lib/PuppeteerSharp/Payload.cs
- lib/PuppeteerSharp/Request.cs
> Improve Request overrides on ContinueAsync

- lib/PuppeteerSharp/ChromiumProcess.cs
> Always add `about:blank` to default arguments

- lib/PuppeteerSharp/BrowserFetcher.cs
> Bump Chromium version to 575458

- lib/PuppeteerSharp.Tests/PageTests/SetRequestInterceptionTests.cs
- lib/PuppeteerSharp/Payload.cs
> Remove header 'cookie' from request hash

- lib/PuppeteerSharp.Tests/PuppeteerTests/HeadfulTests.cs
> Fix flakiness of certain extension tests

- lib/PuppeteerSharp/FrameManager.cs
- lib/PuppeteerSharp/Page.cs
> Don't emit an internal error when eval causes navigation

- lib/PuppeteerSharp.Tests/BrowserContextTests/BrowserContextTests.cs
- lib/PuppeteerSharp/Browser.cs
- lib/PuppeteerSharp/BrowserContext.cs
> Add BrowserContext.Pages() method

- lib/PuppeteerSharp.Tests/JSCoverageTests/JSCoverageTests.cs
- lib/PuppeteerSharp/Page.cs
> Try to fix CSS coverage flakes on win

- lib/PuppeteerSharp.Tests/PageTests/WaitForNavigationTests.cs
> Unflake page test that was causing us a lot of CI flakes

- lib/PuppeteerSharp.Tests/InputTests/InputTests.cs
- lib/PuppeteerSharp/Input/Keyboard.cs
> Typing emoji

- lib/PuppeteerSharp.Tests/PageTests/SetRequestInterceptionTests.cs
- lib/PuppeteerSharp/Page.cs
- lib/PuppeteerSharp/Payload.cs
- lib/PuppeteerSharp/Request.cs
Also Headers should be a `Dictionary<string, string>`
closes #555
> Make sure referer header is reported with request interception

- lib/PuppeteerSharp/Page.cs
- lib/PuppeteerSharp/PdfOptions.cs
> Add 'PreferCSSPageSize' to PdfOptions

- lib/PuppeteerSharp.Tests/PageTests/EvalManyTests.cs
- lib/PuppeteerSharp.Tests/PageTests/EvalTests.cs
- lib/PuppeteerSharp/Extensions.cs
EvaluateFunctionAsync extensions now works with resolved tasks
> Extension improvements

- lib/PuppeteerSharp/Frame.cs
- lib/PuppeteerSharp/WaitTaskTimeoutException.cs
> Make WaitTaskTimeoutException public

- lib/PuppeteerSharp.Tests/InputTests/InputTests.cs
- lib/PuppeteerSharp/ElementHandle.cs
- lib/PuppeteerSharp/Page.cs
> Page.ClickAsync should work with disabled javascript

- lib/PuppeteerSharp/Connection.cs
> Force KeepAliveInterval to 0

- lib/PuppeteerSharp.Tests/ConnectionTests/ConnectionTests.cs
- lib/PuppeteerSharp/CDPSession.cs
- lib/PuppeteerSharp/Connection.cs
- lib/PuppeteerSharp/PuppeteerSharp.csproj
- lib/PuppeteerSharp/WaitTaskTimeoutException.cs
> Remove callback items

- lib/PuppeteerSharp.Tests/Issues/Issue0648.cs
- lib/PuppeteerSharp/ResourceType.cs
> New ResourceType.Ping

- lib/PuppeteerSharp.Tests/PageTests/GotoTests.cs
- lib/PuppeteerSharp/Frame.cs
- lib/PuppeteerSharp/Messaging/PageNavigateResponse.cs
- lib/PuppeteerSharp/NavigatorWatcher.cs
- lib/PuppeteerSharp/Page.cs
- lib/PuppeteerSharp/WaitTask.cs
> Page.goto should properly handle historyAPI in beforeunload

- lib/PuppeteerSharp/ExecutionContext.cs
- lib/PuppeteerSharp/Frame.cs
- lib/PuppeteerSharp/FrameManager.cs
- lib/PuppeteerSharp/JSHandle.cs
- lib/PuppeteerSharp/Page.cs
- lib/PuppeteerSharp/Worker.cs
> Drop object factory from execution context

- lib/PuppeteerSharp/NetworkManager.cs
- lib/PuppeteerSharp/Request.cs
> Create Request class right away from payload

- lib/PuppeteerSharp/PdfOptions.cs
> Improve PdfOptions documentation

- lib/PuppeteerSharp.Tests/PageTests/GotoTests.cs
- lib/PuppeteerSharp/NavigationOptions.cs
- lib/PuppeteerSharp/Page.cs
> Add 'referer' as a parameter to Page.GoToAsync

- lib/PuppeteerSharp/CDPSession.cs
- lib/PuppeteerSharp/ElementHandle.cs
- lib/PuppeteerSharp/Page.cs
This is more for consistency with Puppeteer.
closes #599
> Fix null-type bugs

- lib/PuppeteerSharp.Tests/PageTests/SetRequestInterceptionTests.cs
- lib/PuppeteerSharp/Extensions.cs
> New ignored tests + new extension functions

- lib/PuppeteerSharp/Launcher.cs
- lib/PuppeteerSharp/Puppeteer.cs
> Launch with Environment Variables

- lib/PuppeteerSharp.Tests/PageTests/SelectTests.cs
> added failing test for page.select

- lib/PuppeteerSharp/BrowserFetcher.cs
> Fixed windows fetching & rolled Chromium to r590951

- lib/PuppeteerSharp/SecurityDetails.cs
> docs: Fixed description of SecurityDetails class

- lib/PuppeteerSharp/BrowserFetcher.cs
this address #666 
Ran all the test locally as well.
> bump the version of chromium

- lib/PuppeteerSharp.Tests/ElementHandleTests/ScreenshotTests.cs
Handles issue #668 
Fails currently a `TargetClosedException`
> Add zero width element test

- lib/PuppeteerSharp.Tests/PageTests/EvaluateTests.cs
- lib/PuppeteerSharp/ExecutionContext.cs
Fixes bug relating to #652 caused by insufficient test of JToken when returning null
> Fix bug affecting evaluation of string using Evaluate* methods

- lib/PuppeteerSharp.Tests/PuppeteerTests/PuppeteerLaunchTests.cs
- lib/PuppeteerSharp/Page.cs
> Fix full page screenshot when defaultViewport is null

- lib/PuppeteerSharp/NavigatorWatcher.cs
- lib/PuppeteerSharp/Page.cs
> Unify response tracking in page.goto and waitForNavigation

- lib/PuppeteerSharp.Tests/BrowserTests/Events/DisconnectedTests.cs
- lib/PuppeteerSharp/CDPSession.cs
- lib/PuppeteerSharp/Connection.cs
- lib/PuppeteerSharp/IConnection.cs
- lib/PuppeteerSharp/NavigatorWatcher.cs
- lib/PuppeteerSharp/Page.cs
closes #671 
based on #698 to avoid conflicts
>  Browser closing/disconnecting should abort navigations

- lib/PuppeteerSharp/CDPSession.cs
- lib/PuppeteerSharp/Connection.cs
- lib/PuppeteerSharp/WaitTask.cs
Made integer increments use Interlocked and replace dictionary with ConcurrentDictionary to resolve issue #714
> Made CDPSession, Connection and WaitTask more threadsafe

- lib/PuppeteerSharp/NetworkManager.cs
This will help us with #717 and #331
> Check if frame exists before creating a Request

- lib/PuppeteerSharp/BrowserFetcher.cs
> Roll chromium to r599821

- lib/PuppeteerSharp.Tests/PageTests/SetRequestInterceptionTests.cs
- lib/PuppeteerSharp/Payload.cs
> PostData should be a string

- lib/PuppeteerSharp.Tests/CSSCoverageTests/CSSCoverageTests.cs
- lib/PuppeteerSharp/PageCoverage/CSSCoverage.cs
> Don't prematurely disable the CSS domain

- lib/PuppeteerSharp/Input/KeyDefinitions.cs
> Add missing location property to some key descriptors

- lib/PuppeteerSharp.Tests/PageTests/ExposeFunctionTests.cs
- lib/PuppeteerSharp.Tests/PuppeteerTests/HeadfulTests.cs
> Add missing test

- lib/PuppeteerSharp/ChromiumProcess.cs
> Add flags to improve reliability

- lib/PuppeteerSharp.TestServer/wwwroot/input/rotatedButton.html
- lib/PuppeteerSharp.Tests/InputTests/InputTests.cs
- lib/PuppeteerSharp/ElementHandle.cs
> Handle negative area results in computeQuadArea

- lib/PuppeteerSharp/Connection.cs
- lib/PuppeteerSharp/PuppeteerSharp.csproj
- lib/PuppeteerSharp/Transport/IConnectionTransport.cs
- lib/PuppeteerSharp/Transport/WebSocketTransport.cs
This will help us implement a better transport for ASP.NET Full Framework.
> Improve IConnectionTransport

- lib/PuppeteerSharp/ChromiumProcess.cs
- lib/PuppeteerSharp/Frame.cs
- lib/PuppeteerSharp/Launcher.cs
- lib/PuppeteerSharp/NetworkManager.cs
- lib/PuppeteerSharp/Page.cs
- lib/PuppeteerSharp/Target.cs
- lib/PuppeteerSharp/Tracing.cs
- lib/PuppeteerSharp/WaitTask.cs
We are basically adding a few missing ConfigureAwaits, Replacing SetResult with TrySetResult and some code formatting
> Code cleanup

- lib/PuppeteerSharp/Helpers/TaskHelper.cs
- lib/PuppeteerSharp/NavigatorWatcher.cs
- Removed unused `TaskCompletitionSource`
- Used static array instead of creating one on each navigation
> Removed couple of common allocations

- lib/PuppeteerSharp.Tests/BrowserTests/Events/DisconnectedTests.cs
- lib/PuppeteerSharp/FrameManager.cs
- lib/PuppeteerSharp/LifecycleWatcher.cs
- lib/PuppeteerSharp/PuppeteerSharp.csproj
- lib/PuppeteerSharp/TargetClosedException.cs
* Add CloseReason to the message.
* Improve WhenAny code.
> Improve TargetClosedException

- lib/PuppeteerSharp/Browser.cs
- lib/PuppeteerSharp/FrameManager.cs
- lib/PuppeteerSharp/Helpers/TaskHelper.cs
- lib/PuppeteerSharp/LifecycleWatcher.cs
- lib/PuppeteerSharp/Page.cs
> Replace timeouts with CancellationTokens

- lib/PuppeteerSharp.DevicesFetcher/PuppeteerSharp.DevicesFetcher.csproj
- lib/PuppeteerSharp.TestServer/PuppeteerSharp.TestServer.csproj
- lib/PuppeteerSharp.Tests.DumpIO/PuppeteerSharp.Tests.DumpIO.csproj
- lib/PuppeteerSharp.Tests/PuppeteerSharp.Tests.csproj
- lib/PuppeteerSharp/PuppeteerSharp.csproj
> Upgrade to C# 7.3

- appveyor-linux.yml
- lib/PuppeteerSharp.Tests/FrameTests/GoToTests.cs
- lib/PuppeteerSharp/Response.cs
It seems that `ValueTask` was generating some random Index our of range exception
https://ci.appveyor.com/project/kblok/puppeteer-sharp-esipd/builds/21193962#L255
> Change TextAsync output type

- lib/PuppeteerSharp/CDPSession.cs
- lib/PuppeteerSharp/Connection.cs
- lib/PuppeteerSharp/Helpers/TaskHelper.cs
This will prevent the code from hanging if the connection with Chromium is lost.
> Cancel task if the connection was closed

- appveyor-demo.yml
- appveyor-linux.yml
- appveyor.yml
- lib/PuppeteerSharp.DevicesFetcher/PuppeteerSharp.DevicesFetcher.csproj
- lib/PuppeteerSharp.Tests.DumpIO/PuppeteerSharp.Tests.DumpIO.csproj
- lib/PuppeteerSharp.Tests/PuppeteerSharp.Tests.csproj
- lib/PuppeteerSharp.Tests/PuppeteerTests/PuppeteerLaunchTests.cs
> Upgrade .NET Core projects to 2.2

- lib/PuppeteerSharp.Tests/PageTests/GotoTests.cs
Trying to fix this hang https://ci.appveyor.com/project/kblok/puppeteer-sharp-esipd/builds/21304579/tests
I moved some code there, maybe it will fix it. But I added some `WithTimeouts` so if it happens again we don't hang and we know where is the fail.
> Fix race conditions on ShouldWaitForNetworkIdleToSucceedNavigation

- lib/PuppeteerSharp.Tests/PageTests/SetRequestInterceptionTests.cs
This will help us with this https://ci.appveyor.com/project/kblok/puppeteer-sharp/builds/21355031/job/xjg7hbw9tqg865xi#L236
> Fix race conditions on ShouldContainRefererHeader

- lib/PuppeteerSharp.Tests/FrameTests/WaitForXPathTests.cs
- lib/PuppeteerSharp/Helpers/TaskHelper.cs
It won't fix the issue but it will let us see if this is the line hanging here https://ci.appveyor.com/project/kblok/puppeteer-sharp/builds/21378483/job/g7kjejvsl703e6nf#L239
> Evaluate race conditions on HiddenShouldWaitForDisplayNone

- lib/PuppeteerSharp/Helpers/TaskHelper.cs
- lib/PuppeteerSharp/Transport/WebSocketTransport.cs
- lib/PuppeteerSharp/WaitTask.cs
Based on https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/master/AsyncGuidance.md#always-create-taskcompletionsourcet-with-taskcreationoptionsruncontinuationsasynchronously
> Dispose CancellationTokens

- lib/PuppeteerSharp/Browser.cs
- lib/PuppeteerSharp/CDPSession.cs
- lib/PuppeteerSharp/ChromiumProcess.cs
- lib/PuppeteerSharp/Connection.cs
- lib/PuppeteerSharp/Frame.cs
- lib/PuppeteerSharp/FrameManager.cs
- lib/PuppeteerSharp/Helpers/TaskHelper.cs
- lib/PuppeteerSharp/Launcher.cs
- lib/PuppeteerSharp/LifecycleWatcher.cs
- lib/PuppeteerSharp/Page.cs
- lib/PuppeteerSharp/Response.cs
- lib/PuppeteerSharp/Target.cs
- lib/PuppeteerSharp/Tracing.cs
- lib/PuppeteerSharp/WaitTask.cs
- lib/PuppeteerSharp/Worker.cs
Add TaskCreationOptions.RunContinuationsAsynchronously based on https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/master/AsyncGuidance.md#always-create-taskcompletionsourcet-with-taskcreationoptionsruncontinuationsasynchronously
> Add TaskCreationOptions.RunContinuationsAsynchronously to TaskCompletionSources

- lib/PuppeteerSharp.Tests/PuppeteerTests/BrowserFetcherTests.cs
- lib/PuppeteerSharp/BrowserFetcher.cs
> No need to fix file permissions on Mac

- lib/PuppeteerSharp/FrameManager.cs
- lib/PuppeteerSharp/Messaging/MessageKeys.cs
- lib/PuppeteerSharp/Messaging/PageFrameAttachedResponse.cs
- lib/PuppeteerSharp/Messaging/PageFrameNavigatedResponse.cs
- lib/PuppeteerSharp/Messaging/RuntimeExceptionThrownResponse.cs
- lib/PuppeteerSharp/Messaging/RuntimeExecutionContextCreatedResponse.cs
- lib/PuppeteerSharp/Messaging/RuntimeExecutionContextDestroyedResponse.cs
- lib/PuppeteerSharp/Messaging/TargetAttachedToTargetResponse.cs
- lib/PuppeteerSharp/Messaging/TargetDetachedFromTargetResponse.cs
- lib/PuppeteerSharp/Page.cs
- lib/PuppeteerSharp/Worker.cs
> Implement Response classes for all MessageDatas

- lib/PuppeteerSharp/BrowserFetcher.cs
> Roll Chromium to r624487

- lib/PuppeteerSharp.Tests/PageTests/BrowserContextTests.cs
- lib/PuppeteerSharp/Page.cs
> add Page.BrowserContext

- lib/PuppeteerSharp.Tests/PageTests/SetRequestInterceptionTests.cs
- lib/PuppeteerSharp/Payload.cs
> Relax request matching heuristic

- lib/PuppeteerSharp.Tests/ElementHandleTests/ScreenshotTests.cs
- lib/PuppeteerSharp/ElementHandle.cs
- lib/PuppeteerSharp/Page.cs
> Throw on 0x0 screenshots

- lib/PuppeteerSharp.Tests/FrameTests/EvaluateTests.cs
- lib/PuppeteerSharp.Tests/FrameTests/FrameManagementTests.cs
- lib/PuppeteerSharp/Frame.cs
> Make sure evaluation does not hang in detached iframes

- lib/PuppeteerSharp.Tests/JSCoverageTests/JSCoverageTests.cs
> add failing test for skipping all debugger statements

- lib/PuppeteerSharp.TestServer/wwwroot/consolelog.html
- lib/PuppeteerSharp.Tests/PageTests/Events/ConsoleTests.cs
- lib/PuppeteerSharp/Page.cs
> Ignore console messages from destroyed execution contexts

- lib/PuppeteerSharp/ResourceType.cs
> Flexible ResourceType parse

- lib/PuppeteerSharp.Tests/PageTests/Events/PopupTests.cs
- lib/PuppeteerSharp.Tests/TestConstants.cs
- lib/PuppeteerSharp/Page.cs
- lib/PuppeteerSharp/PopupEventArgs.cs
- lib/PuppeteerSharp/Target.cs
> Introduce Popup event

- lib/PuppeteerSharp.Tests/PageTests/SetRequestInterceptionTests.cs
- lib/PuppeteerSharp/Payload.cs
> filter out "intervention" header

- lib/PuppeteerSharp.Tests/PageTests/SetContentTests.cs
- lib/PuppeteerSharp/Frame.cs
- lib/PuppeteerSharp/LifecycleWatcher.cs
> Fix repetititive setContent calls

- lib/PuppeteerSharp/ChromiumProcess.cs
> Force color profile

- lib/PuppeteerSharp.Tests/FrameTests/WaitForFunctionTests.cs
> Add test for waitForFunction with cross-process navigation

- lib/PuppeteerSharp.Tests/PuppeteerTests/HeadfulTests.cs
> Make sure headful browser closes with beforeuload page

- lib/PuppeteerSharp.Tests/PageTests/WaitForTests.cs
- lib/PuppeteerSharp/WaitTask.cs
> Page.WaitForFunctionAsync should work with multiline strings

- lib/PuppeteerSharp/Mobile/DeviceDescriptors.cs
> Update device descriptors

- lib/PuppeteerSharp.Tests/PageTests/SetRequestInterceptionTests.cs
- lib/PuppeteerSharp/ChromiumProcess.cs
- lib/PuppeteerSharp/NetworkManager.cs
- lib/PuppeteerSharp/Request.cs
> Enable Network Service by default

- lib/PuppeteerSharp.Tests/ConnectionTests/ConnectionTests.cs
- lib/PuppeteerSharp/ConnectOptions.cs
- lib/PuppeteerSharp/Launcher.cs
- lib/PuppeteerSharp/Messaging/WSEndpointResponse.cs
> Add browserUrl option to Puppeteer.ConnectAsync

- lib/PuppeteerSharp.Tests/PageTests/Events/ConsoleTests.cs
- lib/PuppeteerSharp.Tests/WorkerTests/WorkerTests.cs
- lib/PuppeteerSharp/ConsoleMessage.cs
- lib/PuppeteerSharp/ConsoleMessageLocation.cs
- lib/PuppeteerSharp/Messaging/LogEntryAddedResponse.cs
- lib/PuppeteerSharp/Messaging/PageConsoleResponse.cs
- lib/PuppeteerSharp/Messaging/StackTrace.cs
- lib/PuppeteerSharp/Page.cs
- lib/PuppeteerSharp/Worker.cs
> Introduce ConsoleMessage.Location

- lib/PuppeteerSharp/Page.cs
Adds a good experience for 1st time users of the library.
> Provide default quality for jpeg screenshots

- lib/PuppeteerSharp.Tests/PageTests/SelectTests.cs
- lib/PuppeteerSharp/ContextPayload.cs
- lib/PuppeteerSharp/ContextPayloadAuxData.cs
- lib/PuppeteerSharp/DOMWorld.cs
- lib/PuppeteerSharp/DOMWorldType.cs
- lib/PuppeteerSharp/ExecutionContext.cs
- lib/PuppeteerSharp/Frame.cs
- lib/PuppeteerSharp/FrameManager.cs
- lib/PuppeteerSharp/Messaging/PageAddScriptToEvaluateOnNewDocumentRequest.cs
- lib/PuppeteerSharp/Messaging/PageCreateIsolatedWorldRequest.cs
- lib/PuppeteerSharp/Page.cs
- lib/PuppeteerSharp/WaitTask.cs
> Use secondary DOMWorld to drive page.Select

- lib/PuppeteerSharp.Tests/InputTests/InputTests.cs
- lib/PuppeteerSharp/DOMWorld.cs
- lib/PuppeteerSharp/Frame.cs
- lib/PuppeteerSharp/Page.cs
I also wired the Page with the Frame and the DOMWorld in some missing methods
closes #881
> Use secondary world to drive clicks

- lib/PuppeteerSharp/DOMWorld.cs
- lib/PuppeteerSharp/WaitForSelectorOptions.cs
> Sync WaitForSelectorOrXPathAsync code

- lib/PuppeteerSharp.Tests/FrameTests/WaitForSelectorTests.cs
- lib/PuppeteerSharp/DOMWorld.cs
- lib/PuppeteerSharp/Frame.cs
- lib/PuppeteerSharp/Page.cs
> Teach waitForSelector to return null

- docfx_project/examples/index.md
> Fix code in examples page

- lib/PuppeteerSharp.TestServer/wwwroot/longText.html
- lib/PuppeteerSharp.Tests/InputTests/InputTests.cs
- lib/PuppeteerSharp/Input/Mouse.cs
- lib/PuppeteerSharp/Messaging/InputDispatchMouseEventRequest.cs
- lib/PuppeteerSharp/Messaging/MouseEventType.cs
> #934: Implemented support for mouseWheel (Mouse.WheelAsync)

- lib/PuppeteerSharp/BrowserFetcher.cs
> Bump Chromium to 624492

- lib/PuppeteerSharp/Page.cs
- lib/PuppeteerSharp/Target.cs
Modifications to Page and Target classes to prevent unhandled exceptions. Includes clean up of a couple of fields/properties in the Target class.
> Prevent unhandled task exceptions

- lib/PuppeteerSharp.Tests/FrameTests/WaitForFunctionTests.cs
- lib/PuppeteerSharp.Tests/FrameTests/WaitForSelectorTests.cs
- lib/PuppeteerSharp.Tests/PageTests/SetCacheEnabledTests.cs
> SetCacheEnable and WaitFor test updates

- lib/PuppeteerSharp.Tests/InputTests/InputTests.cs
- lib/PuppeteerSharp.Tests/TargetTests/TargetTests.cs
> Input and target tests updates

- lib/PuppeteerSharp/BrowserFetcher.cs
- lib/PuppeteerSharp/ChromiumProcess.cs
> Bump chromium to r637110

- lib/PuppeteerSharp.Tests/PageTests/EmulateTests.cs
- lib/PuppeteerSharp.Tests/PageTests/SetUserAgentTests.cs
> Emulate and SetUserAgent test updates

- lib/PuppeteerSharp.Tests/PuppeteerTests/PuppeteerLaunchTests.cs
> Disable flaky cookies test

- lib/PuppeteerSharp.Tests/InputTests/InputTests.cs
> Add failing for test for mobile + cross process navigation

- lib/PuppeteerSharp.Tests/NetworkTests/NetworkEventTests.cs
- lib/PuppeteerSharp.Tests/NetworkTests/RequestPostDataTests.cs
> RequestPostDataTests tests

- lib/PuppeteerSharp.Tests/NetworkTests/RequestHeadersTests.cs
- lib/PuppeteerSharp.Tests/NetworkTests/ResponseHeadersTests.cs
- lib/PuppeteerSharp/Messaging/ResponsePayload.cs
- lib/PuppeteerSharp/Response.cs
> Add headers tests

- lib/PuppeteerSharp/ConsoleMessageLocation.cs
> Update ConsoleMessage.Location comments

- lib/PuppeteerSharp.Tests/FrameTests/WaitForNavigationTests.cs
> WaitForNavigationTests updates

- lib/PuppeteerSharp.TestServer/wwwroot/beforeunload.html
- lib/PuppeteerSharp.Tests/PageTests/CloseTests.cs
> Beforeunload tests updates

- lib/PuppeteerSharp.Tests/PuppeteerTests/PuppeteerConnectTests.cs
> New connect test

- lib/PuppeteerSharp.Tests/PageTests/CloseTests.cs
> CloseTests updates

- lib/PuppeteerSharp.Tests/PageTests/SetRequestInterceptionTests.cs
> SetRequestInterceptionTests changes

- lib/PuppeteerSharp.Tests/PageTests/WaitForTests.cs
> WaitForTests changes

- lib/PuppeteerSharp.Tests/InputTests/InputTests.cs
> ElementHandlePress tests updates

- lib/PuppeteerSharp/Page.cs
> ExposeFunction improvements

- lib/PuppeteerSharp.Tests/ChromiumSpecificLauncherTests/BrowserUrlOptionTests.cs
- lib/PuppeteerSharp.Tests/ConnectionTests/ConnectionTests.cs
- lib/PuppeteerSharp.Tests/PuppeteerTests/BrowserDisconnectTests.cs
- lib/PuppeteerSharp.Tests/PuppeteerTests/PuppeteerLaunchTests.cs
- lib/PuppeteerSharp/Launcher.cs
> Launcher refactor

- lib/PuppeteerSharp.Tests/InputTests/InputTests.cs
- lib/PuppeteerSharp.Tests/InputTests/TouchScreenTests.cs
> Touchscreen tests improvements

- lib/PuppeteerSharp.Tests/PageTests/SetRequestInterceptionTests.cs
- lib/PuppeteerSharp.Tests/RequestTests/RespondTests.cs
> Add failing test for bad request interception

- lib/PuppeteerSharp.Tests/PageTests/BrowserContextOverridePermissionsTests.cs
> Override Permissions tests changes

- lib/PuppeteerSharp.Tests/ChromiumSpecificTests/BrowserUrlOptionTests.cs
- lib/PuppeteerSharp.Tests/ChromiumSpecificTests/PageTests.cs
- lib/PuppeteerSharp.Tests/PageTests/SetRequestInterceptionTests.cs
> Move some chromium specific tests

- lib/PuppeteerSharp.Tests/AccessibilityTests/AccessibilityTests.cs
closes #979 
added roledescription, orientation, autocomplete, multiselectable & keyshortcuts tests
> added page.accessibility.snapshot tests

- lib/PuppeteerSharp.TestServer/wwwroot/frames/nested-frames.html
- lib/PuppeteerSharp.TestServer/wwwroot/frames/two-frames.html
- lib/PuppeteerSharp.TestServer/wwwroot/title.html
- lib/PuppeteerSharp.TestServer/wwwroot/wrappedlink.html
- lib/PuppeteerSharp.Tests/FrameTests/FrameManagementTests.cs
- lib/PuppeteerSharp.Tests/FrameUtils.cs
- lib/PuppeteerSharp.Tests/InputTests/InputTests.cs
- lib/PuppeteerSharp.Tests/PageTests/EvaluateTests.cs
- lib/PuppeteerSharp.Tests/PageTests/TitleTests.cs
- lib/PuppeteerSharp.Tests/PuppeteerTests/PuppeteerConnectTests.cs
- lib/PuppeteerSharp.Tests/TestConstants.cs
- lib/PuppeteerSharp/FrameTree.cs
> Test refactors

- README.md
Fix #1024 
Let me know if you want to add any comment or clarification in README or docs.
> Update README.md to fix WaitForFunctionAsync usage

- lib/PuppeteerSharp.Tests/PageTests/Cookies/CookiesTests.cs
- lib/PuppeteerSharp.Tests/PageTests/Cookies/DeleteCookiesTests.cs
- lib/PuppeteerSharp.Tests/PageTests/Cookies/SetCookiesTests.cs
- lib/PuppeteerSharp.Tests/PageTests/CookiesTests.cs
> Cookies tests improvements

- lib/PuppeteerSharp.Tests/ConnectionTests/ConnectionTests.cs
- lib/PuppeteerSharp.Tests/InputTests/KeyboardTests.cs
- lib/PuppeteerSharp.Tests/TargetTests/CreateCDPSessionTests.cs
> Minor test changes

- lib/PuppeteerSharp.Tests/PageTests/PdfTests.cs
- lib/PuppeteerSharp/Media/MarginOptions.cs
- lib/PuppeteerSharp/Media/PaperFormat.cs
- lib/PuppeteerSharp/PdfOptions.cs
> PdfOptions should be serializable

- lib/PuppeteerSharp/Page.cs
> Fix EvaluateOnNewDocumentAsync doc

- lib/PuppeteerSharp/BrowserFetcher.cs
> Roll chromium to r641577

- lib/PuppeteerSharp.Tests/FrameTests/FrameManagementTests.cs
> Make sure frames are reported from-inside shadow DOM

- lib/PuppeteerSharp.Tests/PuppeteerTests/ExecutablePathTests.cs
> Check if the executable path is an exact match

- lib/PuppeteerSharp.Tests/InputTests/ClickTests.cs
> Add a failing test that tries to click a fixed button in an iframe

- lib/PuppeteerSharp.Tests/PageTests/SetBypassCSPTests.cs
- lib/PuppeteerSharp/DOMWorld.cs
- lib/PuppeteerSharp/Frame.cs
- lib/PuppeteerSharp/Page.cs
> Ensure Page.setBypassCSP works with iFrames

- lib/PuppeteerSharp.Tests/NetworkTests/RequestContinueTests.cs
- lib/PuppeteerSharp/Request.cs
> Sync Request.Continue tests

- lib/PuppeteerSharp.TestServer/wwwroot/global-var.html
- lib/PuppeteerSharp.Tests/PageTests/EvaluateTests.cs
- lib/PuppeteerSharp/ExecutionContext.cs
- lib/PuppeteerSharp/Helpers/RemoteObjectHelper.cs
> BigInteger support and EvaluateTests sync-up

- lib/PuppeteerSharp.Tests/PageTests/WaitForRequestTests.cs
- lib/PuppeteerSharp/Page.cs
> Improve WhatForRequest event detach

- lib/PuppeteerSharp/CDPSession.cs
- lib/PuppeteerSharp/Connection.cs
- lib/PuppeteerSharp/Helpers/TaskQueue.cs
When we flatten our calls we lost session logs
> Fix session logs

- lib/PuppeteerSharp/BrowserFetcher.cs
> Fix unzip command in MacOS

- lib/PuppeteerSharp.Tests/InputTests/ClickTests.cs
> Add failing test for clicking certain elements

- lib/PuppeteerSharp/BrowserFetcher.cs
> Roll Chromium to r650583

- lib/PuppeteerSharp.Tests/ExecutionContextTests/QueryObjectsTests.cs
> Add a test for queryObjects with navigation

- lib/PuppeteerSharp.Tests/InputTests/ClickTests.cs
- lib/PuppeteerSharp/ElementHandle.cs
> Intersect content quads with viewport

- lib/PuppeteerSharp.Tests/NetworkTests/RequestContinueTests.cs
> test: verify overriding postdata and method on navigation

- lib/PuppeteerSharp.Tests/NetworkTests/SetRequestInterceptionTests.cs
- lib/PuppeteerSharp/Messaging/RequestInterceptedResponse.cs
- lib/PuppeteerSharp/NetworkManager.cs
- lib/PuppeteerSharp/Payload.cs
> Use new requestId for interception request matching

- lib/PuppeteerSharp.Tests/PuppeteerTests/PuppeteerConnectTests.cs
- lib/PuppeteerSharp/DOMWorld.cs
- lib/PuppeteerSharp/FrameManager.cs
> Gracefully handle multiple contexts for secondary DOM World

- lib/PuppeteerSharp.Tests/PageTests/SetCacheEnabledTests.cs
- lib/PuppeteerSharp/FrameManager.cs
- lib/PuppeteerSharp/Messaging/SecuritySetIgnoreCertificateErrorsRequest.cs
- lib/PuppeteerSharp/NetworkManager.cs
- lib/PuppeteerSharp/Page.cs
> Fix cache disabling should stick when toggling request interception

- lib/PuppeteerSharp.Tests/ExecutionContextTests/QueryObjectsTests.cs
- lib/PuppeteerSharp.Tests/FrameTests/WaitForNavigationTests.cs
- lib/PuppeteerSharp.Tests/PageTests/EvaluateTests.cs
- lib/PuppeteerSharp/BrowserFetcher.cs
- lib/PuppeteerSharp/CookieParam.cs
- lib/PuppeteerSharp/SameSite.cs
> Roll Chromium to r656675 

- lib/PuppeteerSharp/PageAccessibility/Accessibility.cs
> Update Accessibility comments

- lib/PuppeteerSharp.Tests/NetworkTests/SetRequestInterceptionTests.cs
> Add failing test for request interception with sync XHRs

- lib/PuppeteerSharp.Tests/PageTests/SetContentTests.cs
- lib/PuppeteerSharp/DOMWorld.cs
> Teach Page.SetContentAsync to work with tricky content

- lib/PuppeteerSharp.Tests/TracingTests/TracingTests.cs
- lib/PuppeteerSharp/Tracing.cs
> Tracing.StartAsync without options

- lib/PuppeteerSharp.Tests/PageTests/ExposeFunctionTests.cs
> Make sure exposeFunction works with complex args

- lib/PuppeteerSharp.Tests/BrowserTests/IsConnectedTests.cs
- lib/PuppeteerSharp/Browser.cs
> Add Browser.IsConnected

- lib/PuppeteerSharp.Tests/AccessibilityTests/RootOptionTests.cs
- lib/PuppeteerSharp/Messaging/AccessibilityGetFullAXTreeResponse.cs
- lib/PuppeteerSharp/PageAccessibility/AXNode.cs
- lib/PuppeteerSharp/PageAccessibility/Accessibility.cs
- lib/PuppeteerSharp/PageAccessibility/AccessibilitySnapshotOptions.cs
> `root` option in Page.Accessibility.SnapshotAsync()

- lib/PuppeteerSharp.Tests/TargetTests/TargetTests.cs
- lib/PuppeteerSharp/Browser.cs
- lib/PuppeteerSharp/Target.cs
- lib/PuppeteerSharp/TargetType.cs
- lib/PuppeteerSharp/Worker.cs
> Create workers from service workers and shared workers

- lib/PuppeteerSharp.Tests/NetworkTests/RequestRespondTests.cs
- lib/PuppeteerSharp/ResponseData.cs
> Stringify response headers for intercepted requests

- lib/PuppeteerSharp.Tests/InputTests/ClickTests.cs
> Add SVG clicking test

- lib/PuppeteerSharp.Tests/PageTests/EvaluateTests.cs
- lib/PuppeteerSharp.Tests/PageTests/SetContentTests.cs
- lib/PuppeteerSharp/BrowserFetcher.cs
- lib/PuppeteerSharp/DOMWorld.cs
closes #1140 
closes #1137
closes #1138
> Roll Chromium to r662092

- lib/PuppeteerSharp/NetworkManager.cs
- lib/PuppeteerSharp/PuppeteerSharp.csproj
closes #1147 
closes #1146
closes #1145
> NetworkId can be null

- lib/PuppeteerSharp.Tests/InputTests/KeyboardTests.cs
- lib/PuppeteerSharp.Tests/Issues/Issue0716.cs
- lib/PuppeteerSharp/Connection.cs
> Fix SlowMo

- samples/PupppeterSharpAspNetFrameworkSample/PupppeterSharpAspNetFrameworkSample/Services/BrowserClient.cs
> Update the ASP.NET Full Framework example

- lib/PuppeteerSharp/CDPSession.cs
- lib/PuppeteerSharp/ChromiumProcess.cs
- lib/PuppeteerSharp/WaitTask.cs
> Add missing TrySetExceptions

- lib/PuppeteerSharp/Media/PaperFormat.cs
> Fix A2 and A3 format size

- lib/PuppeteerSharp.Tests/NetworkTests/RequestRespondTests.cs
- lib/PuppeteerSharp/Messaging/FetchFulfillRequest.cs
- lib/PuppeteerSharp/Request.cs
> Use .NET HttpCode phrases

- lib/PuppeteerSharp/Page.cs
> Add EmulateAsync and SetViewPortAsync notes

- lib/PuppeteerSharp.Tests/InputTests/ClickTests.cs
- lib/PuppeteerSharp/Input/Mouse.cs
> Mouse.ClickAsync improvements

- lib/PuppeteerSharp.TestServer/wwwroot/dynamic-oopif.html
- lib/PuppeteerSharp.Tests/JSCoverageTests/JSCoverageTests.cs
- lib/PuppeteerSharp.Tests/OOPIFTests/OOPIFTests.cs
- lib/PuppeteerSharp/BrowserFetcher.cs
- lib/PuppeteerSharp/Target.cs
- lib/PuppeteerSharp/TargetType.cs
> OOPIF support

- lib/PuppeteerSharp.Tests/NetworkTests/SetRequestInterceptionTests.cs
> Add test to verify fetching of dataURL requests

- lib/PuppeteerSharp/ChromiumProcess.cs
> Remove "--disable-gpu" flag in Windows

- lib/PuppeteerSharp/BrowserFetcher.cs
> Roll Chromium to r669486

- lib/PuppeteerSharp.Tests/PageTests/CloseTests.cs
- lib/PuppeteerSharp.Tests/PageTests/EvaluateTests.cs
- lib/PuppeteerSharp.Tests/PageTests/SelectTests.cs
- lib/PuppeteerSharp/EvaluationFailedException.cs
- lib/PuppeteerSharp/ExecutionContext.cs
- lib/PuppeteerSharp/Helpers/RemoteObjectHelper.cs
> Do evaluations with one roundtrip

- lib/PuppeteerSharp/BrowserFetcher.cs
> Expose IWebProxy in BrowserFetcher

- lib/PuppeteerSharp.Tests/PageTests/CloseTests.cs
- lib/PuppeteerSharp.Tests/PageTests/EvaluateTests.cs
- lib/PuppeteerSharp.Tests/PuppeteerTests/BrowserDisconnectTests.cs
- lib/PuppeteerSharp.Tests/PuppeteerTests/PuppeteerLaunchTests.cs
- lib/PuppeteerSharp/ExecutionContext.cs
> Be able to throw protocol like errors

- lib/PuppeteerSharp/Helpers/ProtocolStreamReader.cs
- lib/PuppeteerSharp/Messaging/IOReadResponse.cs
- lib/PuppeteerSharp/Messaging/PagePrintToPDFRequest.cs
- lib/PuppeteerSharp/Messaging/PagePrintToPDFResponse.cs
- lib/PuppeteerSharp/Page.cs
- lib/PuppeteerSharp/Tracing.cs
> Move Path.PdfAsync to protocol streams

- lib/PuppeteerSharp.Tests/PageTests/EvaluateTests.cs
> Add max payload test

- docfx_project/examples/LodCDP.md
- docfx_project/examples/toc.yml
> Add Log CDP example

- lib/PuppeteerSharp/CDPSession.cs
- lib/PuppeteerSharp/Page.cs
This will be the user the ability to listen and send messages to Chromium manually.
closes #1219
> Expose Page.Session

- lib/PuppeteerSharp/BrowserFetcher.cs
- lib/PuppeteerSharp/Launcher.cs
> Roll Chromium to r674921

- lib/PuppeteerSharp/ElementHandle.cs
> Slightly enhanced wording

- lib/PuppeteerSharp/Input/KeyDefinitions.cs
> Phone buttons support

- lib/PuppeteerSharp.Tests/PuppeteerTests/HeadfulTests.cs
- lib/PuppeteerSharp/Page.cs
> New Feature Page.BringToFrontAsync

- lib/PuppeteerSharp.TestServer/PuppeteerSharp.TestServer.csproj
- lib/PuppeteerSharp.Tests/PuppeteerSharp.Tests.csproj
- lib/PuppeteerSharp.Tests/PuppeteerTests/IgnoreHttpsErrorsTests.cs
- lib/PuppeteerSharp.Tests/PuppeteerTests/PuppeteerConnectTests.cs
- lib/PuppeteerSharp.Tests/TestUtils.cs
> Get TLS version from request

- lib/PuppeteerSharp/FrameManager.cs
> Properly create isolated worlds

- lib/PuppeteerSharp.Tests/Assets/file-to-upload.txt
- lib/PuppeteerSharp.Tests/ChromiumSpecificTests/PageWaitForFileChooserTests.cs
- lib/PuppeteerSharp.Tests/InputTests/FileChooserAcceptTests.cs
- lib/PuppeteerSharp.Tests/InputTests/FileChooserCancelTests.cs
- lib/PuppeteerSharp.Tests/InputTests/FileChooserIsMultipleTests.cs
- lib/PuppeteerSharp.Tests/InputTests/InputTests.cs
- lib/PuppeteerSharp.Tests/InputTests/PageWaitForFileChooserTests.cs
- lib/PuppeteerSharp.Tests/TestConstants.cs
- lib/PuppeteerSharp/FileChooser.cs
- lib/PuppeteerSharp/Messaging/FileChooserAction.cs
- lib/PuppeteerSharp/Messaging/PageFileChooserOpenedResponse.cs
- lib/PuppeteerSharp/Messaging/PageHandleFileChooserRequest.cs
- lib/PuppeteerSharp/Messaging/PageSetInterceptFileChooserDialog.cs
- lib/PuppeteerSharp/Page.cs
- lib/PuppeteerSharp/WaitForFileChooserOptions.cs
> Introduce file chooser interception

- lib/PuppeteerSharp/Target.cs
> Improve target doc

- lib/PuppeteerSharp.Tests/PuppeteerTests/HeadfulTests.cs
> Background page tests should wait for the page

- lib/PuppeteerSharp.Tests/PageTests/EvaluateTests.cs
> Make sure selection is not empty before running copy command

- lib/PuppeteerSharp/Mobile/DeviceDescriptors.cs
> Update DeviceDescriptors to include 6.5 inch iPhone XR

- lib/PuppeteerSharp.Tests/PageTests/EvaluateTests.cs
> Make eval test resilient to error format

- lib/PuppeteerSharp.Tests/NetworkTests/SetRequestInterceptionTests.cs
> Enable redirect inside sync XHR test

- lib/PuppeteerSharp.Tests/InputTests/InputTests.cs
> Enable cross process viewport test

- lib/PuppeteerSharp.Tests/NetworkTests/SetRequestInterceptionTests.cs
> Be able to remove headers using request.continue

- lib/PuppeteerSharp.Tests/PuppeteerTests/HeadfulTests.cs
- lib/PuppeteerSharp/BrowserFetcher.cs
- lib/PuppeteerSharp/ChromiumProcess.cs
> Roll Chromium to r682225

- lib/PuppeteerSharp.Tests/PageTests/AddScriptTagTests.cs
- lib/PuppeteerSharp/BrowserFetcher.cs
- lib/PuppeteerSharp/Target.cs
> Roll Chromium to r686378

- lib/PuppeteerSharp.Tests/PageTests/EvaluateTests.cs
> Add a test for errors inside promise

- lib/PuppeteerSharp/FrameManager.cs
- lib/PuppeteerSharp/NetworkManager.cs
> Pass FrameManager to NetworkManager constructor

- lib/PuppeteerSharp.Tests/PageTests/CloseTests.cs
- lib/PuppeteerSharp.Tests/PuppeteerTests/BrowserCloseTests.cs
- lib/PuppeteerSharp/Page.cs
> Abort page.waitForRequest/Response when page closes

- lib/PuppeteerSharp/DOMWorld.cs
- lib/PuppeteerSharp/ElementHandle.cs
- lib/PuppeteerSharp/Extensions.cs
- lib/PuppeteerSharp/JSHandle.cs
> Add element.SelectAsync and element.EvaluateFunctionAsync

- docfx_project/examples/ChromeExtension.md
- docfx_project/examples/toc.yml
> docs: testing chrome extension

- lib/PuppeteerSharp/DOMWorld.cs
- lib/PuppeteerSharp/WaitForOptions.cs
- lib/PuppeteerSharp/WaitForSelectorOptions.cs
> Fix WaitFor Timeout defaults

- lib/PuppeteerSharp/WaitTask.cs
> Check cancellation on WaitTask.Cleanup

- README.md
- docfx_project/api/index.md
- docfx_project/examples/index.md
> Fix demo code

- lib/PuppeteerSharp/Frame.cs
- lib/PuppeteerSharp/Page.cs
> clarify `TypeAsync` method examples

- lib/PuppeteerSharp/WaitForSelectorOptions.cs
> Improve WaitForSelector docs

- lib/PuppeteerSharp.Tests/PageTests/EmulateTimezoneTests.cs
- lib/PuppeteerSharp/Messaging/EmulateTimezoneRequest.cs
- lib/PuppeteerSharp/Page.cs
- lib/PuppeteerSharp/WaitForSelectorOptions.cs
> Add Page.EmulateTimezoneAsync

- lib/PuppeteerSharp/Input/Keyboard.cs
> Avoid unnecessary zero-delays in input code

- lib/PuppeteerSharp/CookieParam.cs
> Improve CookieParam.Expires documentation

- docfx_project/api/index.md
- docfx_project/index.md
> PdfOptions example

- lib/PuppeteerSharp.Tests/InputTests/InputTests.cs
- lib/PuppeteerSharp/ElementHandle.cs
Added ability to skip resolving file paths for UploadFileAsync. Fixes #1363
> Added ability to skip resolving file paths for UploadFileAsync. Fixes #1363

- lib/PuppeteerSharp/SecurityDetails.cs
There aren't any 'working' SSL tests in the test suite, but I have tested a built version with my app and can confirm this fixes the issue with certs expiring > 2038
> #1372 fix ssl when navigate to site with cert expiring after 2038

- lib/PuppeteerSharp/ChromiumProcess.cs
- lib/PuppeteerSharp/Helpers/TaskHelper.cs
- lib/PuppeteerSharp/LifecycleWatcher.cs
> Add cancellationtoken to timeout tasks

- lib/PuppeteerSharp.ruleset
> Remove duplicated rule

- lib/PuppeteerSharp.Tests/PageTests/CloseTests.cs
- lib/PuppeteerSharp.Tests/PuppeteerTests/PuppeteerLaunchTests.cs
- lib/PuppeteerSharp/Browser.cs
- lib/PuppeteerSharp/Page.cs
- lib/PuppeteerSharp/PuppeteerSharp.csproj
> Add IAsyncDisposable support for Page and Browser

- lib/PuppeteerSharp.ruleset
- lib/PuppeteerSharp/BrowserFetcher.cs
Corrects CA2000 (#1442 ) issue but also fixes IDE0008. This seems to be traced back to 
```
csharp_style_var_for_built_in_types = false:error
```
in `lib/.editorconfig`
This was unexpected but solution compiles now?
_(First public PR - go easy!)_
> Corrects CA2000 and IDE0008

- lib/PuppeteerSharp.ruleset
- lib/PuppeteerSharp/Browser.cs
- lib/PuppeteerSharp/ChromiumProcess.cs
- lib/PuppeteerSharp/Connection.cs
- lib/PuppeteerSharp/Page.cs
- lib/PuppeteerSharp/Transport/WebSocketTransport.cs
> fix CA1063

- docfx_project/examples/Page.WaitForFunctionAsync.md
- docfx_project/examples/toc.yml
> Add WaitForFunctionAsync doc

- appveyor-demo.yml
- demos/PuppeteerSharpPdfDemo/PuppeteerSharpPdfDemo-Local.csproj
- demos/PuppeteerSharpPdfDemo/PuppeteerSharpPdfDemo.csproj
> Update demo versions

- lib/PuppeteerSharp.Tests/BrowserTests/UserAgentTests.cs
- lib/PuppeteerSharp.Tests/BrowserTests/VersionTests.cs
- lib/PuppeteerSharp.Tests/ElementHandleTests/BoundingBoxTests.cs
- lib/PuppeteerSharp.Tests/JSHandleTests/JsonValueTests.cs
- lib/PuppeteerSharp.Tests/NetworkTests/NetworkEventTests.cs
- lib/PuppeteerSharp.Tests/NetworkTests/RequestHeadersTests.cs
- lib/PuppeteerSharp.Tests/NetworkTests/SetRequestInterceptionTests.cs
- lib/PuppeteerSharp.Tests/PageTests/CloseTests.cs
- lib/PuppeteerSharp.Tests/PageTests/Events/ConsoleTests.cs
- lib/PuppeteerSharp.Tests/PageTests/GotoTests.cs
- lib/PuppeteerSharp.Tests/PuppeteerTests/PuppeteerLaunchTests.cs
- lib/PuppeteerSharp.Tests/TestConstants.cs
> Tests: Implement the Chrome bit

- lib/.editorconfig
- lib/PuppeteerSharp/JSHandle.cs
- lib/PuppeteerSharp/SelectorException.cs
Added constructor in SelectorExpection and fixed CA2229
Added CurrentCulture in JSHandle in .toLower function and fixed CA1304
> Fix CA2229, CA1304

- lib/PuppeteerSharp/ElementHandle.cs
since the type conflict with properties in the class they need to be fully qualified
> fix doc links

- lib/PuppeteerSharp.ruleset
Set rule CA2229 to Error.
Fixes https://github.com/hardkoded/puppeteer-sharp/issues/1428
> Set rule to Error

- lib/PuppeteerSharp.ruleset
- lib/PuppeteerSharp/Helpers/TaskHelper.cs
[#1399 ](https://github.com/hardkoded/puppeteer-sharp/issues/1399)
> Enabled and fixed SA1005

- lib/PuppeteerSharp.ruleset
- lib/PuppeteerSharp/ChromiumLauncher.cs
> Add SA1505 rule and fix errors

- lib/PuppeteerSharp.ruleset
- lib/PuppeteerSharp/LifecycleWatcher.cs
- lib/PuppeteerSharp/Transport/WebSocketTransport.cs
Set CA2213 rule to Error and adjusted code to this change.
Fixes #1441
> Set CA2213 rule to Error

- lib/PuppeteerSharp.ruleset
- lib/PuppeteerSharp/FrameManager.cs
- lib/PuppeteerSharp/NetworkManager.cs
- lib/PuppeteerSharp/PageAccessibility/SerializedAXNode.cs
[#1396 ](https://github.com/hardkoded/puppeteer-sharp/issues/1396)
> Enabled and fixed errors for SA1009

- lib/PuppeteerSharp.ruleset
- lib/PuppeteerSharp/Page.cs
> Enable SA1620 rule

- lib/PuppeteerSharp.ruleset
- lib/PuppeteerSharp/DOMWorld.cs
> Enable SA1118 rule

- lib/PuppeteerSharp.ruleset
- lib/PuppeteerSharp/ElementHandle.cs
Set SA1612 rule to Error and adjusted code to this change.
Fixes #1419
> Set SA1612 rule to Error

- lib/PuppeteerSharp.ruleset
- lib/PuppeteerSharp/Page.cs
this fixes issue #1439 
I did not add a unit test because inspecting the stack of a caught exception would end up being messy and flaky.
> Set ca2200 to error

- lib/PuppeteerSharp.ruleset
- lib/PuppeteerSharp/ChromiumProcessException.cs
- lib/PuppeteerSharp/MessageException.cs
- lib/PuppeteerSharp/ProcessException.cs
- lib/PuppeteerSharp/SelectorException.cs
- lib/PuppeteerSharp/TargetClosedException.cs
> enable CA1032 rule and implement standard exception constructors

- lib/PuppeteerSharp.ruleset
- lib/PuppeteerSharp/NetworkManager.cs
- lib/PuppeteerSharp/Page.cs
- lib/PuppeteerSharp/PageAccessibility/AXNode.cs
> Enable CA1304 rule

- lib/PuppeteerSharp.Tests/PuppeteerTests/PuppeteerConnectTests.cs
i think the intent of the test was to test against the two diff instances?
> fix bug in ConnectToTheSamePageSimultaneously

- appveyor-edge.yml
- appveyor-fullframework.yml
- lib/PuppeteerSharp.DevicesFetcher/Program.cs
- lib/PuppeteerSharp.Tests/BrowserContextTests/BrowserContextTests.cs
- lib/PuppeteerSharp.Tests/InputTests/FileChooserAcceptTests.cs
- lib/PuppeteerSharp.Tests/InputTests/PageWaitForFileChooserTests.cs
- lib/PuppeteerSharp.Tests/PageTests/ExposeFunctionTests.cs
- lib/PuppeteerSharp.Tests/PageTests/WaitForRequestTests.cs
- lib/PuppeteerSharp.Tests/PuppeteerTests/HeadfulTests.cs
- lib/PuppeteerSharp.Tests/PuppeteerTests/PuppeteerLaunchTests.cs
- lib/PuppeteerSharp.Tests/TracingTests/TracingTests.cs
- lib/PuppeteerSharp/FrameManager.cs
very minor, but figured i would submit it anyway
> remove some redundant variables

- lib/PuppeteerSharp/BrowserFetcher.cs
Fixes the `Bad NaCl helper startup ack (0 bytes)` error
> chmod +x nacl_helper

- lib/PuppeteerSharp.Tests/PageTests/EmulateNetworkConditions.cs
- lib/PuppeteerSharp/InternalNetworkConditions.cs
- lib/PuppeteerSharp/Messaging/NetworkEmulateNetworkConditionsRequest.cs
- lib/PuppeteerSharp/NetworkConditions.cs
- lib/PuppeteerSharp/NetworkManager.cs
- lib/PuppeteerSharp/Page.cs
- lib/PuppeteerSharp/PredefinedNetworkConditions.cs
- lib/PuppeteerSharp/Puppeteer.cs
See https://github.com/hardkoded/puppeteer-sharp/pull/1645#issuecomment-799692242
> feat: add page.emulateNetworkConditions

- lib/PuppeteerSharp/BoundingBox.cs
> Fix BoundingBox equality

- lib/PuppeteerSharp/Browser.cs
- lib/PuppeteerSharp/BrowserContext.cs
- lib/PuppeteerSharp/MessageException.cs
- lib/PuppeteerSharp/Page.cs
- lib/PuppeteerSharp/Target.cs
since there are properties matching those type  names, the types need to be fully qualified
> Broken xml doc links

- lib/PuppeteerSharp/ChromiumLauncher.cs
See https://github.com/puppeteer/puppeteer/pull/6692
> Rename TranslateUI to Translate to match Chrome

- lib/PuppeteerSharp/BrowserFetcher.cs
- lib/PuppeteerSharp/CDPSession.cs
- lib/PuppeteerSharp/Connection.cs
- lib/PuppeteerSharp/DOMWorld.cs
- lib/PuppeteerSharp/Page.cs
closes #1485
https://devblogs.microsoft.com/premier-developer/the-danger-of-taskcompletionsourcet-class/
> Add missing `TaskCreationOptions.RunContinuationsAsynchronously`

- lib/PuppeteerSharp/WaitTask.cs
http://joeduffyblog.com/2010/06/27/on-partiallyconstructed-objects/
> Avoid leaking reference to partially constructed WaitTask instance

- lib/PuppeteerSharp/Helpers/ConcurrentSet.cs
- lib/PuppeteerSharp/NetworkManager.cs
I have prepared a test project to demonstrate the errors that can occur with the current version: [Test.zip](https://github.com/hardkoded/puppeteer-sharp/files/6256308/Test.zip)
- `Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: index`
- `ContainsKey` returns wrong value
See #1680 for context
> Fix NetworkManager._attemptedAuthentications concurrency issues

- lib/PuppeteerSharp/Frame.cs
I have prepared a test project to demonstrate the errors that can occur with the current version:  [Test.zip](https://github.com/hardkoded/puppeteer-sharp/files/6289342/Test.zip)
- `Contains` returns wrong value
See #1680
> Fix Frame.ChildFrames concurrency issues

- lib/PuppeteerSharp.Tests/FixturesTests/FixturesTests.cs
- lib/PuppeteerSharp/BrowserFetcher.cs
- lib/PuppeteerSharp/Launcher.cs
- lib/PuppeteerSharp/PuppeteerSharp.csproj
> Check firefox version automatically

- .gitignore
- lib/PuppeteerSharp/Mobile/DeviceDescriptorName.cs
- lib/PuppeteerSharp/Mobile/DeviceDescriptors.cs
- Fix iPhone X user agents
- Add iPhone devices from XR version to 11 Pro Max
Data about these devices have been extracted from Puppeteer JavaScript project.
> Add iphone family devices

- lib/PuppeteerSharp.Tests/OOPIFTests/OOPIFTests.cs
> Mark OOPIF test

- lib/PuppeteerSharp.Tests/WontImplementTests.cs
> Add ignored pipe tests

- lib/PuppeteerSharp.Tests/NavigationTests/PageReloadTests.cs
- lib/PuppeteerSharp.Tests/WontImplementTests.cs
> Update navigation tests

- lib/PuppeteerSharp.Tests/WontImplementTests.cs
> Ignore missing tracing tests

- lib/PuppeteerSharp/NetworkManager.cs
Fixes the issues seen in #1798 @kblok
> Fix NetworkManager.OnRequestAsync

- lib/PuppeteerSharp.TestServer/wwwroot/cached/one-style-font.css
- lib/PuppeteerSharp.TestServer/wwwroot/cached/one-style-font.html
- lib/PuppeteerSharp.Tests/RequestInterceptionTests/SetRequestInterceptionTests.cs
- lib/PuppeteerSharp/NetworkManager.cs
- lib/PuppeteerSharp/Page.cs
> Add missing set request interception tests

- lib/PuppeteerSharp/Page.cs
- lib/PuppeteerSharp/PdfOptions.cs
> Introduce OmitBackground option on PrintToPdf

- lib/PuppeteerSharp.Tests/WontImplementTests.cs
> Mark pipe test as won't implement

- lib/PuppeteerSharp/ConsoleType.cs
> Add console type timeStamp

- lib/PuppeteerSharp.Tests/JSHandleTests/JsonValueTests.cs
- lib/PuppeteerSharp.Tests/JSHandleTests/PageEvaluateHandle.cs
- lib/PuppeteerSharp.Tests/JSHandleTests/ToStringTests.cs
- lib/PuppeteerSharp/Helpers/RemoteObjectHelper.cs
- lib/PuppeteerSharp/JSHandle.cs
> Add missing JSHandle tests

- lib/PuppeteerSharp.Tests/KeyboardTests/KeyboardTests.cs
> Fix keyboard test name

- lib/PuppeteerSharp.ruleset
- lib/PuppeteerSharp/BrowserFetcher.cs
- lib/PuppeteerSharp/ChromiumLauncher.cs
- lib/PuppeteerSharp/ElementHandle.cs
- lib/PuppeteerSharp/ExecutionContext.cs
- lib/PuppeteerSharp/Extensions.cs
- lib/PuppeteerSharp/Frame.cs
- lib/PuppeteerSharp/Helpers/TaskHelper.cs
- lib/PuppeteerSharp/Input/Key.cs
- lib/PuppeteerSharp/Launcher.cs
- lib/PuppeteerSharp/LauncherBase.cs
- lib/PuppeteerSharp/Page.cs
- lib/PuppeteerSharp/PageAccessibility/SerializedAXNode.cs
- lib/PuppeteerSharp/PageCoverage/CoverageEntryRange.cs
RE: Issue #1435 
Set CA1031 to Error and resolved compiler errors.
Added suppression attributes where throwing an exception was not an option.
> Set CA1031 to Error and resolved compiler errors

- lib/PuppeteerSharp.ruleset
- lib/PuppeteerSharp/Helpers/AsyncMessageQueue.cs
- lib/PuppeteerSharp/Page.cs
- lib/PuppeteerSharp/Target.cs
- lib/PuppeteerSharp/Transport/WebSocketTransport.cs
- lib/PuppeteerSharp/WaitTask.cs
- lib/PuppeteerSharp/Worker.cs
closes #1431 
Set CA2008 to "Error" and resolved compiler errors.
When prompted for a TaskScheduler, set the value to the Default TaskScheduler.
> Set CA2008 to "Error" and resolved compiler errors

- lib/PuppeteerSharp.ruleset
- lib/PuppeteerSharp/ChromiumProcessException.cs
- lib/PuppeteerSharp/MessageException.cs
- lib/PuppeteerSharp/ProcessException.cs
- lib/PuppeteerSharp/TargetClosedException.cs
RE: #1429
Marked ISerializable types with SerializableAttribute and added serialization constructor delegating to args the base constructor.
> Set CA2237 to "Error" and resolved compiler errors.

- lib/PuppeteerSharp.ruleset
closes #1426 
Set CA2220 to "Error". No errors resulted.
> Set CA2220 to "Error". No error to be seen.

- lib/PuppeteerSharp.Tests/WontImplementTests.cs
> Add EventEmiter tests to the Won't implement list

- README.md
- lib/PuppeteerSharp.TestServer/wwwroot/input/drag-and-drop.html
- lib/PuppeteerSharp.Tests/DragAndDropTests/InputDragTests.cs
- lib/PuppeteerSharp/DragData.cs
- lib/PuppeteerSharp/DragDataItem.cs
- lib/PuppeteerSharp/DragOperation.cs
- lib/PuppeteerSharp/ElementHandle.cs
- lib/PuppeteerSharp/Input/Mouse.cs
- lib/PuppeteerSharp/Messaging/DragEventType.cs
- lib/PuppeteerSharp/Messaging/InputDispatchDragEventRequest.cs
- lib/PuppeteerSharp/Messaging/InputSetInterceptDragsRequest.cs
- lib/PuppeteerSharp/Page.cs
> Introduce drag and drop support

- lib/PuppeteerSharp.ruleset
- lib/PuppeteerSharp/BrowserFetcher.cs
- lib/PuppeteerSharp/ChromiumProcessException.cs
- lib/PuppeteerSharp/Frame.cs
- lib/PuppeteerSharp/Input/Mouse.cs
- lib/PuppeteerSharp/Input/Touchscreen.cs
- lib/PuppeteerSharp/MessageException.cs
- lib/PuppeteerSharp/Page.cs
- lib/PuppeteerSharp/ProcessException.cs
- lib/PuppeteerSharp/TargetClosedException.cs
> Set SA1614 to "Error" and resolved errors.

- lib/PuppeteerSharp.ruleset
- lib/PuppeteerSharp/PuppeteerHandleExtensions.cs
> Set SA1622 to "Error" and resolved compiler errors.

- lib/PuppeteerSharp.ruleset
- lib/PuppeteerSharp/LauncherBase.cs
> Set SA1643 to "Error" and resolved errors.

- lib/PuppeteerSharp.Tests/TouchScreenTests/TouchScreenTests.cs
> Fix touchscreen test name

- lib/PuppeteerSharp.Tests/InputTests/FileChooserAcceptTests.cs
- lib/PuppeteerSharp/ElementHandle.cs
> Add missing FileChooser Accept test

- lib/PuppeteerSharp.ruleset
- lib/PuppeteerSharp/CDPSession.cs
- lib/PuppeteerSharp/ElementHandle.cs
> Set SA1627 to "Error" and resolved errors.

- lib/PuppeteerSharp.Tests/WaitTaskTests/FrameWaitForFunctionTests.cs
- lib/PuppeteerSharp.Tests/WaitTaskTests/FrameWaitForTimeoutTests.cs
- lib/PuppeteerSharp.Tests/WaitTaskTests/PageWaitForTimeoutTests.cs
- lib/PuppeteerSharp.Tests/WontImplementTests.cs
- lib/PuppeteerSharp/WaitTask.cs
> Add missing wait task tests

- lib/PuppeteerSharp.ruleset
- lib/PuppeteerSharp/CDPSession.cs
- lib/PuppeteerSharp/Connection.cs
- lib/PuppeteerSharp/JSHandle.cs
- lib/PuppeteerSharp/MessageEventArgs.cs
- lib/PuppeteerSharp/Request.cs
- lib/PuppeteerSharp/RequestEventArgs.cs
- lib/PuppeteerSharp/ResponseCreatedEventArgs.cs
- lib/PuppeteerSharp/TargetChangedArgs.cs
- lib/PuppeteerSharp/TargetInfo.cs
> Changes to enforce error on SA1624 rule

- lib/PuppeteerSharp.Tests/BrowserTests/BrowserVersionTests.cs
- lib/PuppeteerSharp.Tests/BrowserTests/ProcessTests.cs
> Add missing browser tests

- lib/PuppeteerSharp.Tests/NetworkTests/NetworkEventTests.cs
- lib/PuppeteerSharp.Tests/NetworkTests/ResponseHeadersTests.cs
- lib/PuppeteerSharp.Tests/WontImplementTests.cs
> Add missing network tests

- lib/PuppeteerSharp.Tests/TargetTests/BrowserWaitForTargetTests.cs
> Add missing target tests

- lib/PuppeteerSharp.Tests/ScreenshotTests/ElementHandleScreenshotTests.cs
> Add missing PuppeteerTest in Screenshot tests

- lib/PuppeteerSharp.Tests/PageTests/PageEventsLoadTests.cs
> Add missing load test

- lib/PuppeteerSharp/Frame.cs
- Add CDATA formatting to all blocks
- Replace const with var
- Fix some other mistakes
> Frame - Fix xml doc example code

- lib/PuppeteerSharp.Tests/PageTests/WaitForResponseTests.cs
> Fix WaitForResponse test name

- lib/PuppeteerSharp.Tests/PageTests/ExposeFunctionTests.cs
- lib/PuppeteerSharp.Tests/PageTests/SetUserAgentTests.cs
- lib/PuppeteerSharp.Tests/WontImplementTests.cs
- lib/PuppeteerSharp/Browser.cs
- lib/PuppeteerSharp/Messaging/NetworkSetUserAgentOverrideRequest.cs
- lib/PuppeteerSharp/NetworkManager.cs
- lib/PuppeteerSharp/Page.cs
- lib/PuppeteerSharp/UserAgentBrandVersion.cs
- lib/PuppeteerSharp/UserAgentMetadata.cs
> Introduce user agent metadata in Page.SetUserAgentAsync

- lib/PuppeteerSharp.Tests/PageTests/PdfTests.cs
- lib/PuppeteerSharp.Tests/PageTests/SelectTests.cs
- lib/PuppeteerSharp.Tests/WontImplementTests.cs
> Add missing PDF test

- lib/PuppeteerSharp.Tests/EvaluationTests/FrameEvaluateTests.cs
- lib/PuppeteerSharp.Tests/WontImplementTests.cs
> Add missing evaluation tests

- lib/PuppeteerSharp.Tests/FrameTests/FrameEvaluateTests.cs
- lib/PuppeteerSharp.Tests/FrameTests/FrameManagementTests.cs
> Add missing frame tests

- lib/PuppeteerSharp.Tests/QuerySelectorTests/PageQuerySelectorTests.cs
> Fix a test name on Page.$

- lib/PuppeteerSharp/NetworkEventManager.cs
RAM Leak Fix
https://github.com/hardkoded/puppeteer-sharp/pull/1980
https://github.com/cefsharp/Puppeteer/pull/31
> RAM Leak Fix

- appveyor/GenerateDocs.ps1
- lib/PuppeteerSharp.Tests/QuerySelectorTests/PierceHandlerTests.cs
- lib/PuppeteerSharp/CustomQueriesManager.cs
> Add shadow DOM support

- lib/PuppeteerSharp.Tests/OOPIFTests/OOPIFTests.cs
- lib/PuppeteerSharp.ruleset
- lib/PuppeteerSharp/BoundingBox.cs
- lib/PuppeteerSharp/Browser.cs
- lib/PuppeteerSharp/BrowserFetcherOptions.cs
- lib/PuppeteerSharp/CDPSession.cs
- lib/PuppeteerSharp/ChromiumLauncher.cs
- lib/PuppeteerSharp/ChromiumProcessException.cs
- lib/PuppeteerSharp/Dialog.cs
- lib/PuppeteerSharp/ElementHandle.cs
- lib/PuppeteerSharp/EmulationManager.cs
- lib/PuppeteerSharp/FirefoxLauncher.cs
- lib/PuppeteerSharp/FrameManager.cs
- lib/PuppeteerSharp/Helpers/ConcurrentSet.cs
- lib/PuppeteerSharp/LaunchOptions.cs
- lib/PuppeteerSharp/LauncherBase.cs
- lib/PuppeteerSharp/Media/PaperFormat.cs
- lib/PuppeteerSharp/Messaging/RemoteObject.cs
- lib/PuppeteerSharp/NetworkManager.cs
- lib/PuppeteerSharp/Page.cs
- lib/PuppeteerSharp/PageAccessibility/SerializedAXNode.cs
- lib/PuppeteerSharp/Puppeteer.cs
- lib/PuppeteerSharp/TargetType.cs
- lib/PuppeteerSharp/Transport/WebSocketTransport.cs
- lib/PuppeteerSharp/ViewPortOptions.cs
- lib/PuppeteerSharp/WaitTask.cs
Resolves #1411, #1409, #1405, #1403, #1402, #1401, #1400 and #1393. Everything is in one PR as it's mostly just formatting and style.
* TargetType.iFrame is renamed to TargetType.IFrame
> [BREAKING CHANGE] Enable various analyzer rules

- lib/PuppeteerSharp/BrowserFetcher.cs
> Improve browser download location

- lib/PuppeteerSharp.Tests/Issues/Issue1895.cs
- lib/PuppeteerSharp/Page.cs
> Fix console log arguments deserialization

- lib/PuppeteerSharp.ruleset
- lib/PuppeteerSharp/BrowserFetcher.cs
- lib/PuppeteerSharp/Connection.cs
- lib/PuppeteerSharp/ExecutionContext.cs
- lib/PuppeteerSharp/Media/PaperFormat.cs
- lib/PuppeteerSharp/Page.cs
- lib/PuppeteerSharp/Response.cs
- lib/PuppeteerSharp/Tracing.cs
- lib/PuppeteerSharp/ViewPortOptions.cs
Change the action for SA1204 to Error, and update solution files.
Fixes https://github.com/hardkoded/puppeteer-sharp/issues/1392
> Enable SA1204 rule

- .github/workflows/dotnet.yml
- lib/PuppeteerSharp.Tests/BrowserContextTests/BrowserContextTests.cs
- lib/PuppeteerSharp/BrowserContext.cs
- lib/PuppeteerSharp/IBrowserContext.cs
> Expose browser context Id

- lib/PuppeteerSharp/TargetType.cs
Currently, receiving a `Log.entryAdded` message with `source` set to `rendering` causes a `JsonSerializationException`:
```
Newtonsoft.Json.JsonSerializationException: Error converting value "rendering" to type 'PuppeteerSharp.TargetType'. Path 'entry.source'.
---> System.ArgumentException: Requested value 'rendering' was not found.
at Newtonsoft.Json.Utilities.EnumUtils.ParseEnum(Type enumType, NamingStrategy namingStrategy, String value, Boolean disallowNumber)
at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
--- End of inner exception stack trace ---
at Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) …
```
> Support "rendering" target type.

- lib/PuppeteerSharp.ruleset
- lib/PuppeteerSharp/DOMWorldType.cs
- lib/PuppeteerSharp/Helpers/Linux/FileAccessPermissions.cs
- lib/PuppeteerSharp/Input/PointerType.cs
- lib/PuppeteerSharp/Messaging/DispatchKeyEventType.cs
- lib/PuppeteerSharp/Messaging/DragEventType.cs
- lib/PuppeteerSharp/Messaging/FileChooserAction.cs
- lib/PuppeteerSharp/Messaging/MouseEventType.cs
- lib/PuppeteerSharp/Messaging/PageFrameDetachedResponse.cs
> Enable rule SA1602

- lib/PuppeteerSharp.ruleset
- lib/PuppeteerSharp/Browser.cs
- lib/PuppeteerSharp/BrowserContext.cs
- lib/PuppeteerSharp/BrowserFetcher.cs
- lib/PuppeteerSharp/CDPSession.cs
- lib/PuppeteerSharp/ConsoleMessageLocation.cs
- lib/PuppeteerSharp/ElementHandle.cs
- lib/PuppeteerSharp/Input/Mouse.cs
- lib/PuppeteerSharp/Input/Touchscreen.cs
- lib/PuppeteerSharp/JSHandle.cs
- lib/PuppeteerSharp/Media/MarginOptions.cs
- lib/PuppeteerSharp/Media/PaperFormat.cs
- lib/PuppeteerSharp/Page.cs
- lib/PuppeteerSharp/PageAccessibility/Accessibility.cs
- lib/PuppeteerSharp/PdfOptions.cs
- lib/PuppeteerSharp/Request.cs
- lib/PuppeteerSharp/Response.cs
> Enable rule SA1648

- lib/PuppeteerSharp.TestServer/wwwroot/frames/frame.html
- lib/PuppeteerSharp.Tests/AccessibilityTests/AccessibilityTests.cs
- lib/PuppeteerSharp.Tests/Issues/Issue0343.cs
- lib/PuppeteerSharp.Tests/TargetTests/TargetTests.cs
- lib/PuppeteerSharp/Browser.cs
- lib/PuppeteerSharp/BrowserFetcher.cs
- lib/PuppeteerSharp/CDPSession.cs
- lib/PuppeteerSharp/ChromeTargetManager.cs
- lib/PuppeteerSharp/ChromiumLauncher.cs
- lib/PuppeteerSharp/Connection.cs
- lib/PuppeteerSharp/FirefoxTargetManager.cs
- lib/PuppeteerSharp/FrameManager.cs
- lib/PuppeteerSharp/IBrowser.cs
- lib/PuppeteerSharp/ICDPConnection.cs
- lib/PuppeteerSharp/ICDPSession.cs
- lib/PuppeteerSharp/ITargetManager.cs
- lib/PuppeteerSharp/Launcher.cs
- lib/PuppeteerSharp/Messaging/TargetSetDiscoverTargetsRequest.cs
- lib/PuppeteerSharp/Page.cs
- lib/PuppeteerSharp/SessionEventArgs.cs
- lib/PuppeteerSharp/Target.cs
- lib/PuppeteerSharp/TargetChangedArgs.cs
- lib/PuppeteerSharp/TargetInfo.cs
- lib/PuppeteerSharp/TargetType.cs
> Introduce Target Managers

- lib/PuppeteerSharp.Tests/PageTests/PageEventsConsoleTests.cs
- lib/PuppeteerSharp/Page.cs
- lib/PuppeteerSharp/PuppeteerSharp.csproj
> Fix Page.AddConsoleMessageAsync NullReferenceException

- lib/PuppeteerSharp/BrowserFetcher.cs
- lib/PuppeteerSharp/PuppeteerSharp.csproj
> Improve DownloadFetcher executable path

- lib/PuppeteerSharp/ExecutionContext.cs
- lib/PuppeteerSharp/Frame.cs
- lib/PuppeteerSharp/FrameManager.cs
- lib/PuppeteerSharp/IsolatedWorld.cs
- lib/PuppeteerSharp/WaitTask.cs
> Rename DOMWorld to IsolatedWorld

- lib/PuppeteerSharp/Helpers/TaskQueue.cs
Adds a double dispose guard to `DisposeAsync`. As proposed in https://github.com/hardkoded/puppeteer-sharp/pull/2118#issuecomment-1489622471 
Same pattern is used within the `dotnet runtime` itself. 
https://github.com/dotnet/runtime/blob/38b81ba83ab2b27a730a9524401d74043d172049/src/libraries/System.Net.Quic/src/System/Net/Quic/QuicListener.cs#L356
> TaskQueue - ThreadSafe Dispose(Async) guard

- lib/PuppeteerSharp/Target.cs
Similar to what was changed in #2094
> Return Task wrapping a null worker instead of a null task

- lib/PuppeteerSharp.Tests/TaskQueueTests.cs
- lib/PuppeteerSharp/Helpers/TaskQueue.cs
> TaskQueue tests

- lib/PuppeteerSharp.Tests/UtilitiesTests/TaskHelperTests.cs
- lib/PuppeteerSharp.Tests/UtilitiesTests/TaskQueueTests.cs
As promised, as PR moving `TaskHelperTests` and `TaskQueueTests` into a subfolder `UtilitiesTests`
> Create subfolder UtilitiesTests

- lib/PuppeteerSharp.Tests/InjectedTests/InjectedTests.cs
- lib/PuppeteerSharp.Tests/PuppeteerSharp.Tests.csproj
- lib/PuppeteerSharp/Frame.cs
- lib/PuppeteerSharp/Injected/README.md
- lib/PuppeteerSharp/Injected/injected.js
- lib/PuppeteerSharp/IsolatedWorld.cs
- lib/PuppeteerSharp/PuppeteerSharp.csproj
This is part of a chain of changes upstream that we need to introduce. This is not even close to the final solution, but we need to take it step by step.
[Upstream change](https://github.com/puppeteer/puppeteer/commit/292216652b0e1771564718bf6cc1e1139446316a)
> Add injected framework

- lib/PuppeteerSharp.Tests/PageTests/AddScriptTagTests.cs
- lib/PuppeteerSharp/AddTagOptions.cs
- lib/PuppeteerSharp/AriaQueryHandlerFactory.cs
- lib/PuppeteerSharp/FirefoxTargetManager.cs
- lib/PuppeteerSharp/Frame.cs
- lib/PuppeteerSharp/IsolatedWorld.cs
This will bring [This migration](https://github.com/puppeteer/puppeteer/pull/8878/files).
> Migrate addScriptTag

- lib/PuppeteerSharp.Tests/TestConstants.cs
- lib/PuppeteerSharp.Tests/WaitTaskTests/FrameWaitForFunctionTests.cs
- lib/PuppeteerSharp.Tests/WaitTaskTests/FrameWaitForSelectorTests.cs
- lib/PuppeteerSharp.Tests/WaitTaskTests/FrameWaitForXPathTests.cs
- lib/PuppeteerSharp.Tests/WaitTaskTests/PageWaitForTests.cs
- lib/PuppeteerSharp/AriaQueryHandlerFactory.cs
- lib/PuppeteerSharp/CustomQueriesManager.cs
- lib/PuppeteerSharp/Injected/injected.js
- lib/PuppeteerSharp/IsolatedWorld.cs
- lib/PuppeteerSharp/TaskManager.cs
- lib/PuppeteerSharp/WaitForFunctionOptions.cs
- lib/PuppeteerSharp/WaitTask.cs
- lib/PuppeteerSharp/WaitTaskTimeoutException.cs
This will match the upstream change [here](https://github.com/puppeteer/puppeteer/pull/8943/files#diff-b5735653f04183106c7769b4c707f0a9d7742f9367334fc9f38f79bb9a596786).
> Waittask refactor

- lib/PuppeteerSharp.Tests/PollerInterceptor.cs
- lib/PuppeteerSharp.Tests/WaitTaskTests/FrameWaitForFunctionTests.cs
- lib/PuppeteerSharp.Tests/WaitTaskTests/FrameWaitForXPathTests.cs
> Improve FrameWaitForXPathTests tests

- lib/PuppeteerSharp.Tests/ClickTests/ClickTests.cs
- lib/PuppeteerSharp.Tests/CoverageTests/JSCoverageTests.cs
- lib/PuppeteerSharp.Tests/IgnoreHttpsErrorsTests/ResponseSecurityDetailsTests.cs
- lib/PuppeteerSharp.Tests/PageTests/ExposeFunctionTests.cs
- lib/PuppeteerSharp/Binding.cs
- lib/PuppeteerSharp/BindingUtils.cs
- lib/PuppeteerSharp/CDPSession.cs
- lib/PuppeteerSharp/Connection.cs
- lib/PuppeteerSharp/FrameManager.cs
- lib/PuppeteerSharp/Helpers/RemoteObjectHelper.cs
- lib/PuppeteerSharp/IsolatedWorld.cs
- lib/PuppeteerSharp/MessageTask.cs
- lib/PuppeteerSharp/Messaging/BindingCalledResponse.cs
- lib/PuppeteerSharp/Messaging/RuntimeAddBindingRequest.cs
- lib/PuppeteerSharp/Page.cs
- lib/PuppeteerSharp/WaitTask.cs
See [upstream refactor](https://github.com/puppeteer/puppeteer/pull/9651)
> Reverse argument binding

- README.md
- lib/PuppeteerSharp.Tests/PageTests/ExposeFunctionTests.cs
- lib/PuppeteerSharp.Tests/PageTests/PdfTests.cs
- lib/PuppeteerSharp/CDPSession.cs
The test runner doesn't output logs in the terminal
> Improve flaky test logs

- lib/PuppeteerSharp.Tests/CoverageTests/JSCoverageTests.cs
- lib/PuppeteerSharp.Tests/Issues/Issue 2251.cs
- lib/PuppeteerSharp/CustomQueriesManager.cs
- lib/PuppeteerSharp/PuppeteerSharp.csproj
> Fix XPath querySelectorAll

- lib/PuppeteerSharp.Tests/CoverageTests/CSSCoverageTests.cs
- lib/PuppeteerSharp/Binding.cs
- lib/PuppeteerSharp/ExecutionContext.cs
Upstream is awaiting for these calls.
> await for binding calls

- lib/PuppeteerSharp.Tests/PageTests/ExposeFunctionTests.cs
> Fix expose function tests

- lib/PuppeteerSharp.Tests/HeadfulTests/HeadfulTests.cs
- lib/PuppeteerSharp/Browser.cs
- lib/PuppeteerSharp/ChromeTargetManager.cs
- lib/PuppeteerSharp/FirefoxTargetManager.cs
- lib/PuppeteerSharp/Helpers/AsyncDictionaryHelper.cs
- lib/PuppeteerSharp/ITargetManager.cs
- lib/PuppeteerSharp/PuppeteerSharp.csproj
- lib/PuppeteerSharp/Target.cs
Let's see if there is a race condition on #2280
> Make the available targets an async dictionary

- .github/workflows/dotnet.yml
- lib/PuppeteerSharp.Tests/IgnoreHttpsErrorsTests/ResponseSecurityDetailsTests.cs
- lib/PuppeteerSharp.Tests/test.runsettings
Firefox on windows is taking longer now.
> Increase test session timeout to 45 minutes

- .github/workflows/demo.yml
- lib/PuppeteerSharp/BrowserFetcher.cs
- lib/PuppeteerSharp/PuppeteerSharp.csproj
I need to figure out how to install the required certificates in macOS to run the tests. But at least, we are going to check that the build will run in macos.
> Run demo in macOS

- lib/PuppeteerSharp.TestServer/wwwroot/input/scrollable.html
- lib/PuppeteerSharp.Tests/ClickTests/ClickTests.cs
> Add missing click tests

- lib/PuppeteerSharp.Tests/CDPSessionTests/CreateCDPSessionTests.cs
> Add missing CDPSession test

- lib/PuppeteerSharp.Tests/AccessibilityTests/AccessibilityTests.cs
> Add missing accessibility test

- lib/PuppeteerSharp.Tests/BrowserContextTests/BrowserContextTests.cs
> Fix browser context test name

- lib/PuppeteerSharp.Tests/Browsers/Chromium/ChromiumDataTests.cs
- lib/PuppeteerSharp/BrowserData/JsonUtils.cs
- lib/PuppeteerSharp/PuppeteerSharp.csproj
> Fix chromium latest download

- lib/PuppeteerSharp.Tooling/IdentifyMissingTests.cs
- lib/PuppeteerSharp.Tooling/Options/IdentifyMissingTestsOptions.cs
- lib/PuppeteerSharp.Tooling/Program.cs
- lib/PuppeteerSharp.Tooling/PuppeteerSharp.Tooling.csproj
This will make the tool simpler.
> Use the test project in the missing test tool

- lib/PuppeteerSharp.Tests/CoverageTests/JSCoverageTests.cs
- lib/PuppeteerSharp.Tests/OOPIFTests/OOPIFTests.cs
- lib/PuppeteerSharp.Tooling/ScaffoldTest.cs
> Add oopif tests

- lib/PuppeteerSharp.Tests/QuerySelectorTests/PageQuerySelectorAllEvalTests.cs
> Change a querySelector test name

- lib/PuppeteerSharp.Tests/TargetManagerTests/TargetManagerTests.cs
> Add missing target manager tests

- lib/PuppeteerSharp/Browser.cs
- lib/PuppeteerSharp/ChromeTargetManager.cs
based on https://github.com/puppeteer/puppeteer/pull/10189
> Move target updates to the target manager

- docfx_project/examples/index.md
- lib/PuppeteerSharp/Browser.cs
- lib/PuppeteerSharp/InitializationStatus.cs
- lib/PuppeteerSharp/PageTarget.cs
- lib/PuppeteerSharp/Target.cs
This will match [this change](https://github.com/puppeteer/puppeteer/pull/10191)
> Introduce Target initialization status

- lib/PuppeteerSharp/ChromeTargetManager.cs
- lib/PuppeteerSharp/FirefoxTargetManager.cs
- lib/PuppeteerSharp/PageTarget.cs
- lib/PuppeteerSharp/Target.cs
Bring changes from https://github.com/puppeteer/puppeteer/pull/10600
> Separate target init from construction

- lib/PuppeteerSharp.Tests/HeadfulTests/HeadfulTests.cs
- lib/PuppeteerSharp/Browser.cs
- lib/PuppeteerSharp/DevToolsTarget.cs
- lib/PuppeteerSharp/OtherTarget.cs
- lib/PuppeteerSharp/PageTarget.cs
- lib/PuppeteerSharp/Target.cs
- lib/PuppeteerSharp/WorkerTarget.cs
This will bring DevTools targets and expose all targets to consumers.
> Expose DevTools as a target

- lib/PuppeteerSharp/Messaging/FetchFulfillRequest.cs
- lib/PuppeteerSharp/PuppeteerSharp.csproj
> Remove Microsoft.AspNetCore.WebUtilities dependency

- lib/PuppeteerSharp/ChromiumLauncher.cs
related to https://github.com/puppeteer/puppeteer/pull/10880
> Add --disable-search-engine-choice-screen to default arguments

- lib/PuppeteerSharp.TestServer/wwwroot/input/drag-and-drop.html
- lib/PuppeteerSharp.Tests/DragAndDropTests/DragAndDropTests.cs
- lib/PuppeteerSharp.Tests/DragAndDropTests/LegacyDragAndDropTests.cs
- lib/PuppeteerSharp/ElementHandle.cs
- lib/PuppeteerSharp/Frame.cs
- lib/PuppeteerSharp/IElementHandle.cs
- lib/PuppeteerSharp/IFrame.cs
- lib/PuppeteerSharp/IPage.cs
- lib/PuppeteerSharp/Page.cs
- lib/PuppeteerSharp/Target.cs
New drag and drop API. [See upstream](https://github.com/puppeteer/puppeteer/pull/10651)
> Implement improved drag and drop API

- lib/PuppeteerSharp/CDPSession.cs
- lib/PuppeteerSharp/Connection.cs
- lib/PuppeteerSharp/ICDPSession.cs
- lib/PuppeteerSharp/SessionEventArgs.cs
Based on [this change](https://github.com/puppeteer/puppeteer/pull/10941)
> Expose SessionAttached and SessionDetached events

- lib/PuppeteerSharp.Tests/CDPSessionTests/CreateCDPSessionTests.cs
- lib/PuppeteerSharp.Tests/WontImplementTests.cs
- lib/PuppeteerSharp/Browser.cs
- lib/PuppeteerSharp/CDPSession.cs
- lib/PuppeteerSharp/Connection.cs
- lib/PuppeteerSharp/CustomQueryHandler.cs
- lib/PuppeteerSharp/ElementHandle.cs
- lib/PuppeteerSharp/ExecutionContext.cs
- lib/PuppeteerSharp/Frame.cs
- lib/PuppeteerSharp/Injected/injected.js
- lib/PuppeteerSharp/QueryHandlers/AriaQueryHandler.cs
- lib/PuppeteerSharp/QueryHandlers/CustomQuerySelectorRegistry.cs
- lib/PuppeteerSharp/QueryHandlers/QueryHandler.cs
- lib/PuppeteerSharp/ScriptInjector.cs
- lib/PuppeteerSharp/Target.cs
- lib/PuppeteerSharp/WorkerTarget.cs
[upstream change](https://github.com/puppeteer/puppeteer/pull/9678)
> Refactor global bingins

- lib/PuppeteerSharp/Browser.cs
- lib/PuppeteerSharp/BrowserContextOptions.cs
- lib/PuppeteerSharp/IBrowser.cs
- lib/PuppeteerSharp/Messaging/TargetCreateBrowserContextRequest.cs
Closes #2342
Upstream reference https://github.com/puppeteer/puppeteer/pull/7516
> Implement browser context options

- lib/PuppeteerSharp/IsolatedWorld.cs
- lib/PuppeteerSharp/QueryHandlers/QueryHandler.cs
- lib/PuppeteerSharp/WaitForFunctionOptions.cs
- lib/PuppeteerSharp/WaitTask.cs
See [upstream change](https://github.com/puppeteer/puppeteer/pull/9679)
> Remove obsolete binding code

- lib/PuppeteerSharp/BrowserData/Cache.cs
- lib/PuppeteerSharp/BrowserFetcher.cs
- lib/PuppeteerSharp/IBrowserFetcher.cs
- lib/PuppeteerSharp/PuppeteerSharp.csproj
> Restore BrowserFetcher.GetExecutablePath

- lib/PuppeteerSharp/Injected/injected.js
[See upstream change](https://github.com/puppeteer/puppeteer/pull/11200)
> fix: update TextQuerySelector cache on subtree update

- lib/PuppeteerSharp/Browser.cs
- lib/PuppeteerSharp/IBrowser.cs
- lib/PuppeteerSharp/Page.cs
- lib/PuppeteerSharp/Puppeteer.cs
- lib/PuppeteerSharp/PuppeteerSharp.csproj
> Fix browser check in Page.ScreenshotAsync

- lib/PuppeteerSharp.Tests/CoverageTests/CSSResetOnNavigationTests.cs
- lib/PuppeteerSharp.Tests/CoverageTests/JSResetOnNavigationTests.cs
- lib/PuppeteerSharp.Tests/MouseTests/Dimensions.cs
- lib/PuppeteerSharp.Tests/PageTests/PdfTests.cs
- lib/PuppeteerSharp.Tests/TracingTests/TracingTests.cs
- lib/PuppeteerSharp/BoundingBox.cs
- lib/PuppeteerSharp/ContextPayload.cs
- lib/PuppeteerSharp/ContextPayloadAuxData.cs
- lib/PuppeteerSharp/FramePayload.cs
- lib/PuppeteerSharp/GeolocationOption.cs
- lib/PuppeteerSharp/Media/ScreenOrientation.cs
- lib/PuppeteerSharp/Messaging/ConnectionRequest.cs
- lib/PuppeteerSharp/Messaging/EmulateTimezoneRequest.cs
- lib/PuppeteerSharp/Messaging/EmulationSetEmulatedMediaFeatureRequest.cs
- lib/PuppeteerSharp/Messaging/EvaluateExceptionResponseInfo.cs
- lib/PuppeteerSharp/Messaging/InputDispatchKeyEventRequest.cs
- lib/PuppeteerSharp/Messaging/PageGetLayoutMetricsResponse.cs
- lib/PuppeteerSharp/Messaging/PageHandleFileChooserRequest.cs
- lib/PuppeteerSharp/Messaging/PageHandleJavaScriptDialogRequest.cs
- lib/PuppeteerSharp/Messaging/RequestWillBeSentPayload.cs
- lib/PuppeteerSharp/Messaging/RuntimeCallFunctionOnRequest.cs
- lib/PuppeteerSharp/Metric.cs
Remove some unsued usings, mostly unused Newtonsoft.Json usings.
This is a baby step towards #2362
> Remove unused Newtonsoft.Json usings

- .github/workflows/on-push-do-docs.yml
- lib/PuppeteerSharp.Tests/test.runsettings
- lib/PuppeteerSharp/Browser.cs
- lib/PuppeteerSharp/BrowserData/Firefox.cs
- lib/PuppeteerSharp/CDPSession.cs
- lib/PuppeteerSharp/ChromeTargetManager.cs
- lib/PuppeteerSharp/Connection.cs
- lib/PuppeteerSharp/FirefoxTargetManager.cs
- lib/PuppeteerSharp/ICDPSession.cs
- lib/PuppeteerSharp/ITargetManager.cs
- lib/PuppeteerSharp/Page.cs
- lib/PuppeteerSharp/SessionEventArgs.cs
- lib/PuppeteerSharp/Target.cs
- mdsnippets.json
[See upstream change](https://github.com/puppeteer/puppeteer/pull/10794)
> Remove target interceptors in favor of session events

- lib/PuppeteerSharp.Tests/DeviceRequestPromptTests/MockCDPSession.cs
- lib/PuppeteerSharp.Tests/NetworkTests/RequestPostDataTests.cs
- lib/PuppeteerSharp/DeviceRequestPromptManager.cs
- lib/PuppeteerSharp/IRequest.cs
- lib/PuppeteerSharp/Messaging/DeviceAccessCancelPrompt.cs
- lib/PuppeteerSharp/Messaging/DeviceAccessSelectPrompt.cs
- lib/PuppeteerSharp/Messaging/Protocol/Network/GetRequestPostDataRequest.cs
- lib/PuppeteerSharp/Messaging/Protocol/Network/GetRequestPostDataResponse.cs
- lib/PuppeteerSharp/Payload.cs
- lib/PuppeteerSharp/Request.cs
Upstream change https://github.com/puppeteer/puppeteer/pull/11598
closes #2401
> Support fetching request POST data

- lib/PuppeteerSharp/Frame.cs
- lib/PuppeteerSharp/FrameManager.cs
- lib/PuppeteerSharp/LifecycleWatcher.cs
- lib/PuppeteerSharp/Page.cs
Inspired by [this change](https://github.com/puppeteer/puppeteer/pull/8770)
Closes #2405
> Move navigation logic from FrameManager to Frame

- lib/PuppeteerSharp.Tests/BrowserContextTests/BrowserContextTests.cs
- lib/PuppeteerSharp.Tests/DeviceRequestPromptTests/DeviceRequestPromptWaitForDeviceTests.cs
- lib/PuppeteerSharp.Tests/DeviceRequestPromptTests/WaitForDevicePromptTests.cs
- lib/PuppeteerSharp.Tests/InputTests/PageWaitForFileChooserTests.cs
- lib/PuppeteerSharp.Tests/PageTests/WaitForRequestTests.cs
- lib/PuppeteerSharp.Tests/PageTests/WaitForResponseTests.cs
- lib/PuppeteerSharp/Browser.cs
- lib/PuppeteerSharp/BrowserContext.cs
- lib/PuppeteerSharp/DeviceRequestPrompt.cs
- lib/PuppeteerSharp/DeviceRequestPromptManager.cs
- lib/PuppeteerSharp/FileChooser.cs
- lib/PuppeteerSharp/Frame.cs
- lib/PuppeteerSharp/IBrowser.cs
- lib/PuppeteerSharp/IBrowserContext.cs
- lib/PuppeteerSharp/IFrame.cs
- lib/PuppeteerSharp/IPage.cs
- lib/PuppeteerSharp/IResponse.cs
- lib/PuppeteerSharp/Page.cs
- lib/PuppeteerSharp/PuppeteerSharp.csproj
- lib/PuppeteerSharp/WaitForFunctionOptions.cs
- lib/PuppeteerSharp/WaitForNetworkIdleOptions.cs
- lib/PuppeteerSharp/WaitForOptions.cs
- lib/PuppeteerSharp/WaitForSelectorOptions.cs
It was too minor to make it a breaking change.
> Undo breaking change

- lib/PuppeteerSharp.Tests/CoverageTests/JSCoverageTests.cs
- lib/PuppeteerSharp.Tests/LauncherTests/BrowserDisconnectTests.cs
- lib/PuppeteerSharp.Tests/LauncherTests/PuppeteerConnectTests.cs
- lib/PuppeteerSharp.Tests/NavigationTests/PageGotoTests.cs
- lib/PuppeteerSharp/ChromeTargetManager.cs
- lib/PuppeteerSharp/ElementHandle.cs
- lib/PuppeteerSharp/Frame.cs
- lib/PuppeteerSharp/FrameManager.cs
- lib/PuppeteerSharp/LifecycleWatcher.cs
closes #2406
Upstream change: https://github.com/puppeteer/puppeteer/pull/10711
> Emit events from the frame

- lib/PuppeteerSharp/Browser.cs
- lib/PuppeteerSharp/EmulationManager.cs
- lib/PuppeteerSharp/IPage.cs
- lib/PuppeteerSharp/Messaging/TargetCreateTargetRequest.cs
- lib/PuppeteerSharp/Page.cs
> Move more things to emulation manager

- lib/PuppeteerSharp.Tests/PrerenderTests/WithEmulationTests.cs
- lib/PuppeteerSharp/EmulationManager.cs
- lib/PuppeteerSharp/Page.cs
> Apply viewport emulation to prerender targets

- lib/PuppeteerSharp/EmulationManager.cs
- lib/PuppeteerSharp/Page.cs
> Unify tab target handling in page

- tools/github-ops/create-issue-from-upstream
- tools/github-ops/package-lock.json
- tools/github-ops/package.json
Some github goodies to keep track of puppeteer.
> Github ops tools

- lib/PuppeteerSharp.Nunit/TestExpectations/TestExpectations.upstream.json
- lib/PuppeteerSharp.Tests/CoverageTests/JSCoverageTests.cs
- lib/PuppeteerSharp/BrowserData/Chrome.cs
> roll to Chrome 122.0.6261.57 (r1250580)

- lib/PuppeteerSharp.TestServer/wwwroot/input/touch-move.html
- lib/PuppeteerSharp.Tests/TouchScreenTests/TouchScreenTests.cs
- lib/PuppeteerSharp/ElementHandle.cs
- lib/PuppeteerSharp/IElementHandle.cs
- lib/PuppeteerSharp/Input/ITouchscreen.cs
- lib/PuppeteerSharp/Input/Touchscreen.cs
> Add touchstart, touchmove and touchend methods

- lib/PuppeteerSharp/BrowserData/Chrome.cs
> Roll to Chrome 122.0.6261.69 (r1250580)

- lib/PuppeteerSharp/EmulationManager.cs
- lib/PuppeteerSharp/Page.cs
> Supress viewport errors for pages that do not support changing it

- lib/PuppeteerSharp/Page.cs
- lib/PuppeteerSharp/ViewPortOptions.cs
> Remove emulation from screenshots

- lib/PuppeteerSharp.Tests/BrowserContextTests/BrowserContextOverridePermissionsTests.cs
- lib/PuppeteerSharp.Tests/BrowserContextTests/BrowserContextTests.cs
- lib/PuppeteerSharp.Tests/CookiesTests/SetCookiesTests.cs
- lib/PuppeteerSharp.Tests/DevtoolsTests/DevtoolsTests.cs
- lib/PuppeteerSharp.Tests/PuppeteerBrowserContextBaseTest.cs
- lib/PuppeteerSharp/Browser.cs
- lib/PuppeteerSharp/IBrowser.cs
> [BREAKING] Rename CreateIncognitoBrowserContextAsync to CreateBrowserContextAsync

- lib/PuppeteerSharp.Tests/BrowserContextTests/BrowserContextTests.cs
- lib/PuppeteerSharp.Tests/CDPSessionTests/CreateCDPSessionTests.cs
- lib/PuppeteerSharp.Tests/HeadfulTests/HeadfulTests.cs
- lib/PuppeteerSharp.Tests/PageTests/PageEventsConsoleTests.cs
- lib/PuppeteerSharp.Tests/TargetTests/TargetTests.cs
- lib/PuppeteerSharp/IPage.cs
- lib/PuppeteerSharp/Page.cs
> Deprecate IPage.Target and add IPage.CreateCDPSessionAsync

- lib/PuppeteerSharp.Tests/FrameTests/FrameManagementTests.cs
- lib/PuppeteerSharp/Frame.cs
> FrameElement should work for framesets

- lib/PuppeteerSharp.Nunit/TestExpectations/TestExpectations.local.json
- lib/PuppeteerSharp.Tests/TargetTests/TargetTests.cs
- lib/PuppeteerSharp.Tests/WorkerTests/PageWorkerTests.cs
- lib/PuppeteerSharp/Page.cs
- lib/PuppeteerSharp/Target.cs
- lib/PuppeteerSharp/WebWorker.cs
- lib/PuppeteerSharp/WorkerTarget.cs
> Support closing workers

- docfx_project/examples/ReuseChrome.md
> Fix reusable Chrome example

- README.md
- lib/PuppeteerSharp.TestServer/wwwroot/pdf.html
- lib/PuppeteerSharp.Tests/PageTests/PdfTests.cs
- lib/PuppeteerSharp/ChromiumLauncher.cs
- lib/PuppeteerSharp/ElementHandle.cs
- lib/PuppeteerSharp/Messaging/PagePrintToPDFRequest.cs
- lib/PuppeteerSharp/Page.cs
- lib/PuppeteerSharp/PdfOptions.cs
> Add outline to PDF generation

- lib/PuppeteerSharp/FrameManager.cs
> Synchronize frame tree with the events processing

- .github/workflows/dotnet.yml
- lib/PuppeteerSharp.Nunit/PuppeteerSharp.Nunit.csproj
- lib/PuppeteerSharp.Nunit/PuppeteerTestAttribute.cs
- lib/PuppeteerSharp.Nunit/TestExpectations/TestExpectation.cs
- lib/PuppeteerSharp.Nunit/TestExpectations/TestExpectations.local.json
- lib/PuppeteerSharp.TestServer/wwwroot/input/mouse-helper.js
- lib/PuppeteerSharp.TestServer/wwwroot/input/scrollable.html
- lib/PuppeteerSharp.TestServer/wwwroot/input/textarea.html
- lib/PuppeteerSharp.Tests/BrowserTests/BrowserVersionTests.cs
- lib/PuppeteerSharp.Tests/LauncherTests/PuppeteerLaunchTests.cs
- lib/PuppeteerSharp.Tests/MouseTests/MouseTests.cs
- lib/PuppeteerSharp.Tests/NetworkTests/PageAuthenticateTests.cs
- lib/PuppeteerSharp.Tests/NetworkTests/RequestHeadersTests.cs
- lib/PuppeteerSharp.Tests/NetworkTests/RequestPostDataTests.cs
- lib/PuppeteerSharp.Tests/NetworkTests/ResponseFromCacheTests.cs
- lib/PuppeteerSharp.Tests/NetworkTests/ResponseFromServiceWorkerTests.cs
- lib/PuppeteerSharp.Tests/NetworkTests/ResponseTextTests.cs
- lib/PuppeteerSharp.Tests/OOPIFTests/OOPIFTests.cs
- lib/PuppeteerSharp.Tests/RequestInterceptionExperimentalTests/PageSetRequestInterceptionTests.cs
- lib/PuppeteerSharp.Tests/RequestInterceptionTests/SetRequestInterceptionTests.cs
- lib/PuppeteerSharp.Tests/TestConstants.cs
- lib/PuppeteerSharp/ChromiumLauncher.cs
- lib/PuppeteerSharp/FirefoxLauncher.cs
- lib/PuppeteerSharp/HeadlessMode.cs
- lib/PuppeteerSharp/LaunchOptions.cs
- lib/PuppeteerSharp/Page.cs
New headless mode!!
closes #2422
> [BREAKING] Introduce new headless mode

- .github/workflows/dotnet.yml
- lib/PuppeteerSharp.Tests/ChromeLauncherTests/GetFeaturesTests.cs
- lib/PuppeteerSharp.Tests/ChromeLauncherTests/RemoveMatchingFlagsTests.cs
- lib/PuppeteerSharp.Tests/FixturesTests/FixturesTests.cs
- lib/PuppeteerSharp/BrowserData/Chrome.cs
- lib/PuppeteerSharp/BrowserData/ChromeHeadlessShell.cs
- lib/PuppeteerSharp/BrowserData/InstalledBrowser.cs
- lib/PuppeteerSharp/BrowserFetcher.cs
- lib/PuppeteerSharp/ChromeLauncher.cs
- lib/PuppeteerSharp/LaunchOptions.cs
- lib/PuppeteerSharp/Launcher.cs
- lib/PuppeteerSharp/Puppeteer.cs
- lib/PuppeteerSharp/SupportedBrowser.cs
> Download chrome-headless-shell by default and use it for the old headless mode

- lib/PuppeteerSharp.Tests/CDPSessionTests/CreateCDPSessionTests.cs
- lib/PuppeteerSharp.Tests/DeviceRequestPromptTests/MockCDPSession.cs
- lib/PuppeteerSharp/CDPSession.cs
- lib/PuppeteerSharp/CommandOptions.cs
- lib/PuppeteerSharp/ConnectOptions.cs
- lib/PuppeteerSharp/Connection.cs
- lib/PuppeteerSharp/ICDPConnection.cs
- lib/PuppeteerSharp/ICDPSession.cs
- lib/PuppeteerSharp/IConnectionOptions.cs
- lib/PuppeteerSharp/LaunchOptions.cs
- lib/PuppeteerSharp/MessageException.cs
- lib/PuppeteerSharp/Transport/IConnectionTransport.cs
- lib/PuppeteerSharp/Transport/WebSocketTransport.cs
> Support timeouts per CDP command

- lib/PuppeteerSharp/FirefoxLauncher.cs
> Disable GFX sanity window for Firefox

- lib/PuppeteerSharp.Tests/EvaluationTests/RemoveScriptToEvaluateOnNewDocumentTests.cs
- lib/PuppeteerSharp.Tests/PageTests/ExposeFunctionTests.cs
- lib/PuppeteerSharp.Tests/PageTests/RemoveExposedFunctionTests.cs
- lib/PuppeteerSharp/IPage.cs
- lib/PuppeteerSharp/Messaging/PageAddScriptToEvaluateOnNewDocumentResponse.cs
- lib/PuppeteerSharp/Messaging/PageRemoveScriptToEvaluateOnNewDocumentRequest.cs
- lib/PuppeteerSharp/Messaging/RuntimeRemoveBindingRequest.cs
- lib/PuppeteerSharp/NewDocumentScriptEvaluation.cs
- lib/PuppeteerSharp/Page.cs
> Introduce RemoveExposedFunctionAsync and RemoveScriptToEvaluateOnNewDocumentAsync

- lib/PuppeteerSharp.Tests/LauncherTests/BrowserTargetEventsTests.cs
- lib/PuppeteerSharp/BindingUtils.cs
- lib/PuppeteerSharp/Frame.cs
- lib/PuppeteerSharp/IsolatedWorld.cs
- lib/PuppeteerSharp/Page.cs
> Improve expose function reliability

- lib/PuppeteerSharp/WebWorker.cs
> Expose WebWorker.Client

- lib/PuppeteerSharp.Nunit/TestExpectations/TestExpectations.local.json
- tools/upstream-ops/generate-ignore-tests.js
- tools/upstream-ops/package.json
This is the first step to start working on webdriver bidi.
> Ignore all tests on webdriver bidi

- lib/PuppeteerSharp/Cdp/CdpDialog.cs
- lib/PuppeteerSharp/Dialog.cs
- lib/PuppeteerSharp/Page.cs
Getting the Dialog class ready for webdriver bidi
> Split Dialog class

- lib/PuppeteerSharp/Cdp/CdpWebWorker.cs
- lib/PuppeteerSharp/Page.cs
- lib/PuppeteerSharp/WebWorker.cs
- lib/PuppeteerSharp/WorkerTarget.cs
> Introduce CdpWebWorker

- lib/PuppeteerSharp.Tests/NetworkManagerTests/NetworkManagerTests.cs
- lib/PuppeteerSharp.Tests/NetworkTests/NetworkEventTests.cs
- lib/PuppeteerSharp.Tests/RequestInterceptionExperimentalTests/PageSetRequestInterceptionTests.cs
- lib/PuppeteerSharp.Tests/RequestInterceptionTests/SetRequestInterceptionTests.cs
- lib/PuppeteerSharp/Cdp/CdpHttpRequest.cs
- lib/PuppeteerSharp/Cdp/CdpHttpResponse.cs
- lib/PuppeteerSharp/Cdp/LifecycleWatcher.cs
- lib/PuppeteerSharp/Cdp/NetworkEventManager.cs
- lib/PuppeteerSharp/Cdp/NetworkManager.cs
- lib/PuppeteerSharp/Frame.cs
- lib/PuppeteerSharp/FrameManager.cs
- lib/PuppeteerSharp/IFrame.cs
- lib/PuppeteerSharp/IPage.cs
- lib/PuppeteerSharp/IRequest.cs
- lib/PuppeteerSharp/IResponse.cs
- lib/PuppeteerSharp/NetworkManager.cs
- lib/PuppeteerSharp/Page.cs
- lib/PuppeteerSharp/RemoteAddress.cs
- lib/PuppeteerSharp/Request.cs
- lib/PuppeteerSharp/RequestAbortErrorCode.cs
- lib/PuppeteerSharp/ResourceType.cs
- lib/PuppeteerSharp/Response.cs
- lib/PuppeteerSharp/SecurityDetails.cs
- lib/PuppeteerSharp/WebWorker.cs
closes #2551
closes #2559
Breaking:
* Request.Failure was renamed to Request.FailureText.
* Request.RequestId was renamed to Request.Id
> [BREAKING] Split Response and Request classes

- README.md
- docfx_project/examples/DownloadFetcher.Download.md
- lib/PuppeteerSharp/Browser.cs
- lib/PuppeteerSharp/Cdp/CdpDevToolsTarget.cs
- lib/PuppeteerSharp/Cdp/CdpOtherTarget.cs
- lib/PuppeteerSharp/Cdp/CdpPageTarget.cs
- lib/PuppeteerSharp/Cdp/CdpTarget.cs
- lib/PuppeteerSharp/Cdp/CdpWorkerTarget.cs
- lib/PuppeteerSharp/Cdp/ChromeTargetManager.cs
- lib/PuppeteerSharp/Cdp/FirefoxTargetManager.cs
- lib/PuppeteerSharp/Cdp/ITargetManager.cs
- lib/PuppeteerSharp/Target.cs
> Split target class

- lib/PuppeteerSharp/Cdp/CdpElementHandle.cs
- lib/PuppeteerSharp/Cdp/CdpJSHandle.cs
- lib/PuppeteerSharp/Cdp/CdpWebWorker.cs
- lib/PuppeteerSharp/ElementHandle.cs
- lib/PuppeteerSharp/ExecutionContext.cs
- lib/PuppeteerSharp/Frame.cs
- lib/PuppeteerSharp/JSHandle.cs
- lib/PuppeteerSharp/Target.cs
> Split JSHandle and ElementHandle

- lib/PuppeteerSharp/Cdp/CdpKeyboard.cs
- lib/PuppeteerSharp/Cdp/CdpMouse.cs
- lib/PuppeteerSharp/Cdp/CdpPage.cs
- lib/PuppeteerSharp/Cdp/CdpTouchscreen.cs
- lib/PuppeteerSharp/Input/Keyboard.cs
- lib/PuppeteerSharp/Input/Mouse.cs
- lib/PuppeteerSharp/Input/Touchscreen.cs
> Split input classes

- lib/PuppeteerSharp/BrowserData/Chrome.cs
- lib/PuppeteerSharp/PuppeteerSharp.csproj
> Roll chrome to 123.0.6312.86

- lib/PuppeteerSharp.Nunit/TestExpectations/TestExpectations.upstream.json
- lib/PuppeteerSharp.Tests/NetworkTests/PageSetBypassServiceWorkerTests.cs
- lib/PuppeteerSharp/Cdp/CdpPage.cs
- lib/PuppeteerSharp/Cdp/Messaging/Protocol/Network/SetBypassServiceWorkerRequest.cs
- lib/PuppeteerSharp/IPage.cs
- lib/PuppeteerSharp/Page.cs
> Introduce Page.SetBypassServiceWorkerAsync

- lib/PuppeteerSharp.TestServer/wwwroot/cached/bfcache/index.html
- lib/PuppeteerSharp.TestServer/wwwroot/cached/bfcache/target.html
- lib/PuppeteerSharp.TestServer/wwwroot/cached/bfcache/worker-iframe-container.html
- lib/PuppeteerSharp.TestServer/wwwroot/cached/bfcache/worker-iframe.html
- lib/PuppeteerSharp.TestServer/wwwroot/cached/bfcache/worker.mjs
- lib/PuppeteerSharp.Tests/BFCacheTests/BFCacheTests.cs
- lib/PuppeteerSharp/Cdp/CdpPage.cs
- lib/PuppeteerSharp/Cdp/FrameManager.cs
- lib/PuppeteerSharp/Cdp/LifecycleWatcher.cs
- lib/PuppeteerSharp/Cdp/Messaging/NavigationType.cs
- lib/PuppeteerSharp/Cdp/Messaging/PageFrameNavigatedResponse.cs
- lib/PuppeteerSharp/ElementHandle.cs
- lib/PuppeteerSharp/Frame.cs
- lib/PuppeteerSharp/FrameNavigatedEventArgs.cs
- lib/PuppeteerSharp/IPage.cs
- lib/PuppeteerSharp/Page.cs
> Make page.goBack work with bfcache in tab mode

- lib/PuppeteerSharp/BrowserData/Firefox.cs
- lib/PuppeteerSharp/FirefoxLauncher.cs
- lib/PuppeteerSharp/LaunchOptions.cs
> Ensure fission.bfcacheInParent is disabled for cdp in Firefox

- lib/PuppeteerSharp.Tests/AriaQueryHandlerTests/WaitForSelectorAriaTests.cs
- lib/PuppeteerSharp.Tests/FrameTests/FrameManagementTests.cs
- lib/PuppeteerSharp.Tests/FrameUtils.cs
- lib/PuppeteerSharp.Tests/LauncherTests/PuppeteerConnectTests.cs
- lib/PuppeteerSharp.Tests/PageExtensions.cs
- lib/PuppeteerSharp.Tests/PuppeteerSharp.Tests.csproj
- lib/PuppeteerSharp.Tests/WaitTaskTests/FrameWaitForSelectorTests.cs
- lib/PuppeteerSharp/Frame.cs
- lib/PuppeteerSharp/IFrame.cs
> [BREAKING] Deprecate Frame.Name and expose FrameElement

- lib/PuppeteerSharp.Tests/EmulationTests/EmulateTests.cs
- lib/PuppeteerSharp.Tests/NavigationTests/PageGotoTests.cs
- lib/PuppeteerSharp/Cdp/CdpFrame.cs
- lib/PuppeteerSharp/Cdp/CdpPage.cs
- lib/PuppeteerSharp/NavigationOptions.cs
> Reload should not resolve early on fragment navigations

- lib/PuppeteerSharp/QueryHandlers/AriaQueryHandler.cs
[see upstream change](https://github.com/puppeteer/puppeteer/pull/12224/files)
> Query only unignored nodes

- lib/PuppeteerSharp/ElementHandle.cs
- lib/PuppeteerSharp/Frame.cs
- lib/PuppeteerSharp/IElementHandle.cs
- lib/PuppeteerSharp/IFrame.cs
- lib/PuppeteerSharp/IPage.cs
- lib/PuppeteerSharp/Page.cs
If we drop this method, people will create their extension method. These functions relies on the functionality the new engines provides.
> Revert breaking XPath Change

- lib/PuppeteerSharp/Cdp/CdpPage.cs
> Wait for fonts before pdf printing

- lib/PuppeteerSharp/ElementHandle.cs
> Cache isolated handle

- README.md
- docfx_project/examples/DownloadFetcher.Download.md
- docfx_project/examples/ReuseChrome.md
- lib/PuppeteerSharp.Tests/Browsers/Chrome/ChromeDataTests.cs
> Fix reuse chrome docs

- lib/PuppeteerSharp/BrowserFetcher.cs
- lib/PuppeteerSharp/Launcher.cs
- lib/PuppeteerSharp/PuppeteerSharp.csproj
> Fix chromium version fetcher

- lib/PuppeteerSharp/BrowserFetcher.cs
> Replace WebException with HttpRequestException

- lib/PuppeteerSharp.Tests/PageTests/RemoveExposedFunctionTests.cs
- lib/PuppeteerSharp/Cdp/CdpPage.cs
> fix Page.RemoveExposedFunctionAsync

- lib/PuppeteerSharp.Nunit/TestExpectations/TestExpectations.upstream.json
- lib/PuppeteerSharp.Tests/OOPIFTests/OOPIFTests.cs
- lib/PuppeteerSharp/Browser.cs
- lib/PuppeteerSharp/BrowserFetcher.cs
- lib/PuppeteerSharp/Cdp/CdpBrowser.cs
- lib/PuppeteerSharp/Cdp/CdpPage.cs
- lib/PuppeteerSharp/Cdp/ChromeTargetManager.cs
- lib/PuppeteerSharp/Cdp/FirefoxTargetManager.cs
- lib/PuppeteerSharp/Cdp/ITargetManager.cs
- lib/PuppeteerSharp/ITarget.cs
- lib/PuppeteerSharp/Page.cs
- lib/PuppeteerSharp/PuppeteerSharp.csproj
- lib/PuppeteerSharp/Target.cs
> Ensure existing targets are attached to pages

- lib/PuppeteerSharp.Tests/LauncherTests/BrowserCloseTests.cs
- lib/PuppeteerSharp/Browser.cs
- lib/PuppeteerSharp/Helpers/TempDirectory.cs
- lib/PuppeteerSharp/LauncherBase.cs
- lib/PuppeteerSharp/PuppeteerSharp.csproj
- lib/PuppeteerSharp/States/DisposedState.cs
- lib/PuppeteerSharp/States/ExitedState.cs
- lib/PuppeteerSharp/States/ExitingState.cs
- lib/PuppeteerSharp/States/KillingState.cs
- lib/PuppeteerSharp/States/ProcessStartingState.cs
- lib/PuppeteerSharp/States/StartedState.cs
- lib/PuppeteerSharp/States/State.cs
> Ensure temp directory is deleted on disposal

- lib/PuppeteerSharp/Cdp/CdpElementHandle.cs
We should wait for the inner handle
> Await handle on disposal

- lib/PuppeteerSharp.Tests/Browsers/Firefox/FirefoxDataTests.cs
- lib/PuppeteerSharp/BrowserData/Firefox.cs
- lib/PuppeteerSharp/BrowserData/FirefoxChannel.cs
- lib/PuppeteerSharp/BrowserFetcher.cs
- lib/PuppeteerSharp/BrowserTag.cs
- lib/PuppeteerSharp/FirefoxLauncher.cs
- lib/PuppeteerSharp/Helpers/EnumHelper.cs
> Add support to firefox channels

- lib/PuppeteerSharp.Nunit/TestExpectations/TestExpectations.upstream.json
- lib/PuppeteerSharp.Tests/CookiesTests/SetCookiesTests.cs
- lib/PuppeteerSharp/CookieSourceScheme.cs
- lib/PuppeteerSharp/PuppeteerSharp.csproj
> Fix cookie source scheme

- lib/PuppeteerSharp/Cdp/ChromeTargetManager.cs
> fix: only wait for page and frame targets when connecting

- .github/workflows/demo.yml
- .github/workflows/dotnet.yml
- lib/PuppeteerSharp.Tests/AriaQueryHandlerTests/ParseAriaSelectorTests.cs
- lib/PuppeteerSharp/QueryHandlers/AriaQueryHandler.cs
> BREAKING: remove whitespace normalization from a11y selectors

- .github/workflows/dotnet.yml
- README.md
- lib/PuppeteerSharp.Nunit/PuppeteerTestAttribute.cs
- lib/PuppeteerSharp/BrowserFetcher.cs
- lib/PuppeteerSharp/BrowserFetcherOptions.cs
- lib/PuppeteerSharp/LaunchOptions.cs
- lib/PuppeteerSharp/Launcher.cs
closes #2724
It's not a breaking change for us.
> Rename product to browser

- lib/PuppeteerSharp.Nunit/TestExpectations/TestExpectations.upstream.json
- lib/PuppeteerSharp.Tests/OOPIFTests/OOPIFTests.cs
- lib/PuppeteerSharp/Cdp/CdpFrame.cs
- lib/PuppeteerSharp/Cdp/FrameManager.cs
- lib/PuppeteerSharp/Frame.cs
- lib/PuppeteerSharp/IFrame.cs
> Remove deprecated IsOopFrame

- lib/PuppeteerSharp/Cdp/Connection.cs
- lib/PuppeteerSharp/Transport/MessageReceivedEventArgs.cs
- lib/PuppeteerSharp/Transport/WebSocketTransport.cs
Moved to the v20 branch due to a breaking change.
> Revert "Use byte array in message received to avoid some unnecessary encoding"

- lib/PuppeteerSharp/Cdp/Connection.cs
- lib/PuppeteerSharp/Transport/MessageReceivedEventArgs.cs
- lib/PuppeteerSharp/Transport/WebSocketTransport.cs
Looks like this commit got lost (reverted and not applied again) with the v20 merge.
> Use byte array in message received to avoid some unnecessary encoding (#2748)

- lib/PuppeteerSharp.TestServer/wwwroot/lone-surrogate.html
- lib/PuppeteerSharp.Tests/PageTests/GetContentTests.cs
- lib/PuppeteerSharp/Frame.cs
- lib/PuppeteerSharp/GetContentOptions.cs
- lib/PuppeteerSharp/IFrame.cs
- lib/PuppeteerSharp/IPage.cs
- lib/PuppeteerSharp/Page.cs
> Replace lone surrogates option

- lib/PuppeteerSharp.Tests/EmulationTests/PageEmulateNetworkConditionsTests.cs
- lib/PuppeteerSharp/NetworkConditions.cs
- lib/PuppeteerSharp/PredefinedNetworkConditions.cs
Second commit updates the test which hasn't been done upstream.
Fixes #2763
> Add Slow 4G / Fast 4G predefined network conditions

- lib/PuppeteerSharp.Tests/LauncherTests/PuppeteerConnectTests.cs
- lib/PuppeteerSharp.Tests/NetworkManagerTests/NetworkManagerTests.cs
- lib/PuppeteerSharp/Browser.cs
- lib/PuppeteerSharp/Cdp/CdpBrowser.cs
- lib/PuppeteerSharp/Cdp/CdpDevToolsTarget.cs
- lib/PuppeteerSharp/Cdp/CdpPage.cs
- lib/PuppeteerSharp/Cdp/CdpPageTarget.cs
- lib/PuppeteerSharp/Cdp/CdpTarget.cs
- lib/PuppeteerSharp/Cdp/FrameManager.cs
- lib/PuppeteerSharp/Cdp/NetworkManager.cs
- lib/PuppeteerSharp/IBrowser.cs
Align with upstream https://github.com/puppeteer/puppeteer/pull/12339
Target branch v21 because of breaking change.
> refactor: configure https error handling globally

- lib/PuppeteerSharp/Launcher.cs
- lib/PuppeteerSharp/PuppeteerSharp.csproj
fixes https://github.com/hardkoded/puppeteer-sharp/issues/2800
> Only get build ID if executable path is not supplied.

- .gitignore
- lib/PuppeteerSharp.Tests/EvaluationTests/PageEvaluateTests.cs
* Ignore test screenshots folder in .gitignore
* Refactor EvaluationTests.ShouldAcceptObjectHandleAsAnArgument
Change variable type to object as test suggest
> Ignore test screenshots folder in .gitignore

- lib/PuppeteerSharp/BrowserData/Chrome.cs
> Roll chrome to 130

- lib/PuppeteerSharp/Cdp/CdpHttpRequest.cs
- lib/PuppeteerSharp/Cdp/Messaging/Request.cs
- lib/PuppeteerSharp/PuppeteerSharp.csproj
Use the correct type
closes #2809
> Fix PostData type in protocol

- lib/PuppeteerSharp.Nunit/PuppeteerTestAttribute.cs
- lib/PuppeteerSharp.Nunit/TestExpectations/TestExpectations.local.json
- lib/PuppeteerSharp.Tests/EvaluationTests/PageEvaluateTests.cs
- lib/PuppeteerSharp.Tests/NavigationTests/PageWaitForNavigationTests.cs
- lib/PuppeteerSharp/Bidi/BidiFrame.cs
- lib/PuppeteerSharp/Bidi/BidiFrameRealm.cs
- lib/PuppeteerSharp/Bidi/BidiJSHandle.cs
- lib/PuppeteerSharp/Bidi/BidiPage.cs
- lib/PuppeteerSharp/Bidi/BidiRealm.cs
- lib/PuppeteerSharp/Bidi/Core/BrowsingContext.cs
- lib/PuppeteerSharp/Bidi/Core/CallFunctionParameters.cs
- lib/PuppeteerSharp/Bidi/Core/DedicatedWorkerRealm.cs
- lib/PuppeteerSharp/Bidi/Core/IDedicatedWorkerOwnerRealm.cs
- lib/PuppeteerSharp/Bidi/Core/Realm.cs
- lib/PuppeteerSharp/Bidi/Core/WorkerRealmEventArgs.cs
- lib/PuppeteerSharp/Bidi/WindowRealm.cs
- lib/PuppeteerSharp/ExecutionContext.cs
- lib/PuppeteerSharp/ExecutionUtils.cs
- lib/PuppeteerSharp/Frame.cs
- lib/PuppeteerSharp/IPuppeteerUtilWrapper.cs
- lib/PuppeteerSharp/IsolatedWorld.cs
- lib/PuppeteerSharp/PuppeteerSharp.csproj
- lib/PuppeteerSharp/Realm.cs
There are lots of tests that are using functions. This is a first implementation to unlock other tests.
> First bidi function evaluation implementation

- .github/workflows/dotnet.yml
- lib/PuppeteerSharp.Nunit/TestExpectations/TestExpectations.local.json
- lib/PuppeteerSharp.Tests/BrowserTests/UserAgentTests.cs
- lib/PuppeteerSharp/Bidi/BidiBrowser.cs
Unlocking browser.version tests
> Bidi: Browser.version and Browser.userAgent

- lib/PuppeteerSharp.Nunit/TestExpectations/TestExpectations.local.json
> Ignore page spec ignores

- .github/workflows/on-push-do-docs.yml
- .github/workflows/publish-docs.yml
- lib/PuppeteerSharp/Cdp/CdpElementHandle.cs
- lib/PuppeteerSharp/Cdp/CdpJSHandle.cs
- lib/PuppeteerSharp/ElementHandle.cs
- lib/PuppeteerSharp/JSHandle.cs
This will help us with the Bidi implementation
> Refactor ElementHandle

- lib/PuppeteerSharp.Nunit/TestExpectations/TestExpectations.local.json
- lib/PuppeteerSharp.Tests/JSHandleTests/ToStringTests.cs
- lib/PuppeteerSharp/Bidi/BidiDeserializer.cs
- lib/PuppeteerSharp/Bidi/BidiElementHandle.cs
- lib/PuppeteerSharp/Bidi/BidiJSHandle.cs
- lib/PuppeteerSharp/Bidi/BidiRealm.cs
- lib/PuppeteerSharp/Binding.cs
- lib/PuppeteerSharp/Cdp/CdpElementHandle.cs
- lib/PuppeteerSharp/Cdp/CdpJSHandle.cs
- lib/PuppeteerSharp/Cdp/CdpPage.cs
- lib/PuppeteerSharp/Cdp/ICdpHandle.cs
- lib/PuppeteerSharp/ElementHandle.cs
- lib/PuppeteerSharp/ExecutionContext.cs
- lib/PuppeteerSharp/IJSHandle.cs
- lib/PuppeteerSharp/IsolatedWorld.cs
- lib/PuppeteerSharp/JSHandle.cs
- lib/PuppeteerSharp/PageAccessibility/Accessibility.cs
- lib/PuppeteerSharp/PuppeteerHandleExtensions.cs
- lib/PuppeteerSharp/QueryHandlers/AriaQueryHandler.cs
First implementation of JS and Element handle with passing ToString tests.
> Bidi element handle

- lib/PuppeteerSharp.Nunit/TestExpectations/TestExpectations.local.json
- lib/PuppeteerSharp.Tests/AriaQueryHandlerTests/ParseAriaSelectorTests.cs
- lib/PuppeteerSharp.Tests/AriaQueryHandlerTests/QueryAllArrayTests.cs
- lib/PuppeteerSharp.Tests/AriaQueryHandlerTests/QueryAllTests.cs
- lib/PuppeteerSharp.Tests/AriaQueryHandlerTests/QueryOneTests.cs
- lib/PuppeteerSharp.Tests/AriaQueryHandlerTests/WaitForSelectorAriaTests.cs
These are already being ignored
> Remove some upstream ignores

- lib/PuppeteerSharp/Cdp/CdpPage.cs
- lib/PuppeteerSharp/Cdp/NetworkEventManager.cs
- lib/PuppeteerSharp/Cdp/NetworkManager.cs
- lib/PuppeteerSharp/Page.cs
- lib/PuppeteerSharp/PuppeteerSharp.csproj
- lib/PuppeteerSharp/WaitForNetworkIdleOptions.cs
This reverts commit 399890f9ac849415ce0e0043b940cde1486a4125.
It seems this change was problematic
closes #2877
> Revert "Refactor WaitForNetworkIdle"

- lib/PuppeteerSharp.Nunit/TestExpectations/TestExpectations.local.json
- lib/PuppeteerSharp.Tests/NetworkTests/RequestPostDataTests.cs
- lib/PuppeteerSharp/Cdp/Messaging/Request.cs
- lib/PuppeteerSharp/Helpers/Json/LowSurrogateConverter.cs
- lib/PuppeteerSharp/PageCoverage/JSCoverage.cs
- lib/PuppeteerSharp/PuppeteerSharp.csproj
> Fix low surrogate on post data

- lib/PuppeteerSharp.AspNetFramework/PuppeteerSharp.AspNetFramework.csproj
- lib/PuppeteerSharp/PuppeteerSharp.csproj
- lib/PuppeteerSharp/Transport/WebSocketTransport.cs
AspNetFramework package needs it
> Change WebSocketTransport constructor to protected

- lib/PuppeteerSharp/Cdp/CdpHttpResponse.cs
- lib/PuppeteerSharp/ExecutionContext.cs
- lib/PuppeteerSharp/QueryHandlers/AriaQueryHandler.cs
Use source generated regexes for hot paths for .NET 8 target.
> Use source generated regexes for hot paths
