hardkoded/puppeteer-sharp

lib/PuppeteerSharp.Tests/Puppeteer/ExecutablePathTests.cs
lib/PuppeteerSharp.Tests/TestConstants.cs
lib/PuppeteerSharp/Downloader.cs
lib/PuppeteerSharp/Launcher.cs
lib/PuppeteerSharp/Puppeteer.cs

added Puppeteer.executablePath tests

---

lib/PuppeteerSharp/Connection.cs
lib/PuppeteerSharp/Page.cs

In some scenarios `GetAwaiter().Result` might produce some deadlocks, there are many [post about this](https://blog.stephencleary.com/2012/07/dont-block-on-async-code.html).
I was never a fan of GetAwaiters because there was something in my mind saying "hey this might break", but we were forced to use `GetAwaiter` because we don't have a DisposableAsync.
So we fell into some deadlocks in console apps. 
When we lock the execution here:
https://github.com/kblok/puppeteer-sharp/blob/master/lib/PuppeteerSharp/Page.cs#L783
There we are preventing the `ReceiveAsync` method from getting the result the same `CloseAsync`, through `target.closeTarget` is waiting for.
https://github.com/kblok/puppeteer-sharp/blob/master/lib/PuppeteerSharp/Connection.cs#L134
I'm fixing this by calling that close as a …

Fire and forget Target.closeTarget

---

lib/PuppeteerSharp.Tests/Issues/Issue0128.cs
lib/PuppeteerSharp/ChromeProcessException.cs
lib/PuppeteerSharp/Launcher.cs

* Check if the process is running before killing it.
* Grab the output from the output variable instead of trying to read the stream again.
Closes #128

Process exit improvements

---

lib/PuppeteerSharp.Tests/Frame/WaitForFunctionTests.cs
lib/PuppeteerSharp/Frame.cs
lib/PuppeteerSharp/WaitForFunctionOptions.cs
lib/PuppeteerSharp/WaitTask.cs

closes #139 
the following tests aren't relevant for C#:
- should accept a string (always a string...)
- should throw on bad polling value (we use an enum)

Implemented Frame.waitForFunction tests

---

lib/PuppeteerSharp/Browser.cs
lib/PuppeteerSharp/Launcher.cs

We have a similar issue we had on #126. The GetAwaiter was hanging on some platforms (like a console app). For instance, the PuppeteerConnectTests.ShouldBeAbleToReconnectToADisconnectedBrowser (https://github.com/kblok/puppeteer-sharp/blob/9bebc1f8a305af365b99d18eedb135e68139104c/lib/PuppeteerSharp.Tests/Puppeteer/PuppeteerConnectTests.cs#L32) hangs if run on a console app.
The solution is quite similar to #126. As we don't need to wait for `Browse.close`.  We just trigger and forget it.
`_closeCallBack` might have a process kill (when we create a process) we would need to await, or a `Browser.close` (when we call connect) we can just trigger and forget.
closes #176

Don't await browse.close task

---

README.md

I'm not sure these changes are correct, but as-is the two AppVeyor 'build status' badges in the README are pointing to the same (AppVeyor) project. Based on the markup in the README file itself, I'm guessing one of the badges was meant to reference the build status of the demo project.
But, even with these changes, there's no visual distinction between the two build status badges. If you have an idea how that should be affected, I'll take a stab at it.

Fix demo build status badge in README

---

README.md

This remove an extraneous `)` in the PDF example in the README.

Fix PDF README example

---

demos/PuppeteerSharpPdfDemo/PuppeteerSharpPdfDemo.csproj
lib/PuppeteerSharp/Downloader.cs
lib/PuppeteerSharp/PuppeteerSharp.csproj

`IntPtr.Size == 8` checks if the application is in 64bits. We need to check whether the host OS is 64bits or not.
closes #294

Fix Chromium downloader on 32bits apps runnning on a x64 platform

---

lib/PuppeteerSharp.TestServer/wwwroot/self-request.html
lib/PuppeteerSharp.Tests/PageTests/GotoTests.cs
lib/PuppeteerSharp.Tests/PuppeteerTests/PuppeteerLaunchTests.cs
lib/PuppeteerSharp/SecurityDetails.cs

Basically, we're supporting SecurityDetails deserializations.
closes #270 
closes #276

Update GotoTests and PuppeteerLaunchTests

---

README.md

the readme will now show the nuget stats
before:
after:

fixed NuGet badge

---

lib/PuppeteerSharp.Tests/TracingTests/TracingTests.cs
lib/PuppeteerSharp/Tracing.cs

Closes #406 
Notice I didn't implemented the test [should return null in case of Buffer error](https://github.com/kblok/puppeteer/commit/98bb2615adb6815c91efcc59593b49e2ec8c3935#diff-e999dddd5041362922d73b6a99f0c6a3R64) because we are returning a string here.

return the trace from tracing.stop

---

lib/PuppeteerSharp.Tests/TestConstants.cs
lib/PuppeteerSharp/Connection.cs
lib/PuppeteerSharp/Frame.cs
lib/PuppeteerSharp/Page.cs
lib/PuppeteerSharp/WaitTask.cs

Remove warnings

---

lib/PuppeteerSharp.Tests/ElementHandleTests/EvaluateFunctionTests.cs

As we [decided on v0.7](http://www.hardkoded.com/blogs/puppeteer-sharp-v07-released). The `$eval` function will be ported using 2 method calls `QuerySelectorAsync` and `EvaluateFunctionAsync`.
I'm adding the test as an example of this feature mapping.
closes #449

ElementHandle EvaluateFunctionAsync examples

---

lib/PuppeteerSharp.Tests/PageTests/EvaluateTests.cs
lib/PuppeteerSharp/ExecutionContext.cs
lib/PuppeteerSharp/ScreenshotType.cs

closes #448 
Notice that this test has only one call because we always execution functions using strings

Allow user gesture restricted code to be run in Page.EvaluateExpressionAsync

---

lib/PuppeteerSharp/Browser.cs
lib/PuppeteerSharp/BrowserFetcher.cs
lib/PuppeteerSharp/CDPSession.cs
lib/PuppeteerSharp/Connection.cs
lib/PuppeteerSharp/Dialog.cs
lib/PuppeteerSharp/ElementHandle.cs
lib/PuppeteerSharp/EmulationManager.cs
lib/PuppeteerSharp/ExecutionContext.cs
lib/PuppeteerSharp/Extensions.cs
lib/PuppeteerSharp/Frame.cs
lib/PuppeteerSharp/Helpers/RemoteObjectHelper.cs
lib/PuppeteerSharp/Helpers/TaskQueue.cs
lib/PuppeteerSharp/Input/Keyboard.cs
lib/PuppeteerSharp/Input/Mouse.cs
lib/PuppeteerSharp/Input/Touchscreen.cs
lib/PuppeteerSharp/JSHandle.cs
lib/PuppeteerSharp/Launcher.cs
lib/PuppeteerSharp/NavigatorWatcher.cs
lib/PuppeteerSharp/NetworkManager.cs
lib/PuppeteerSharp/Page.cs
lib/PuppeteerSharp/PageCoverage/CSSCoverage.cs
lib/PuppeteerSharp/PageCoverage/JSCoverage.cs
lib/PuppeteerSharp/Request.cs
lib/PuppeteerSharp/Response.cs
lib/PuppeteerSharp/Target.cs
lib/PuppeteerSharp/Tracing.cs
lib/PuppeteerSharp/WaitTask.cs

- to prevent deadlocks, every await must be paired with .ConfigureAwait(false)
- this is especially important when puppeteer is called from context which must wait for the task synchronously, e.g. using .GetAwaiter.GetResult() or .Result property
- for more info about this topic check https://msdn.microsoft.com/en-us/magazine/jj991977.aspx?f=255&MSPPError=-2147217396
- note: it is important that all devs understand why this is needed and that future code always uses ConfigureAwait(false)

Added .ConfigureAwait(false) to each await

---

README.md

Also updated `browser` instances from uppercase as they are instance methods, not static methods

Fix SetViewportAsync instances in Readme

---

lib/PuppeteerSharp/CDPSession.cs
lib/PuppeteerSharp/Connection.cs
lib/PuppeteerSharp/IConnection.cs

By doing this we keep the abstraction and the SendAsync methods internal.

Explicit IConnection implementation

---

lib/PuppeteerSharp.DevicesFetcher/DevicePayload.cs
lib/PuppeteerSharp.DevicesFetcher/Models.cs
lib/PuppeteerSharp.DevicesFetcher/OutputDevice.cs
lib/PuppeteerSharp.DevicesFetcher/Program.cs
lib/PuppeteerSharp.DevicesFetcher/PuppeteerSharp.DevicesFetcher.csproj
lib/PuppeteerSharp.DevicesFetcher/ViewportPayload.cs
lib/PuppeteerSharp.sln
lib/PuppeteerSharp/Mobile/DeviceDescriptorName.cs
lib/PuppeteerSharp/Mobile/DeviceDescriptors.cs

added generation of DeviceDescriptors.cs

---

lib/PuppeteerSharp.Tests/FrameTests/WaitForSelectorTests.cs
lib/PuppeteerSharp/Frame.cs

Improve waiting for selector to be hidden error message

---

docfx_project/index.md

- some of the examples were generate a "not a function" error. 
- docs made it look like `Browser` class has a static `NewPageAsync()` method. 
- could not find a `SetViewPort()` method. Looks like the correct method is `SetViewPortAsync()`

Clean up the main examples page

---

lib/PuppeteerSharp/Messaging/PageCaptureScreenshotResponse.cs
lib/PuppeteerSharp/Messaging/PageGetLayoutMetricsResponse.cs
lib/PuppeteerSharp/Page.cs
lib/PuppeteerSharp/ScreenshotOptions.cs

`PerformScreenshot` can make up to 5 WebSocket calls before performing the screenshot:
* Target.activateTarget
* Page.getLayoutMetrics 
* Page.getLayoutMetrics
* Emulation.setDeviceMetricsOverride
* Emulation.setDefaultBackgroundColorOverride
Then it calls `Page.captureScreenshot` and then it might need to call `Emulation.setDefaultBackgroundColorOverride` and `SetViewportAsync`.
This hurt the performance when trying to perform screenshots in "burst mode".
With "burst mode" I mean taking a series of screenshots to the same page during a certain period of time. 
With this new `BurstMode` we would perform those first five calls only on the first screenshot. Then we would call only `Page.captureScreenshot`. This will make this burst process at least 2.5x times faster.
After screenshots are …

Introducing Burst mode

---

lib/PuppeteerSharp.Tests/BrowserTests/TargetTests.cs
lib/PuppeteerSharp/Browser.cs
lib/PuppeteerSharp/Page.cs

closes #677 
We already have a WebSocket factory, so we are good there. There is another test in that commit but it's for Puppeteer-web.

New Browser.Target property

---

lib/PuppeteerSharp.Tests/ElementHandleTests/BoundingBoxTests.cs
lib/PuppeteerSharp.Tests/ElementHandleTests/BoxModelTests.cs
lib/PuppeteerSharp.Tests/ElementHandleTests/ContentFrameTests.cs
lib/PuppeteerSharp.Tests/FrameTests/EvaluateTests.cs
lib/PuppeteerSharp.Tests/FrameTests/ExecutionContextTests.cs
lib/PuppeteerSharp.Tests/FrameTests/FrameManagementTests.cs
lib/PuppeteerSharp.Tests/FrameTests/GoToTests.cs
lib/PuppeteerSharp.Tests/FrameTests/WaitForNavigationTests.cs
lib/PuppeteerSharp.Tests/FrameTests/WaitForSelectorTests.cs
lib/PuppeteerSharp.Tests/FrameTests/WaitForXPathTests.cs
lib/PuppeteerSharp.Tests/InputTests/InputTests.cs
lib/PuppeteerSharp.Tests/PageExtensions.cs
lib/PuppeteerSharp.Tests/PageTests/CookiesTests.cs
lib/PuppeteerSharp.Tests/PageTests/EvaluateTests.cs
lib/PuppeteerSharp.Tests/PageTests/Events/RequestTests.cs
lib/PuppeteerSharp.Tests/PageTests/ExposeFunctionTests.cs
lib/PuppeteerSharp.Tests/PuppeteerTests/IgnoreHttpsErrorsTests.cs
lib/PuppeteerSharp/Browser.cs
lib/PuppeteerSharp/ElementHandle.cs
lib/PuppeteerSharp/Frame.cs
lib/PuppeteerSharp/FrameManager.cs
lib/PuppeteerSharp/Helpers/MultiMap.cs
lib/PuppeteerSharp/NetworkManager.cs
lib/PuppeteerSharp/Page.cs
lib/PuppeteerSharp/TargetType.cs

* Now the Frames Dictionary is a ConcurrentDictionary. That made several tests to fail because the order of the items in the ConcurrentDictionary is not guaranteed. I had to code some helper methods on the tests, such as `FirstChildFrame();` to help us find test frames.
* Many Dictionaries were changed to ConcurrentDictionary.
* In some scenarios (a.k.a. #717) async events caused messages coming to be processed before the Frame was created. That's why, where we were doing things like 
```cs
_frameManager.Frames[nodeInfo.Node.FrameId]
``` 
I replaced it to 
```cs
await _frameManager.GetFrameAsync(nodeInfo.Node.FrameId);
``` 
In order to get a Task if the Frame has not been created yet.
closes #717

Concurrency improvements

---

lib/PuppeteerSharp.Tests/BrowserTests/Events/DisconnectedTests.cs
lib/PuppeteerSharp.Tests/PageTests/CloseTests.cs
lib/PuppeteerSharp/Browser.cs
lib/PuppeteerSharp/CDPSession.cs
lib/PuppeteerSharp/Connection.cs
lib/PuppeteerSharp/FrameManager.cs
lib/PuppeteerSharp/IConnection.cs
lib/PuppeteerSharp/NavigatorWatcher.cs
lib/PuppeteerSharp/NetworkManager.cs
lib/PuppeteerSharp/Page.cs
lib/PuppeteerSharp/PageCoverage/CSSCoverage.cs
lib/PuppeteerSharp/PageCoverage/JSCoverage.cs
lib/PuppeteerSharp/TargetClosedException.cs
lib/PuppeteerSharp/Tracing.cs
lib/PuppeteerSharp/Transport/IConnectionTransport.cs
lib/PuppeteerSharp/Transport/TransportClosedEventArgs.cs
lib/PuppeteerSharp/Transport/WebSocketTransport.cs
lib/PuppeteerSharp/Worker.cs

If we fail to process a message coming from chromium we can't just fail trusting that the user will catch that exception, because that call won't not part of the call stack coming from the user but from the WebSocket listener. This was causing the [unrecoverable exceptions](https://github.com/kblok/puppeteer-sharp/issues/717).
In order to fix this, we are going to close the `IConnection` (`CDPSession` or `Connection`) if we fail to process a message. We will add that exception as a `CloseReason` to the `IConnection` and also to the `TargetClosedException` in order to help us and the user to have more information about the problem we might have.
closes #752

Improve internal exception handling

---

lib/PuppeteerSharp/FrameManager.cs
lib/PuppeteerSharp/NavigatorWatcher.cs

In a scenario where a session is kept open for a pro-longed period with multiple navigations, then the event handlers can be kept in memory causing a prolonged memory leak.
This PR wraps the `NavigationManager` in a `using` statement and cleans up the event handlers on `Dispose`

Fixed event handler leak

---

lib/PuppeteerSharp/ElementHandle.cs

By returning null instead of false we prevent unnecessarily fails trying to case bool to string.

Fix ScrollIntoViewIfNeededAsync script

---

lib/PuppeteerSharp/Page.cs

This would fix this error we get some times https://ci.appveyor.com/project/kblok/puppeteer-sharp/builds/21196351/job/g0o4p4hvl5e04grn#L273

CloseAsync should wait for the target to be closed

---

demos/PuppeteerSharpPdfDemo/PuppeteerSharpPdfDemo-Local.csproj
demos/PuppeteerSharpPdfDemo/PuppeteerSharpPdfDemo.csproj
lib/PuppeteerSharp/CDPSession.cs
lib/PuppeteerSharp/Connection.cs
lib/PuppeteerSharp/ElementHandle.cs
lib/PuppeteerSharp/EvaluationFailedException.cs
lib/PuppeteerSharp/ExecutionContext.cs
lib/PuppeteerSharp/Helpers/FlexibleStringEnumConverter.cs
lib/PuppeteerSharp/Helpers/RemoteObjectHelper.cs
lib/PuppeteerSharp/IConnection.cs
lib/PuppeteerSharp/JSHandle.cs
lib/PuppeteerSharp/MessageException.cs
lib/PuppeteerSharp/Messaging/EvaluateHandleResponse.cs
lib/PuppeteerSharp/Messaging/LogEntryAddedResponse.cs
lib/PuppeteerSharp/Messaging/MessageKeys.cs
lib/PuppeteerSharp/Messaging/PageCaptureScreenshotRequest.cs
lib/PuppeteerSharp/Messaging/PageConsoleResponse.cs
lib/PuppeteerSharp/Messaging/RemoteObject.cs
lib/PuppeteerSharp/Messaging/RemoteObjectSubtype.cs
lib/PuppeteerSharp/Messaging/RemoteObjectType.cs
lib/PuppeteerSharp/Messaging/RuntimeCallFunctionOnResponse.cs
lib/PuppeteerSharp/Messaging/RuntimeGetPropertiesResponse.cs
lib/PuppeteerSharp/Messaging/RuntimeQueryObjectsResponse.cs
lib/PuppeteerSharp/Page.cs
lib/PuppeteerSharp/Worker.cs

We don't need no dynamics

---

lib/PuppeteerSharp/BrowserFetcher.cs

Fixes a minor typo along with a few white-lines for readability.

Fix minor typo in XML docs

---

lib/PuppeteerSharp.Tests/LaunchOptionsTests.cs
lib/PuppeteerSharp/LaunchOptions.cs

The comments say `the headless option will be set false`:
https://github.com/kblok/puppeteer-sharp/blob/82ab1e0807e9a6ce1f5480379190f87a07819754/lib/PuppeteerSharp/LaunchOptions.cs#L62-L65
However, the headless option was not actually set to `false`.

Set headless option to false when Devtools are enabled

---

lib/PuppeteerSharp/Page.cs

`Target.CloseTask` was being being completed before we set `IsClosed = true;`
It will help us with this race https://ci.appveyor.com/project/kblok/puppeteer-sharp/builds/21332785/job/5wrbvkgq0a351en0#L230

Fix Race conditions on Page.CloseAsync

---

lib/PuppeteerSharp/ChromiumProcess.cs
lib/PuppeteerSharp/FrameManager.cs
lib/PuppeteerSharp/Helpers/TaskHelper.cs

Based on this https://github.com/davidfowl/AspNetCoreDiagnosticScenarios/blob/master/AsyncGuidance.md#always-create-taskcompletionsourcet-with-taskcreationoptionsruncontinuationsasynchronously
We are removing Task.Delay used for cancellations

Remove Task.Delays

---

lib/PuppeteerSharp/CDPSession.cs
lib/PuppeteerSharp/Connection.cs
lib/PuppeteerSharp/PageCoverage/CSSCoverage.cs
lib/PuppeteerSharp/PageCoverage/JSCoverage.cs

We need to dispatch connections events as soon as possible. This changed brought many racing conditions.

Connection messages should be dispatched synchronously

---

lib/PuppeteerSharp/Frame.cs

Load LifecycleWatcher before injecting the HTML.
This might have caused this hang https://ci.appveyor.com/project/kblok/puppeteer-sharp/builds/21440654/job/g6ev4p72raqk64k8/tests

SetContentAsync improvements

---

lib/PuppeteerSharp.Tests/PageTests/EvaluateTests.cs
lib/PuppeteerSharp/Browser.cs
lib/PuppeteerSharp/CDPSession.cs
lib/PuppeteerSharp/Connection.cs
lib/PuppeteerSharp/ElementHandle.cs
lib/PuppeteerSharp/FrameManager.cs
lib/PuppeteerSharp/Helpers/Json/FlexibleStringEnumConverter.cs
lib/PuppeteerSharp/Helpers/Json/HttpMethodConverter.cs
lib/PuppeteerSharp/Helpers/Json/JSHandleMethodConverter.cs
lib/PuppeteerSharp/Helpers/Json/JTokenExtensions.cs
lib/PuppeteerSharp/Helpers/Json/JsonHelper.cs
lib/PuppeteerSharp/Helpers/RemoteObjectHelper.cs
lib/PuppeteerSharp/JSHandle.cs
lib/PuppeteerSharp/Messaging/BindingCalledResponse.cs
lib/PuppeteerSharp/Messaging/RemoteObjectSubtype.cs
lib/PuppeteerSharp/Messaging/RemoteObjectType.cs
lib/PuppeteerSharp/NetworkManager.cs
lib/PuppeteerSharp/Page.cs
lib/PuppeteerSharp/PageCoverage/CSSCoverage.cs
lib/PuppeteerSharp/PageCoverage/JSCoverage.cs
lib/PuppeteerSharp/Payload.cs
lib/PuppeteerSharp/PuppeteerSharp.csproj
lib/PuppeteerSharp/ResourceType.cs
lib/PuppeteerSharp/Response.cs
lib/PuppeteerSharp/TargetType.cs
lib/PuppeteerSharp/Worker.cs

We are not getting a `Converting circular structure to JSON` when we try to serialize a JSHandle, and I also consider that's not the best way to infer that, we can do better in C#
So I created a JSHandlerCoverter which will throw that exception is someone is trying to send a JSHandle.

Warn on nested js handle

---

lib/PuppeteerSharp/Helpers/TaskHelper.cs

If `CancellationTokenSource`'s aren't disposed, then there timers are left on the timer queue. Internally, the timer queue runs through each timer to determine whether or not to fire the said time, as it's implemented as a linked list. So this not only clears up the timer resources, but makes the other times more "accurate" as there is less work to do.

Always dispose cancellation token sources

---

lib/PuppeteerSharp/Helpers/MultiMap.cs
lib/PuppeteerSharp/NetworkManager.cs

_Alternative To [This PR](https://github.com/kblok/puppeteer-sharp/pull/925). Decided that I don't know enough about how chrome works to be fiddling with there and i'm running out of in-work time. So fixing the exception by using `TryAdd` instead as well as fixing the other small things. Dictionary accesses are otherwise left as is. Duplicated the PR description for future reference._
Recently we have been seeing the following under load: 
```
ex_msg: The key already existed in the dictionary. | stacktrace: System.ArgumentException: The key already existed in the dictionary.
at System.Collections.Concurrent.ConcurrentDictionary`2.System.Collections.Generic.IDictionary<TKey,TValue>.Add(TKey key, TValue value)
at PuppeteerSharp.NetworkManager.<OnRequestWillBeSentAsync>d__44.MoveNext()
--- …
```

Bug (NetworkManger): The key already existed in the dictionary

---

appveyor-fullframework.yml
lib/PuppeteerSharp.AspNetFramework/AspNetWebSocketTransport.cs
lib/PuppeteerSharp.Tests/PuppeteerSharp.Tests.csproj
lib/PuppeteerSharp.Tests/PuppeteerTests/PuppeteerConnectTests.cs
lib/PuppeteerSharp.Tests/PuppeteerTests/PuppeteerLaunchTests.cs
lib/PuppeteerSharp/ConnectOptions.cs
lib/PuppeteerSharp/Connection.cs
lib/PuppeteerSharp/IConnectionOptions.cs
lib/PuppeteerSharp/LaunchOptions.cs
lib/PuppeteerSharp/Transport/IConnectionTransport.cs
lib/PuppeteerSharp/Transport/TransportFactory.cs
lib/PuppeteerSharp/Transport/TransportTaskScheduler.cs
lib/PuppeteerSharp/Transport/WebSocketFactory.cs
lib/PuppeteerSharp/Transport/WebSocketTransport.cs

While testing the latest commits I no longer experienced hangs, but the debugger did break on some exceptions that are not really necessary in the `WebSocketTransport`. This pull request puts some additional belts and braces around the starting, stopping and cancelling of read operations.

WebSocketTransport initialization, shutdown and extension

---

lib/PuppeteerSharp/TimeoutSettings.cs

It looks like the default timeout was changed with this commit: https://github.com/kblok/puppeteer-sharp/commit/2e59b1eef049836b54767f09c72d345ac0f84227
I figured this was a typo because the comments seem to imply that it should still be 30 seconds. 
This is my first pull request, so let me know if I did something wrong.

Change default timeout back to 30000ms

---

lib/PuppeteerSharp.Tests/test.runsettings
lib/PuppeteerSharp/BrowserFetcher.cs

Fixes https://github.com/kblok/puppeteer-sharp/issues/1050
As the code path is now called from a local function, the static fields of LinuxPermissionsSetter are not loaded by the .net until the local function is called. What was happening, is when ```DownloadAsync``` is invoked, it loads the ```LinuxPermissionsSetter``` class, thus loading the static field ```ExecutableFilePermissions``` which then loads the ```FileAccessPermissions``` enum from the Posix lib.

Isolating the Posix code so it doesn't get loaded in net471.

---

lib/PuppeteerSharp/Media/PaperFormat.cs

- Make a public constructor for `PaperFormat`
- Make `Height` and `Width` readonly properties.
closes #1061

Paper Format Accessibility Changes

---

lib/PuppeteerSharp.Tests/ChromiumSpecificTests/PageTests.cs
lib/PuppeteerSharp.Tests/NetworkTests/ResponseTextTests.cs
lib/PuppeteerSharp.Tests/PuppeteerTests/PuppeteerLaunchTests.cs

We made some minor changes to our tests so they run with Microsoft Edge:
* Intervention header has the URL https://to-be-replaced.invalid/feature/5718547946799104 instead of https://www.chromestatus.com/feature/5718547946799104. We are changing the "Contains" part
* We are removing some new lines and using Trim to compare TextAsync
* Edge launches two pages with default arguments. We are going to check that  the pages array is not empty.

Microsoft Edge Friendly tests

---

lib/PuppeteerSharp.Tests/ExecutionContextTests/QueryObjectsTests.cs
lib/PuppeteerSharp.Tests/PageTests/Cookies/CookiesTests.cs

Add cookie tests

---

lib/PuppeteerSharp.Tests/FrameTests/WaitForFunctionTests.cs
lib/PuppeteerSharp.Tests/PageTests/EvaluateOnNewDocumentTests.cs
lib/PuppeteerSharp.Tests/PageTests/ExposeFunctionTests.cs
lib/PuppeteerSharp/Page.cs

We are spliting EvaluateOnNewDocumentAsync into two methods. EvaluateFunctionOnNewDocumentAsync and EvaluateExpresionOnNewDocumentAsync.
closes #1183

Evaluate expressions on new document support

---

lib/PuppeteerSharp/Frame.cs
lib/PuppeteerSharp/Page.cs

Clarify frame/page.GotAsync()'s handling of HTTP error statuses

---

lib/PuppeteerSharp.Tests/FrameTests/WaitForFunctionTests.cs

We are missing this test from Puppeteer.

Add missing test

---

lib/PuppeteerSharp/Page.cs
lib/PuppeteerSharp/Response.cs

Add response example

---

demos/PuppeteerSharpPdfDemo/PuppeteerSharpPdfDemo.csproj

Pretty self-explanatory. I'm using VS2019 and .NET Core 3.1 for my project and needed to ensure puppeteersharp would work with it.

Updated to work with VS2019 and .NET Core 3.1

---

lib/PuppeteerSharp.Tests/Issues/Issue1447.cs
lib/PuppeteerSharp/FrameManager.cs
lib/PuppeteerSharp/Helpers/AsyncDictionaryHelper.cs
lib/PuppeteerSharp/NetworkManager.cs

Optional frame in requests

---

lib/PuppeteerSharp/ChromiumProcess.cs

Don’t disable BlinkGenPropertyTrees anymore

---

lib/PuppeteerSharp/NetworkManager.cs

Adding the support of null Frame Ids to the 'OnRequestAsync' method, stopping "Value cannot be null" exceptions

Updating OnRequestAsync in NetworkManager

---

lib/PuppeteerSharp.Tests/PageTests/GoBackTests.cs
lib/PuppeteerSharp/Page.cs

This fixes a negative index error that can be reproduced by the new test in this PR: `GoBackTests.GoBackToAboutBlank`.
Exception being thrown was:
```
System.ArgumentOutOfRangeException
Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
at System.Collections.Generic.List`1.get_Item(Int32 index)
at PuppeteerSharp.Page.<GoAsync>d__224.MoveNext() in D:\dev\github\jpeirson\puppeteer-sharp\lib\PuppeteerSharp\Page.cs:line 1878
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at …
```

Fixed negative index error

---

lib/PuppeteerSharp.ruleset
lib/PuppeteerSharp/LifecycleWatcher.cs

When I had a look at the class, i saw that it did not need a finalizer. LifecycleWatcher does not contain any unmanaged members. See [implementing dispose](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose) for reference: "It is possible for a base class to only reference managed objects, and implement the dispose pattern. In these cases, a finalizer is unnecessary. A finalizer is only required if you directly reference unmanaged resources."
In a second commit I removed the second dispose(bool) method and the finalizer.
I am uncertain about the SuppressMessage for CA2213:DisposableFieldsShouldBeDisposed in line 36 of the same file. The _terminationCancellationToken is only canceled in our dispose-method but never actually disposed. Can you elaborate …

Set CA1816 to error

---

lib/PuppeteerSharp/CDPSession.cs

I assume this is redundant? but technically it could be breaking behavior change

remove ToObject<ConnectionResponseParams

---

lib/PuppeteerSharp.Tests/NetworkTests/PageAuthenticateTests.cs
lib/PuppeteerSharp/NetworkManager.cs

See https://github.com/puppeteer/puppeteer/pull/6962

Don't disable cache for auth challenge

---

appveyor-linux.yml

```
$ export framework=netcoreapp2.2
```
```
$ dotnet build ./lib/PuppeteerSharp.TestServer/PuppeteerSharp.TestServer.csproj
Microsoft (R) Build Engine version 16.7.2+b60ddb6f4 for .NET
Copyright (C) Microsoft Corporation. All rights reserved.
Determining projects to restore...
Restored /home/androbin/data/git/puppeteer-sharp/lib/PuppeteerSharp.TestServer/PuppeteerSharp.TestServer.csproj (in 365 ms).
PuppeteerSharp.TestServer -> /home/androbin/data/git/puppeteer-sharp/lib/PuppeteerSharp.TestServer/bin/Debug/netcoreapp2.2/PuppeteerSharp.TestServer.dll
/usr/share/dotnet/sdk/3.1.407/Microsoft.Common.CurrentVersion.targets(1177,5): error MSB3644: The reference assemblies for .NETFramework,Version=v4.8 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this …
```

Add missing `-f $framework`

---

lib/PuppeteerSharp/PuppeteerSharp.csproj

This adds a license to the nuget package.
The most visible places are in the nuget package manager and on https://www.nuget.org/packages/PuppeteerSharp.
this fixes #1609

Add license to nuget package

---

docfx_project/index.md

I really missed that link ;)
additionally: the link for the slack channel doesn't work anymore. it says it is expired.

Added GitHub-Repo to Useful links

---

lib/PuppeteerSharp/Frame.cs

The upstream counterpart for reference:
https://github.com/puppeteer/puppeteer/blob/b349c91e7df76630b7411d6645e649945c4609bd/src/common/FrameManager.ts#L593
See #1670 for context

Avoid leaking reference to partially constructed Frame instance

---

lib/PuppeteerSharp/Page.cs

I have prepared a test project to demonstrate the errors that can occur with the current version: [Test.zip](https://github.com/hardkoded/puppeteer-sharp/files/6289319/Test.zip)
- `Object reference not set to an instance of an object.`
- `Index was outside the bounds of the array.`
- `Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.`
- `TryGetValue` returns wrong value
Fixes #1681

Fix Page._workers concurrency issues

---

lib/PuppeteerSharp/DOMWorld.cs
lib/PuppeteerSharp/Frame.cs

I have prepared a test project to demonstrate the errors that can occur with the current version:  [Test.zip](https://github.com/hardkoded/puppeteer-sharp/files/6289374/Test.zip)
- `Index was out of range. Must be non-negative and less than the size of the collection. Parameter name: index`
- `Index was outside the bounds of the array.`
- `Contains` returns wrong value
See #1680

Fix WaitTasks concurrency issues

---

lib/PuppeteerSharp.TestServer/SimpleServer.cs
lib/PuppeteerSharp/Messaging/FetchRequestPausedResponse.cs
lib/PuppeteerSharp/NetworkManager.cs

See upstream: https://github.com/puppeteer/puppeteer/pull/7060
Fixes #1185

fix(requestinterception): fix font loading issue

---

lib/PuppeteerSharp/BrowserFetcher.cs

Fixes `PuppeteerSharp.Tests.LauncherTests.PuppeteerLaunchTests.ShouldWorkWithNoDefaultArguments` on Linux
See #1643

`chmod +x crashpad_handler`

---

lib/PuppeteerSharp/Page.cs

closes #1768. 
Added example usage of EvaluateExpressionAsync involving scraping hyperlink info for a given web page.
Added href seealso pointing to the JToken documentation on the Newtonsoft JSON website.

Documentation Update for EvaluateExpressionAsync() with Example

---

docfx_project/examples/index.md

closes #1590 
Added example of getting the inner text of an element.
Updated deprecated DownloadAsync() overload usage to the newer recommended usage.

Issue 1590 - Docfx code examples update

---

demos/PuppeteerSharpPdfDemo/Program.cs
demos/PuppeteerSharpPdfDemo/PuppeteerSharpPdfDemo-Local.csproj
docfx_project/api/index.md
docfx_project/examples/ChromeExtension.md
docfx_project/examples/Page.ScreenshotAsync.md
docfx_project/examples/ReuseChrome.md
docfx_project/examples/index.md
lib/PuppeteerSharp.DevicesFetcher/Program.cs
lib/PuppeteerSharp.Tests/FixturesTests/FixturesTests.cs
lib/PuppeteerSharp.Tests/LauncherTests/BrowserFetcherTests.cs
lib/PuppeteerSharp.Tests/PageTests/PdfTests.cs
lib/PuppeteerSharp.Tests/PuppeteerLoaderFixture.cs
lib/PuppeteerSharp.Tests/ScreenshotTests/PageScreenshotTests.cs
lib/PuppeteerSharp.ruleset
lib/PuppeteerSharp/Browser.cs
lib/PuppeteerSharp/BrowserFetcher.cs
lib/PuppeteerSharp/Connection.cs
lib/PuppeteerSharp/DOMWorld.cs
lib/PuppeteerSharp/Helpers/TaskQueue.cs
lib/PuppeteerSharp/Launcher.cs
lib/PuppeteerSharp/Page.cs
lib/PuppeteerSharp/Transport/WebSocketTransport.cs
lib/PuppeteerSharp/WaitTask.cs
samples/PupppeterSharpAspNetFrameworkSample/PupppeterSharpAspNetFrameworkSample/Services/BrowserClient.cs

closes #1423 
For classes with disposable members, made those classes implement IDisposable, using the recommended Dispose() methods.
This created a ripple effect where the newly disposable classes needed to be disposed of wherever used.
Updated documentation, examples, sample code, and demos where `BrowserFetcher` is used and could be disposed.
@kblok sorry, this one has got a lot of changes. Documentation aside, the rest was necessary to satisfy the analyzer.

Set CA1001 to "Error" and resolved issues

---

lib/PuppeteerSharp.Tests/PuppeteerSharp.Tests.csproj
lib/PuppeteerSharp/PuppeteerSharp.csproj

Referencing PuppeteerSharp pulls lots of packages transitively, and it looks like these come mostly from the System.Net.Http package, which apparently is not needed in order to build PuppeteerSharp, but only the Tests project.
Removing this dependency from the published NuGet package would make things simpler, so I've moved the reference to the test project.

Simplify NuGet dependencies

---

lib/PuppeteerSharp.Tests/RequestInterceptionTests/RequestRespondTests.cs
lib/PuppeteerSharp/Request.cs
lib/PuppeteerSharp/ResponseData.cs

- Without breaking the current API this change allows for arrays of values
(Anything that implements ICollection and can be iterated over).
- The Headers with null values will be ignored, previously an exception
would have occurred with the Value.ToString() call so this is unlikely
a breaking change in behaviour.
- New test case added
Resolves https://github.com/hardkoded/puppeteer-sharp/issues/1542
Replaces #1607

Allow ResponseData.Headers to support multiple values for the same key

---

lib/PuppeteerSharp/Page.cs

Currently it's internal and only accessible via the Test project

Make Page.EmulateCPUThrottlingAsync public

---

lib/PuppeteerSharp.Tests/Issues/Issue1878.cs
lib/PuppeteerSharp/Page.cs

This fixes #1878 .
Note that the `TaskQueue` is indeed already disposed as expected when the `Browser` [is disposed](https://github.com/hardkoded/puppeteer-sharp/blob/master/lib/PuppeteerSharp/Browser.cs#L554-L557).

Fixed issue with disposing shared screenshot task queue

---

lib/PuppeteerSharp/States/DisposedState.cs

closes #1870
Removed method which was not called anymore. Added override method which handles the StateMaanger.Exited use case explicitly.

Fix some UnobservedTaskException errors

---

lib/PuppeteerSharp/Browser.cs

Switch browser contexts from Dictionary to ConcurrentDictionary due to rare race condition throwing non-concurrent error

Switch browser contexts from Dictionary to ConcurrentDictionary

---

lib/PuppeteerSharp.Tests/PageTests/WaitForNetworkIdleTests.cs
lib/PuppeteerSharp/NetworkManager.cs
lib/PuppeteerSharp/Page.cs
lib/PuppeteerSharp/WaitForNetworkIdleOptions.cs

Adds new `Page.WaitForNetworkIdleAsync` method ported from [page.waitForNetworkIdle](https://github.com/puppeteer/puppeteer/blob/8ff9d598bf4afd10cbc61ca9579b7bd38edb8026/src/common/Page.ts#L1942)
The current method signature looks like the following:
```c#
public async Task WaitForNetworkIdleAsync(int? timeout = null, int idleTime = 500)
```
The other `WaitFor` methods use `WaitForOptions` which only has a `Timeout` property. Happy to add a new `WaitForNetworkIdleOptions` class if required, though seems overkill for two optional params.
I've expanded the `ShouldWorkWithNoTimeout` test a little, I would have liked to see the responses validated to confirm that not only did the requests complete, that the expected number completed. So I've done that in `ShouldWorkWithNoTimeout`
Tests …

Add Page.WaitForNetworkIdleAsync

---

lib/PuppeteerSharp/PuppeteerSharp.csproj

Updates Microsoft.AspNetCore.WebUtilities" to version 2.2.0 to solve this issue: https://github.com/hardkoded/puppeteer-sharp/issues/1927

chore: update Microsoft.AspNetCore.WebUtilities to 2.2.0

---

lib/PuppeteerSharp.ruleset
lib/PuppeteerSharp/ChromiumLauncher.cs
lib/PuppeteerSharp/Frame.cs
lib/PuppeteerSharp/FrameManager.cs
lib/PuppeteerSharp/FrameTree.cs
lib/PuppeteerSharp/Launcher.cs
lib/PuppeteerSharp/LifecycleWatcher.cs
lib/PuppeteerSharp/MessageTask.cs
lib/PuppeteerSharp/Target.cs

The intention of this change is to enable the analyzer rule [SA1124: DoNotUseRegions](https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1124.md) as described in the issue #1395.
Please let me know if there is anything I've missed while raising the PR.
There are some additional regions in the tests, should these be removed as well?

Configure SA1124 action as error, remove regions

---

lib/PuppeteerSharp/ElementHandle.cs
lib/PuppeteerSharp/Messaging/RemoteObject.cs

- Add RemoteObject.ClassName and RemoteObject.Description
- Add ElementHandle.DebuggerDisplay attribute to use newly added ClassName and Description
Doesn't change any runtime functionality, just improves the debugging output
Viewing an `ElementHandle` in the debugger will now show for example `HtmlButtonElement@button`.

ElementHandle - Improve Debugger Display

---

lib/PuppeteerSharp/ElementHandle.cs

So that the user can choose a variable point where to press in the button
https://github.com/hardkoded/puppeteer-sharp/pull/1985

ElementHandle.ScrollIntoViewIfNeededAsync public

---

lib/PuppeteerSharp/ElementHandle.cs

So that the user can choose a variable point where to press in the button
https://github.com/hardkoded/puppeteer-sharp/pull/1984
I don't want to open a ticket now. Wouldn't it make sense to write your own function so that it is variable for the user and not fixed in the middle? Or Optional variables in the ClickAsync function? If you want it, I'll be happy to open an extra ticket for it.

Make ElementHandle.ClickablePointAsync public

---

lib/PuppeteerSharp/BrowserFetcher.cs

Fixes crash on launch on Linux:
```
[FATAL:double_fork_and_exec.cc(131)] execv .local-chromium/Linux-970485/chrome-linux/chrome_crashpad_handler: Permission denied (13)
```
See #1774

Update list of paths with ExecutableFilePermissions

---

lib/PuppeteerSharp.Tests/JSHandleTests/ClickTests.cs
lib/PuppeteerSharp.Tests/JSHandleTests/ClickablePointTests.cs
lib/PuppeteerSharp.Tests/TestUtils.cs
lib/PuppeteerSharp/ElementHandle.cs
lib/PuppeteerSharp/IElementHandle.cs
lib/PuppeteerSharp/Input/ClickOptions.cs
lib/PuppeteerSharp/Offset.cs

- Add new Offset struct and replace BoxModelPoint usage for ClickablePointAsync
- Add new Test case based on JSHandle.click should work
Puppeteer supports passing an offset via ClickOptions see https://pptr.dev/api/puppeteer.clickoptions

Add ClickOptions.Offset (Optional)

---

lib/PuppeteerSharp/ExecutionContext.cs
lib/PuppeteerSharp/Helpers/RemoteObjectHelper.cs
lib/PuppeteerSharp/IJSHandle.cs
lib/PuppeteerSharp/JSHandle.cs
lib/PuppeteerSharp/PuppeteerHandleExtensions.cs

Motivation for this change is to allow for [PuppeteerSharp.Dom](https://github.com/ChromiumDotNet/PuppeteerSharp.Dom) to pass it's custom `DOM` object instances as `IJSHandle` args to EvaluateFunctionAsync/EvaluateFunctionHandleAsync. 
Currently you have to cast to `JSHandle`. e.g. https://github.com/ChromiumDotNet/PuppeteerSharp.Dom/blob/b1f862ee24dcc2a025dfea43d198597dbdedf17c/PuppeteerSharp.Dom.Tests/ElementHandleTests/BoundingBoxTests.cs#L61

Allow for passing IJSHandle as argument to EvaluateFunctionAsync/EvaluateFunctionHandleAsync

---

lib/PuppeteerSharp.Tests/PageTests/BrowserContextOverridePermissionsTests.cs
lib/PuppeteerSharp/OverridePermission.cs

I had to remove the `Push` enum and rename the  `Clipboard` ones.
closes #2052

[BREAKING] Update permissions overrides

---

lib/PuppeteerSharp/FrameManager.cs

There are two ways Frames are added to the ConcurrentDictionary, only the frames created in OnFrameNavigatedAsync will resolve the Task created by GetItemAsync. The frames created in OnFrameAttached are added to the ConcurrentDictionary directly and never resolve any pending Tasks.
`AsyncDictionaryHelper.AddItem` is now used to add all frames to the dictionary.

FrameManager - Add new frames via AsyncDictionaryHelper.AddItem

---

.github/workflows/PushNugetPackageToIntNugetOrg.yml
.github/workflows/PushNugetPackageToNugetOrg.yml
.github/workflows/dotnet.yml
lib/PuppeteerSharp.TestServer/PuppeteerSharp.TestServer.csproj
lib/PuppeteerSharp.Tests.DumpIO/PuppeteerSharp.Tests.DumpIO.csproj
lib/PuppeteerSharp.Tests/PuppeteerSharp.Tests.csproj
lib/PuppeteerSharp.Xunit/PuppeteerSharp.Xunit.csproj
lib/PuppeteerSharp/FrameManager.cs
lib/PuppeteerSharp/PuppeteerSharp.csproj

Updated api keys
There are two steps that I wont be able to prepare... btw. not able without authorization at nuget.org to change your package.
- Obtain an api key from nuget.org and add it using the key "NUGET_API_KEY" to your secrets to enable pushing built packages to nuget.org. That will get triggerd on pushing to "release-*" branches.
- Obtain an api key from https://int.nugettest.org/ and add it using the key "NUGET_INT_API_KEY" to your secrets to enable pushing built packages to int.nugettest.org. That will get triggered on pushing to "master" branch and will run online similar checks on the package like need to be satisfied publishing using nuget.org.

Automate nuget org push

---

lib/PuppeteerSharp.ruleset
lib/PuppeteerSharp/CDPSession.cs
lib/PuppeteerSharp/Connection.cs
lib/PuppeteerSharp/DOMWorld.cs
lib/PuppeteerSharp/Page.cs

[Roslyn Aanalyzers](https://github.com/dotnet/roslyn-analyzers) reports [CA1836: Prefer IsEmpty over Count when available](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1836).
E.g. [`ConcurrentDictionary.IsEmpty`](https://source.dot.net/#System.Collections.Concurrent/System/Collections/Concurrent/ConcurrentDictionary.cs,1479) has a lock-free fast path, whereas [`ConcurrentDictionary.Count`](https://source.dot.net/#System.Collections.Concurrent/System/Collections/Concurrent/ConcurrentDictionary.cs,1116) always acquires all locks.

Prefer IsEmpty over Count/Any

---

lib/PuppeteerSharp/States/DisposedState.cs

`await`'ing `null` `Task` throws a `NullReferenceException`.
See e.g. this [example](https://sharplab.io/#v2:EYLgxg9gTgpgtADwGwBYA0AXEUCuA7AHwAEAGAAiIEYBWAbgFgAoJogTjIDEIIAKASgbNGRJJ278yAXgB8ZPDgA2C2kA)
`DisposedState.EnterFromAsync` is, as far as I can tell, only invoked as a fire-and-forget from `State.Dispose`, so _currently_ this isn't a problem.
Instead I propose returning a completed `Task`.
`Task.CompletedTask` is a [cached `Task`](https://source.dot.net/#System.Private.CoreLib/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/Task.cs,1477), so there's no overhead in using that over returning `null`.
The rename of `timeSpan` to `timeout` is to match the parameter name in the overridden method `State.EnterFromAsync(LauncherBase p, State fromState, TimeSpan timeout)`

Return a `Task` instead of `null`

---

lib/PuppeteerSharp.Tests/PageTests/PageEventsPopupTests.cs

[`ShouldWorkWithFakeClickingTargetBlankAndReNoopener`](https://github.com/hardkoded/puppeteer-sharp/blob/c18812b66ae07e1c0ecda5af5573a2d12accad8f/lib/PuppeteerSharp.Tests/PageTests/PageEventsPopupTests.cs#L64-L80) and [`ShouldWorkWithFakeClickingTargetBlankAndRelNoopener`](https://github.com/hardkoded/puppeteer-sharp/blob/c18812b66ae07e1c0ecda5af5573a2d12accad8f/lib/PuppeteerSharp.Tests/PageTests/PageEventsPopupTests.cs#L82-L98) are identical.
The first one should use `rel=opener`
Cross-checked with [puppeteer source](https://github.com/puppeteer/puppeteer/blob/415da9230066e5b399f60963b639bfbafdc8ec57/test/src/page.spec.ts#L296-L346)

Fix duplicated test

---

lib/PuppeteerSharp/Helpers/TaskQueue.cs
lib/PuppeteerSharp/WaitTask.cs

When running tests with a debugger attached I found some places that weren't thread-safe.
1) Disposing `TaskQueue` twice would throw an `ObjectDisposedException` on `_semaphore.WaitAsync()` when a previous call to `DisposeAsyncCore` has already disposed the `_semaphore`.
2) Running `PageWaitForTests.ShouldWaitForAnXpath` makes two concurrent calls as shown below
| TaskA                | TaskB                          |
|----------------------|--------------------------------|
| `WaitTask.Dispose()` | `WaitTask.Cleanup()`           |
|                      | `_cts.IsCancellationRequested` |
| `_cts.Dispose()`     |                                |
|                      | `_cts.Cancel()` // throws `ObjectDisposedException`               |
When this race-condition is hit, …

Safer double disposal

---

lib/PuppeteerSharp.Tests/RequestInterceptionTests/SetRequestInterceptionTests.cs
lib/PuppeteerSharp.Tests/WaitTaskTests/FrameWaitForSelectorTests.cs

After reviewing `ContinueWith` usage in the tests there are a couple of cases which can be improved by changing to Assert.ThrowsAsync.

Test - Use Assert.ThrowsAsync for exceptions instead of ContinueWith

---

lib/PuppeteerSharp.Tests/PageTests/WaitForNetworkIdleTests.cs

When running `WaitForNetworkIdleTests.ShouldWork` in debug mode `ExecutionContext.ExecuteEvaluationAsync` throws this exception:
```
PuppeteerSharp.EvaluationFailedException: 'Evaluation failed: SyntaxError: Unexpected token ';''
```
The problem seemed to be that we didn't return a _function_, but an _expression_ `(async ...)();`
To align the two tests with other tests using `EvaluateFunctionAsync` I've changed them to return the async function directly.

Fix SyntaxError in `WaitForNetworkIdleTests.ShouldWork`

---

lib/PuppeteerSharp/Browser.cs

The `ScreenshotTaskQueue` is currently only disposed when `Dispose()` is called, doesn't appear to be disposed when `DisposeAsync` is called.

Browser - Dispose of ScreenshotTaskQueue when async dispose

---

lib/PuppeteerSharp/Helpers/TaskQueue.cs

The class is now **sealed** which means we can remove the `protected` methods

TaskQueue - Make class sealed and simplify Dispose

---

samples/complex-js-objects/Program.cs
samples/complex-js-objects/complex-js-objects.csproj
samples/get-all-links/Program.cs
samples/get-all-links/get-all-links.csproj
samples/reuse-downloaded-chrome/Program.cs
samples/reuse-downloaded-chrome/reuse-downloaded-chrome.csproj
samples/searching/Program.cs
samples/searching/searching.csproj

Updated PuppeteerSharp to 9.0.2 in the samples.
There is no constant called `BrowserFetcher.DefaultRevision` since version 7.0.0. Changed it to `BrowserFetcher.DefaultChromiumRevision`.
Fixed broken CSS selectors in samples. All samples working correctly now.

Update samples to use PuppeteerSharp v9.0.2

---

lib/PuppeteerSharp/Browser.cs
lib/PuppeteerSharp/Helpers/AsyncMessageQueue.cs
lib/PuppeteerSharp/Helpers/TempDirectory.cs
lib/PuppeteerSharp/Launcher.cs
lib/PuppeteerSharp/LifecycleWatcher.cs
lib/PuppeteerSharp/Page.cs
lib/PuppeteerSharp/WaitTask.cs

Found some more places related to disposing to rework.
I've split the changes into three separate commits to ease reviewing.

Rework some disposing

---

lib/PuppeteerSharp.Tests/AriaQueryHandlerTests/WaitForSelectorAriaTests.cs

I noticed that `element` was unused, so looked up the corresponding [puppeteer test](https://github.com/puppeteer/puppeteer/blob/823a9df4429480f597d45368e763fdb05d1e9210/test/src/ariaqueryhandler.spec.ts#L235-L243)
where `WaitForSelectorAsync` is called on `element` and not `page`.

Fix ShouldWorkForElementHandleWaitForSelector

---

lib/PuppeteerSharp/PuppeteerSharp.csproj

Included in #1640 but since 407dd6ffa4ac0e3caeaeef1859253b8b13eda34a it's not used anymore.

Remove unused dependency on SharpZipLib

---

lib/PuppeteerSharp/Page.cs

https://github.com/hardkoded/puppeteer-sharp/pull/705#discussion_r226365932 suggested to return `ResetBackgroundColorAndViewportAsync` directly to save an `await` when `_screenshotBurstModeOptions` is not set.
f18c3f19e9cc4dc661af64f6b1d4bf962f2fbc36 missed the `return`, so `ResetBackgroundColorAndViewportAsync` may not be complete when `await SetBurstModeOffAsync` completes.

Improve SetBurstModeOffAsync return statement

---

lib/PuppeteerSharp.Tests/PuppeteerLoaderFixture.cs

Removes some blocking calls around xunit initialization/disposal
Found on https://jimmybogard.com/integration-testing-with-xunit/#sharedfixturedesign
https://github.com/xunit/xunit/blob/1892224c60f8499b42ee1d8a521d65995ef32aea/src/xunit.execution/Sdk/Frameworks/Runners/XunitTestCollectionRunner.cs#L107-L121
https://github.com/xunit/xunit/blob/1892224c60f8499b42ee1d8a521d65995ef32aea/src/xunit.execution/Sdk/Frameworks/Runners/XunitTestCollectionRunner.cs#L56-L64

Use IAsyncLifetime for async initialization/disposal

---

lib/PuppeteerSharp.Tests/OOPIFTests/OOPIFTests.cs
lib/PuppeteerSharp/Frame.cs
lib/PuppeteerSharp/FrameManager.cs
lib/PuppeteerSharp/IFrame.cs

Follow up to #2187
Change IFrame.ChildFrames from IEnumerable to [IReadOnlyCollection](https://learn.microsoft.com/en-us/dotnet/api/system.collections.generic.ireadonlycollection-1?view=net-8.0)
My opinion it's just a little bit nicer to have a `Count` property rather than calling `Count()`.

IFrame.ChildFrames change from IEnumerable to IReadOnlyCollection

---

lib/PuppeteerSharp/ChromeTargetManager.cs
lib/PuppeteerSharp/Frame.cs

This [comment](https://github.com/hardkoded/puppeteer-sharp/pull/2190#discussion_r1174459542) triggered me to try making more members private instead of internal.
When a member is unused and then made private, it'll trigger different kinds of static analyzers it's unused.
See each commit description for more information about the two changes.
There were plenty of more places, where the member visibility could be reduced from internal -> private.
I'll be happy to open a PR with those changes if you like.

Remove unused members

---

lib/PuppeteerSharp.Tests/WaitTaskTests/FrameWaitForXPathTests.cs
lib/PuppeteerSharp/IsolatedWorld.cs
lib/PuppeteerSharp/WaitTask.cs

This should hopefully fix the `Evaluation failed: TypeError: fun is not a function` error. At least it does when I run it locally.
It looks like the whitespace is causing the `new Function` call to eval to null.
Lots of different places the whitespace could be trimmed, Could just as easily be done in `.Net`.
Reformatting the `const string` is also an option, my concern would be that formatting changes could break this again.

WaitTask Refactor - Fix Evaluation failed: TypeError: fun is not a function

---

lib/PuppeteerSharp/ElementHandle.cs

https://github.com/JamesNK/Newtonsoft.Json/issues/2352
The call to `JObject.Merge` doesn't actually do anything in `Newtonsoft.Json` version `13.0.1`
Newer versions of NewtonSoft.Json will throw "Could not determine JSON object type for type PuppeteerSharp.ViewPortOptions"
Resolves #2199

JObject.Merge does not work with object

---

lib/PuppeteerSharp/Browser.cs
lib/PuppeteerSharp/ChromeTargetManager.cs
lib/PuppeteerSharp/FirefoxTargetManager.cs
lib/PuppeteerSharp/IsolatedWorld.cs
lib/PuppeteerSharp/NetworkManager.cs

When an event handler is attached as part of the constructor and invoked before `_logger` has been populated we might throw an NRE.
Found by @leonardo-fernandes

Initialize logging earlier

---

lib/PuppeteerSharp/ChromeTargetManager.cs
lib/PuppeteerSharp/FirefoxTargetManager.cs
lib/PuppeteerSharp/NetworkEventManager.cs
lib/PuppeteerSharp/Page.cs

Found some places, where we can use built-in ConcurrentDictionary methods to reduce the number of lookups.
It might also improve thread-safety a tad, as currently a value could theoretically be removed/added between calls to `ContainsKey` and `TryGetValue`.
I refrained from updating `ChromeTargetManager.OnTargetCreated` and `ChromeTargetManager.OnAttachedToTarget` as the `valueFactory` might be evaluated more than once, to ensure that `_targetFactoryFunc` is still only evaluated once.
> If you call [GetOrAdd](https://learn.microsoft.com/en-us/dotnet/api/system.collections.concurrent.concurrentdictionary-2.getoradd?view=net-7.0) simultaneously on different threads, valueFactory may be called multiple times, but only one key/value pair will be added to the dictionary. …

More idiomatic usage of ConcurrentDictionary

---

lib/PuppeteerSharp/Connection.cs
lib/PuppeteerSharp/Worker.cs

Inspired by #2218 I found some more places, where we attach event handlers, before initializing instance members used by the event handlers.
Note, I haven't investigated if these scenarios can happen in practice, so this is a better-safe-than-sorry change.
```
Connection.ctor
attaching Transport_Closed
Close(string closeReason)
using _sessions
using _callbacks
using MessageQueue
initialize _callbacks
initialize _sessions
initialize MessageQueue
```    
```    
Worker.ctor
attaching OnMessageReceived
OnExecutionContextCreated(RuntimeExecutionContextCreatedResponse e)
using _executionContextCallback
initialize _executionContextCallback
```

Ensure members are initialized before attaching event handlers

---

lib/PuppeteerSharp/Response.cs

No tests seems to be asserting on this feature.
And only a few tests produces different `extra.Headers` `responseMessage.Headers`.
For e.g. `ShouldProperlyReportHttpOnlyCookie` `extraInfo.Headers` has an extra `Set-Cookie` header that `responseMessage.Headers` does not have.

Use Headers from extraInfo when available

---

lib/PuppeteerSharp.Tests/Attributes/SkipWindowsFact.cs
lib/PuppeteerSharp.Tests/LauncherTests/BrowserFetcherTests.cs

The built-in Windows command `tar` delegates handling of .tar.bzip2 archives to another command `bzip2`.
Windows 10 does not come with `bzip2` pre-installed.
Tests can only be decorated with a single attribute deriving from `FactAttribute`, that's the reason I replaced `PuppeteerFact`.
Fixes https://github.com/hardkoded/puppeteer-sharp/discussions/2130

Skip `ShouldDownloadAndExtractFirefoxLinuxBinary` on Windows

---

lib/PuppeteerSharp.Tests/ElementHandleTests/CustomQueriesTests.cs
lib/PuppeteerSharp.Tests/QuerySelectorTests/ElementHandleXPathTests.cs
lib/PuppeteerSharp.Tests/QuerySelectorTests/PageXPathTests.cs
lib/PuppeteerSharp.Tests/WaitTaskTests/FrameWaitForXPathTests.cs
lib/PuppeteerSharp.Tests/WaitTaskTests/PageWaitForTests.cs
lib/PuppeteerSharp/CustomQueriesManager.cs
lib/PuppeteerSharp/ElementHandle.cs
lib/PuppeteerSharp/Frame.cs
lib/PuppeteerSharp/IElementHandle.cs
lib/PuppeteerSharp/IFrame.cs
lib/PuppeteerSharp/IPage.cs
lib/PuppeteerSharp/IsolatedWorld.cs
lib/PuppeteerSharp/Page.cs

Use xpath query handler

---

lib/PuppeteerSharp.Tests/InjectedTests/InjectedTests.cs
lib/PuppeteerSharp/CustomQueriesManager.cs
lib/PuppeteerSharp/ExecutionContext.cs
lib/PuppeteerSharp/Frame.cs
lib/PuppeteerSharp/IsolatedWorld.cs
lib/PuppeteerSharp/WaitTask.cs

It matches [stream code](https://github.com/puppeteer/puppeteer/commit/050a7b062415ebaf10bcb71c405143eacc4e5d4b)

Atomically get Puppeteer utilities

---

lib/PuppeteerSharp/CustomQueriesManager.cs

Custom queries manager improvements

---

lib/PuppeteerSharp.Tests/NavigationTests/PageGotoTests.cs
lib/PuppeteerSharp/FrameManager.cs
lib/PuppeteerSharp/LifecycleWatcher.cs

I started investigating why PageGotoTests were failing sometimes with NullReferenceException (e.g. https://github.com/hardkoded/puppeteer-sharp/actions/runs/5257640661/jobs/9500723964).
I found that, when the tests fails, the Response object wasn't initialized yet in the test's thread, but another thread was concurrently processing a message that would initialize it. More investigation indicated that the timing and order of two messages would determine if the test passed/failed.
* The `Page.navigate` message is sent to initiate the navigation. This message awaits for `NewDocumentNavigationTask` from LifecycleWatcher.
* Two messages, `Network.responseReceived` and `Network.responseReceivedExtraInfo`, are received as a result of the navigation. It seems that `Network.responseReceived` is …

Fix PageGotoTests

---

lib/PuppeteerSharp.Tests/NavigationTests/PageGotoTests.cs

The `responses` collection is accessed by multiple concurrent requests, so we should use a thread-safe collection. We should also be careful to clear the collection before the next element has any chance of being added to it.

Fix flakyness of ShouldWaitForNetworkIdleToSucceedNavigation test

---

lib/PuppeteerSharp/BrowserFetcher.cs
lib/PuppeteerSharp/Platform.cs
lib/PuppeteerSharp/PuppeteerSharp.csproj

We are also making the `Platform` property read-write. So users can opt to keep downloading the intel version by setting `Platform` to `Platform.MacOS`.
closes #1861

Introduce  chromium for MacOS arm64 downloads

---

lib/PuppeteerSharp.Tests/CoverageTests/CSSCoverageTests.cs
lib/PuppeteerSharp.Tests/CoverageTests/JSCoverageTests.cs
lib/PuppeteerSharp.Tests/NavigationTests/FrameGoToTests.cs
lib/PuppeteerSharp.Tests/PageTests/ExposeFunctionTests.cs
lib/PuppeteerSharp/BrowserFetcher.cs
lib/PuppeteerSharp/PuppeteerSharp.csproj

Upgrade chrome to 1108766

---

lib/PuppeteerSharp/BrowserData/Chromium.cs
lib/PuppeteerSharp/PuppeteerSharp.csproj

There is an issue where the URL has an extra dollar sign (`$`) in the string interpolation, breaking the URL.
This results in a URL like this, giving 404 Not Found
- https://storage.googleapis.com/chromium-browser-snapshots/$Mac_Arm/LAST_CHANGE
Removing the extra dollar sign fixes the issue, giving a correct URL:
- https://storage.googleapis.com/chromium-browser-snapshots/Mac_Arm/LAST_CHANGE

Fix URL for Chromium ResolveBuildIdAsync()

---

lib/PuppeteerSharp/ChromeTargetManager.cs
lib/PuppeteerSharp/IsolatedWorld.cs
lib/PuppeteerSharp/Page.cs
lib/PuppeteerSharp/Worker.cs

Follow-up to #2214 where `OnTargetDestroyed` was changed from `void` to `async void`.

Avoid unhandled exceptions on unawaited async path

---

lib/PuppeteerSharp/IsolatedWorld.cs

When working on #2297 I noticed that something related to `IsolatedWorld` also leaked memory.
master:
PR:
The many remaining `TaskCompletionSource<>` are handled in #2297
With both PRs:
Tested with this code
```cs
[PuppeteerTest("frame.spec.ts", "Frame Management", "should handle nested frames")]
[Skip(SkipAttribute.Targets.Firefox)]
public async Task ShouldHandleNestedFrames()
{
GC.Collect(4, GCCollectionMode.Forced, true, true);
GC.WaitForPendingFinalizers();
// <-- heap dump
for (var i = 0; i < 100; i++)
{
_ = await Page.GoToAsync(TestConstants.ServerUrl + "/frames/nested-frames.html");
}
GC.Collect(4, GCCollectionMode.Forced, true, true);
GC.WaitForPendingFinalizers();
// <-- heap dump and showed diff
}
```

Detach client event handler when detaching `IsolatedWorld`

---

lib/PuppeteerSharp/Browser.cs
lib/PuppeteerSharp/ChromeTargetManager.cs
lib/PuppeteerSharp/Connection.cs
lib/PuppeteerSharp/FirefoxTargetManager.cs
lib/PuppeteerSharp/FrameTree.cs
lib/PuppeteerSharp/Helpers/AsyncDictionaryHelper.cs
lib/PuppeteerSharp/Helpers/MultiMap.cs
lib/PuppeteerSharp/Target.cs

To ensure that entries from `_pendingRequests` are removed when removing a key from `_dictionary`.
See [discussion](https://github.com/hardkoded/puppeteer-sharp/discussions/2283) for more details.

Fix memory leaks with `AsyncDictionaryHelper`

---

.github/workflows/PushNugetPackageToIntNugetOrg.yml
.github/workflows/PushNugetPackageToNugetOrg.yml
.github/workflows/demo.yml
.github/workflows/dotnet.yml
demos/PuppeteerSharpPdfDemo/Program.cs
demos/PuppeteerSharpPdfDemo/PuppeteerSharpPdfDemo-Local.csproj
demos/PuppeteerSharpPdfDemo/PuppeteerSharpPdfDemo.csproj
lib/PuppeteerSharp.DevicesFetcher/PuppeteerSharp.DevicesFetcher.csproj
lib/PuppeteerSharp.Nunit/PuppeteerSharp.Nunit.csproj
lib/PuppeteerSharp.TestServer/PuppeteerSharp.TestServer.csproj
lib/PuppeteerSharp.TestServer/SimpleServer.cs
lib/PuppeteerSharp.Tests.DumpIO/PuppeteerSharp.Tests.DumpIO.csproj
lib/PuppeteerSharp.Tests.SingleFileDeployment/PuppeteerSharp.Tests.SingleFileDeployment.csproj
lib/PuppeteerSharp.Tests/CookiesTests/SetCookiesTests.cs
lib/PuppeteerSharp.Tests/FixturesTests/FixturesTests.cs
lib/PuppeteerSharp.Tests/PuppeteerSharp.Tests.csproj
lib/PuppeteerSharp.Tests/TestConstants.cs
lib/PuppeteerSharp.Tooling/PuppeteerSharp.Tooling.csproj
samples/complex-js-objects/complex-js-objects.csproj
samples/get-all-links/get-all-links.csproj
samples/reuse-downloaded-chrome/reuse-downloaded-chrome.csproj
samples/searching/searching.csproj

It moves all the builds to net7 and removes builds for .NET Framework. As Puppeteer-Sharp is a netstandard library, it will still work in .NET Framework, but we won't run on that framework anymore.
It also closes #2175

Dropping .NET Framework test builds

---

lib/PuppeteerSharp/Browser.cs
lib/PuppeteerSharp/OtherTarget.cs
lib/PuppeteerSharp/PageTarget.cs
lib/PuppeteerSharp/Target.cs
lib/PuppeteerSharp/WorkerTarget.cs

Based on https://github.com/puppeteer/puppeteer/pull/10181

Add WorkerTarget and OtherTarget

---

lib/PuppeteerSharp.Tests/LauncherTests/PuppeteerConnectTests.cs
lib/PuppeteerSharp/Browser.cs
lib/PuppeteerSharp/BrowserContext.cs
lib/PuppeteerSharp/ChromeTargetManager.cs
lib/PuppeteerSharp/ConnectOptions.cs
lib/PuppeteerSharp/FirefoxTargetManager.cs
lib/PuppeteerSharp/IConnectionOptions.cs
lib/PuppeteerSharp/LaunchOptions.cs
lib/PuppeteerSharp/PuppeteerSharp.csproj

This will bring [these changes](https://github.com/puppeteer/puppeteer/pull/10601).
It's a breaking change because we are exposing the TargetFilter, and we changed its type.

BREAKING: Use target for filters

---

lib/PuppeteerSharp.Tests/AccessibilityTests/AccessibilityTests.cs
lib/PuppeteerSharp.Tests/AccessibilityTests/RootOptionTests.cs
lib/PuppeteerSharp/BrowserData/Chrome.cs
lib/PuppeteerSharp/PageAccessibility/AXNode.cs

ref https://github.com/puppeteer/puppeteer/pull/10893/files

Roll to Chrome 117.0.5938.62 (r1181205)

---

lib/PuppeteerSharp/BrowserContext.cs
lib/PuppeteerSharp/IBrowserContext.cs

Puppeteer implemented that [here](https://github.com/puppeteer/puppeteer/pull/10928) with the name `Closed`, but I think `IsClosed` matches other properties.

Implement BrowserContext.IsClosed

---

lib/PuppeteerSharp.Tests/CoverageTests/JSCoverageTests.cs
lib/PuppeteerSharp.Tests/InputTests/FileChooserCancelTests.cs
lib/PuppeteerSharp/ElementHandle.cs
lib/PuppeteerSharp/FileChooser.cs
lib/PuppeteerSharp/PuppeteerSharp.csproj

BREAKING CHANGE: FileChooser.Cancel was renamed to FileChooser.CancelAsync, and it nows returns a task.
[See upstream change](https://github.com/puppeteer/puppeteer/pull/11057)

[BREAKING] Update file chooser events

---

lib/PuppeteerSharp/PuppeteerSharp.csproj

Microsoft.AspNetCore.WebUtilities 2.2.0 depends on System.Text.Encodings.Web 4.5.0 which is marked as vulnerable.
System.Text.Encodings.Web was bumped to 6.0.0 in #2016.
Microsoft.AspNetCore.WebUtilities was removed in #2324.

Remove System.Text.Encodings.Web

---

lib/PuppeteerSharp/QueryHandlers/AriaQueryHandler.cs

[See upstream change](https://github.com/puppeteer/puppeteer/pull/11142)

fix: add InlineTextBox as a non-element a11y role

---

lib/PuppeteerSharp.Tests/BrowserContextTests/BrowserContextTests.cs
lib/PuppeteerSharp/IBrowserContext.cs

In Chrome, the default browser context can also be "icognito" if configured via the arguments and in such cases this getter returns wrong results (see https://github.com/puppeteer/puppeteer/issues/8836). Also, the term "incognito" is not applicable to other browsers. To migrate, check the default browser context instead: in Chrome all non-default contexts are incognito, and the default context might be incognito if you provide the `--incognito` argument when launching the browser.
closes #2462

Deprecate is incognito

---

docfx_project/examples/DownloadFetcher.Download.md
lib/PuppeteerSharp/Cdp/CdpPage.cs
lib/PuppeteerSharp/Cdp/CdpPageTarget.cs
lib/PuppeteerSharp/Cdp/CdpTarget.cs
lib/PuppeteerSharp/Frame.cs
lib/PuppeteerSharp/IFrame.cs
lib/PuppeteerSharp/IResponse.cs
lib/PuppeteerSharp/Page.cs
lib/PuppeteerSharp/TimeoutSettings.cs

Split page

---

tools/github-ops/create-issue-from-file.js

Just a tool I use to create split issues.

DevOps: Create issue from a file

---

lib/.editorconfig
lib/PuppeteerSharp/BrowserData/Firefox.cs
lib/PuppeteerSharp/BrowserFetcher.cs
lib/PuppeteerSharp/Cdp/CdpElementHandle.cs
lib/PuppeteerSharp/Cdp/CdpJSHandle.cs
lib/PuppeteerSharp/Cdp/CdpPage.cs
lib/PuppeteerSharp/Cdp/FrameManager.cs
lib/PuppeteerSharp/Cdp/Messaging/FetchFulfillRequest.cs
lib/PuppeteerSharp/Helpers/AsyncMessageQueue.cs
lib/PuppeteerSharp/Helpers/RemoteObjectHelper.cs
lib/PuppeteerSharp/IsolatedWorld.cs
lib/PuppeteerSharp/Page.cs
lib/PuppeteerSharp/PuppeteerSharp.csproj
lib/PuppeteerSharp/QueryHandlers/QueryHandler.cs
lib/PuppeteerSharp/Request.cs
lib/PuppeteerSharp/ScriptInjector.cs
lib/PuppeteerSharp/States/State.cs
lib/PuppeteerSharp/ViewPortOptions.cs

While looking at #2615 I noticed some other things.

Apply analyzer suggestions

---

lib/PuppeteerSharp/PuppeteerSharp.csproj

Updates the version numbers in `lib/PuppeteerSharp/PuppeteerSharp.csproj` to 18.0.2.
- **Version Updates**: Changes the `<PackageVersion>`, `<AssemblyVersion>`, and `<FileVersion>` tags from `18.0.1` to `18.0.2`, ensuring all version references within the project file are consistent with the new patch version.
- **Consistency**: Maintains the alignment of version numbers across the project, facilitating better version tracking and package management.
---
For more details, open the [Copilot Workspace session](https://copilot-workspace.githubnext.com/hardkoded/puppeteer-sharp?shareId=aef35461-6107-4e55-b4cc-694e7889832f).

Bump patch version to 18.0.2

---

lib/PuppeteerSharp.Tests/PuppeteerBrowserBaseTest.cs
lib/PuppeteerSharp.Tests/PuppeteerPageBaseTest.cs

If the `[SetUp]` methods failed to construct and assign `Browser` or `Page`, the `[TearDown]` methods would throw an NRE.

Gracefully tear down test if SetUp failed

---

lib/PuppeteerSharp.Tests/BrowserContextTests/BrowserContextTests.cs
lib/PuppeteerSharp/BrowserContext.cs

The PR fixes `BrowserContext.IsClosed`. The property returns true when a context is not closed.

Fix: `BrowserContext.IsClosed` returns true when a context is not closed

---

lib/PuppeteerSharp.Tests/NavigationTests/PageWaitForNavigationTests.cs
lib/PuppeteerSharp/BrowserData/Chrome.cs
lib/PuppeteerSharp/BrowserFetcher.cs

This reverts commit 1b2236945528535214a90f4022eed0ca76238200.
Chrome 125 proved to be a headache for many windows users. We will roll this back till we find a better solution.
Closes #2658 and #2657

Rollback to Chrome 124

---

lib/PuppeteerSharp/Page.cs
lib/PuppeteerSharp/PuppeteerSharp.csproj

Puppeteer always closes the page on disposal.

Close page on disposal

---

lib/PuppeteerSharp/BrowserData/InstalledBrowser.cs
lib/PuppeteerSharp/BrowserFetcher.cs
lib/PuppeteerSharp/Cdp/CdpPage.cs
lib/PuppeteerSharp/Cdp/LifecycleWatcher.cs
lib/PuppeteerSharp/ScreenshotOptions.cs

Instead of initializing and looking up values in small dictionaries, it's faster to simply use a switch expression and we can also (I would say) better name the lookup methods.
I implemented them as private static functions, but they also have been static local functions.

Replace small dictionaries with switch

---

lib/PuppeteerSharp.Tests/BrowserContextTests/BrowserContextOverridePermissionsTests.cs
lib/PuppeteerSharp/BrowserData/Cache.cs
lib/PuppeteerSharp/BrowserData/Firefox.cs
lib/PuppeteerSharp/Helpers/EnumHelper.cs

First proposed in https://github.com/hardkoded/puppeteer-sharp/pull/2713#discussion_r1703996482
This avoid constructing the instances of `ConcurrentDictionary` in `EnumHelper` by applying the "Type-Dictionary Trick" from https://mariusgundersen.net/type-dictionary-trick/.
In addition this PR changes the .NET 8 TFM to use generic `Enum` variants.

Apply the Type-Dictionary Trick

---

lib/PuppeteerSharp/Cdp/Connection.cs
lib/PuppeteerSharp/Transport/MessageReceivedEventArgs.cs
lib/PuppeteerSharp/Transport/WebSocketTransport.cs

Since System.Text.Json supports deserializing directly from byte arrays we can avoid some unnecessary en/decoding.

Use byte array in message received to avoid some unnecessary encoding

---

lib/PuppeteerSharp.Tests/PollerInterceptor.cs
lib/PuppeteerSharp/Cdp/Connection.cs
lib/PuppeteerSharp/MessageTask.cs
lib/PuppeteerSharp/Transport/IConnectionTransport.cs
lib/PuppeteerSharp/Transport/WebSocketTransport.cs

Similar to #2748 System.Text.Json can also serialize directly to bytes to avoid some unnecessary [en](https://github.com/dotnet/runtime/blob/d3154144ae65a77585de29892ec41517f0add61e/src/libraries/System.Text.Json/src/System/Text/Json/Serialization/JsonSerializer.Write.String.cs#L164)/[decoding](https://github.com/campersau/puppeteer-sharp/blob/39f23de3c9b9f71178eb9d612bf66f3531bc0ec5/lib/PuppeteerSharp/Transport/WebSocketTransport.cs#L75).

Use byte array in message send to avoid some unnecessary encoding

---

lib/PuppeteerSharp/BrowserData/InstalledBrowser.cs
lib/PuppeteerSharp/BrowserFetcher.cs
lib/PuppeteerSharp/PuppeteerSharp.csproj

This will add an extra way to triage issues deploying the browser in the cloud.

Return whether the permissions fix was executed successfully

---

lib/PuppeteerSharp.Tests/BrowserContextTests/BrowserContextOverridePermissionsTests.cs
lib/PuppeteerSharp.Tests/BrowserContextTests/BrowserContextTests.cs
lib/PuppeteerSharp.Tests/CookiesTests/SetCookiesTests.cs
lib/PuppeteerSharp/BrowserContext.cs
lib/PuppeteerSharp/IBrowserContext.cs

Makes it more convenient to use and aligns with upstream implementation:
https://github.com/puppeteer/puppeteer/blob/3ad2e45c295083de6fc72a5041138c620615b755/packages/puppeteer-core/src/api/BrowserContext.ts#L260-L268
In the second commit I also updated some tests. Looks like this wasn't done upstream so please let me know if I should remove it.

Implement IAsyncDisposable / IDisposable on IBrowserContext

---

README.md
lib/PuppeteerSharp.Tests/PageTests/PdfTests.cs
lib/PuppeteerSharp/BrowserData/Chrome.cs
lib/PuppeteerSharp/Cdp/CdpPage.cs
lib/PuppeteerSharp/Helpers/Json/PrimitiveTypeConverter.cs
lib/PuppeteerSharp/Media/MarginOptions.cs
lib/PuppeteerSharp/Media/PaperFormat.cs
lib/PuppeteerSharp/PdfOptions.cs
lib/PuppeteerSharp/PuppeteerSharp.csproj

Because:
1. [Upstream `PDFMargin` uses `string | number`](https://github.com/puppeteer/puppeteer/blob/3ad2e45c295083de6fc72a5041138c620615b755/packages/puppeteer-core/src/common/PDFOptions.ts#L10-L15)
2. [`PDFOptions.Width` / `PDFOptions.Height` also use `string | number` upstream](https://github.com/puppeteer/puppeteer/blob/3ad2e45c295083de6fc72a5041138c620615b755/packages/puppeteer-core/src/common/PDFOptions.ts#L125-L132)
3. `PdfOptions.Width` / `PdfOptions.Height` using `object` https://github.com/hardkoded/puppeteer-sharp/blob/e14f59da8d95536e0002efa13f451f2dc5c1c762/lib/PuppeteerSharp/PdfOptions.cs#L67-L75
4. All of these properties were already going to `ConvertPrintParameterToInches` https://github.com/hardkoded/puppeteer-sharp/blob/e14f59da8d95536e0002efa13f451f2dc5c1c762/lib/Puppe …

Use object for Top / Left / Bottom / Right in MarginOptions

---

lib/PuppeteerSharp/Cdp/CdpPage.cs
lib/PuppeteerSharp/Cdp/NetworkEventManager.cs
lib/PuppeteerSharp/Cdp/NetworkManager.cs
lib/PuppeteerSharp/Page.cs
lib/PuppeteerSharp/WaitForNetworkIdleOptions.cs

This will get us closer to the implementation we need for Bidi.

Refactor WaitForNetworkIdle

---

lib/PuppeteerSharp/IsExternalInit.cs

Added conditional compilation to use type forwarding for net8.0 target as suggested here - https://github.com/dotnet/runtime/issues/79082#issuecomment-1333716389. Required to correctly handle public init properties.

Use type forwarding for IsExternalInit on .net8 target
